using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Networking;
using System.Diagnostics;
using System.Net;
using System.Net.Http.Headers;
using System;
using System.IO;
using System.Text;
using TMPro;
using System.Threading;
using System.Linq;
using UnityEngine.UIElements;
using Microsoft.CognitiveServices.Speech;
using static SettingManager;
using System.Threading.Tasks;
using UnityEditor.VersionControl;

public class Tts
{
    public string Phrase;

    public double Octave;

    public string Email;

    public string Title;

    public Dictionary<string, string[]> Options = new Dictionary<string, string[]>
    {
        { "Arabic",new string[] { "Farah", } },
        { "Chinese (Mandarin)",new string[] { "Daiyu", } },
        { "Danish",new string[] { "Emma", "Oscar", } },
        { "Dutch",new string[] { "Anke","Adriaan", } },
        { "English (Australian)",new string[] { "Mia","Grace","Jack", } },
        { "English (British)",new string[] { "Charlotte","Sophia","Elijah", } },
        { "English (Indian)",new string[] { "Advika","Onkar", } },
        { "English (New Zealand)",new string[] { "Ruby", } },
        { "English (South African)",new string[] { "Elna", } },
        { "English (US)",new string[] { "Mary","Linda","Patricia","Barbara","Susan","Paul","Michael","William","Thomas", } },
        { "English (Welsh)",new string[] { "Aeron", } },
        { "French",new string[] { "Capucine","Alix","Arnaud", } },
        { "French (Canadian)",new string[] { "Stephanie","Celine", } },
        { "German",new string[] { "Maria","Theresa","Felix", } },
        { "Hindi",new string[] { "Chhaya", } },
        { "Icelandic",new string[] { "Anna","Sigriour", } },
        { "Italian",new string[] { "Gabriella","Bella","Lorenzo", } },
        { "Japanese",new string[] { "Rika","Tanaka", } },
        { "Korean",new string[] { "Ji-Ho", } },
        { "Norwegian",new string[] { "Camilla", } },
        { "Polish",new string[] { "Katarzyna","Malgorzata","Piotr","Jan", } },
        { "Portuguese (Brazilian)",new string[] { "Tabata","Juliana","Pedro", } },
        { "Portuguese (European)",new string[] { "Pati","Adriano", } },
        { "Romanian",new string[] { "Alexandra", } },
        { "Russian",new string[] { "Inessa","Viktor", } },
        { "Spanish (European)",new string[] { "Francisca","Margarita","Mateo", } },
        { "Spanish (Mexican)",new string[] { "Leticia", } },
        { "Spanish (US)",new string[] { "Josefina","Rosa","Miguel", } },
        { "Swedish",new string[] { "Eva", } },
        { "Turkish",new string[] { "Mesut", } },
        { "Welsh",new string[] { "Angharad", } },
    };

    public string[] Langues = new string[]
        {
            "Arabic", "Chinese (Mandarin)", "Danish", "Dutch", "English (Australian)", "English (British)", "English (Indian)", "English (New Zealand)", "English (South African)", "English (US)", "English (Welsh)", "French", "French (Canadian)", "German", "Hindi", "Icelandic", "Italian", "Japanese", "Korean", "Norwegian", "Polish", "Portuguese (Brazilian)", "Portuguese (European)", "Romanian", "Russian", "Spanish (European)", "Spanish (Mexican)", "Spanish (US)", "Swedish", "Turkish", "Welsh",
        };

    public int Selected_O = 0;
    public int Selected_L = 0;
}
public class Synthese
{
    public string sentence;
    public string audio;

}
public class Authorization
{
    public string api_key = "kGOdv5yl.oqUd2gMibwhBVp5C6ed57Wpxvs2LUKOW";

}

public class SpeechGeneration
{
    //懒汉式单例类.在第一次调用的时候实例化自己 
    private SpeechGeneration() { }
    private static SpeechGeneration manager = null;
    //静态工厂方法 
    public static SpeechGeneration Instance()
    {
        if (manager == null)
        {
            manager = new SpeechGeneration();
        }
        return manager;
    }
    private Tts _tts = new Tts();

    public string url;
    UnityWebRequest www;

    public AudioClip son_pilou;

    private Synthese info = null;

    string s_octave;

    int selectedOctave = 0;
    string[] selStrings = { "normal pitch (0)", "low pitch (-0.5)", "high pitch (+0.5)", "custom pitch between -1 and +1" };

    private AudioClip TextToAudio(string option, string phrase, string title, double octave, string apikey)
    {
        if (apikey == null)
        {
            //UnityEngine.Debug.LogError("Please contact the support");
            return null;
        }

        if (phrase == null || phrase == "")
        {
            // UnityEngine.Debug.LogError("Text is empty");
            return null;
        }
        www = null;

        WWWForm form = new WWWForm();
        form.AddField("sentence", phrase);
        s_octave = octave.ToString();
        form.AddField("octave", s_octave.Replace(',', '.'));
        //form.AddField("speed", "1");
        string lien = $"https://ariel-api.xandimmersion.com/tts/{option}";
        www = UnityWebRequest.Post(lien, form);
        www.SetRequestHeader("Authorization", "Api-Key " + apikey);

        www.SendWebRequest();
        while (!www.isDone)
        {
            continue;
        }

        //if (www.result != UnityWebRequest.Result.Success)
        //{
        //    UnityEngine.Debug.LogError("Error While Sending: " + www.error);
        //}
        //else
        {
            info = JsonUtility.FromJson<Synthese>(www.downloadHandler.text);

        }

        url = "https://rocky-taiga-14840.herokuapp.com/" + info.audio;
        using (UnityWebRequest www_audio = UnityWebRequestMultimedia.GetAudioClip(info.audio, AudioType.WAV))
        {
            www_audio.SetRequestHeader("x-requested-with", "http://127.0.0.1:8080");

            www_audio.SendWebRequest();


            while (!www_audio.isDone)
            {
                continue; //ajouter une barre de chargement
            }


            if (www_audio.isNetworkError)
            {
                //    UnityEngine.Debug.LogError(www_audio.error);
            }
            else
            {
                AudioClip son_pilou = DownloadHandlerAudioClip.GetContent(www_audio);
                if (title == null)
                {
                    //   UnityEngine.Debug.Log("No file name : file will be saved at untitled-gen.wav");
                    title = "untitled";
                }
                // UnityEngine.Debug.Log("Audio Generation In Progress.");
                return son_pilou;
                //SavWav.Save($"SpeechGenerationForNPCs/SavedAudioFiles/{title}-gen", son_pilou);

            }
        }



        info = null;
        return null;
    }

    public AudioClip Speek(string word)
    {
        Tts tts = _tts;

        tts.Phrase = word;// EditorGUILayout.TextField("Text to Audio file", tts.Phrase, GUI.skin.textArea, GUILayout.Height(100));

        //selectedOctave = GUILayout.SelectionGrid(selectedOctave, selStrings, 2, GUI.skin.toggle);

        //switch (selectedOctave)
        //{
        //    case 0:
        //        tts.Octave = 0;
        //        break;
        //    case 1:
        //        tts.Octave = -0.5;
        //        break;
        //    case 2:
        //        tts.Octave = 0.5;
        //        break;
        //    case 3:
        //        tts.Octave = EditorGUILayout.DoubleField("Custom Octave", tts.Octave, GUI.skin.textArea);
        //        break;
        //    default:
        //        tts.Octave = 0;
        //        break;
        //}

        tts.Title = word;

        tts.Selected_L = 9;// "English (US)";// EditorGUILayout.Popup("Select Language", tts.Selected_L, tts.Langues);

        tts.Selected_O = 5;//"Paul";// EditorGUILayout.Popup("Select Voice", tts.Selected_O, tts.Options[tts.Langues[tts.Selected_L].ToString()]);


        //  if (GUILayout.Button("Save to wav"))
        // {
        return TextToAudio(tts.Options[tts.Langues[tts.Selected_L].ToString()][tts.Selected_O], tts.Phrase, tts.Title, tts.Octave, "kGOdv5yl.oqUd2gMibwhBVp5C6ed57Wpxvs2LUKOW");
        //     }

    }
    public AudioClip SpeekCN(string word)
    {
        Tts tts = _tts;

        tts.Phrase = word;// EditorGUILayout.TextField("Text to Audio file", tts.Phrase, GUI.skin.textArea, GUILayout.Height(100));

        //selectedOctave = GUILayout.SelectionGrid(selectedOctave, selStrings, 2, GUI.skin.toggle);

        //switch (selectedOctave)
        //{
        //    case 0:
        //        tts.Octave = 0;
        //        break;
        //    case 1:
        //        tts.Octave = -0.5;
        //        break;
        //    case 2:
        //        tts.Octave = 0.5;
        //        break;
        //    case 3:
        //        tts.Octave = EditorGUILayout.DoubleField("Custom Octave", tts.Octave, GUI.skin.textArea);
        //        break;
        //    default:
        //        tts.Octave = 0;
        //        break;
        //}

        tts.Title = word;

        tts.Selected_L = 1;// "Chinese";// EditorGUILayout.Popup("Select Language", tts.Selected_L, tts.Langues);

        tts.Selected_O = 0;//"Paul";// EditorGUILayout.Popup("Select Voice", tts.Selected_O, tts.Options[tts.Langues[tts.Selected_L].ToString()]);


        //  if (GUILayout.Button("Save to wav"))
        // {
        return TextToAudio(tts.Options[tts.Langues[tts.Selected_L].ToString()][tts.Selected_O], tts.Phrase, tts.Title, tts.Octave, "kGOdv5yl.oqUd2gMibwhBVp5C6ed57Wpxvs2LUKOW");
        //     }

    }
    //private string m_SpeechSynthesisVoiceName = "zh-CN-XiaoyouNeural";
    //private string m_SpeechSynthesisVoiceName = "si-LK-ThiliniNeural";
    private string m_SpeechSynthesisVoiceName = "te-IN-MohanNeural";//泰卢固语（印度）男
    private string m_SpeechTLGVoiceFemale = "te-IN-ShrutiNeural";//泰卢固语（印度）女
    private string m_SpeechTLGVoiceMale = "te-IN-MohanNeural";//泰卢固语（印度）男
    private string m_SpeechMMVoiceFemale = "my-MM-NilarNeural";//缅甸语女
    private string m_SpeechMMVoiceMale = "my-MM-ThihaNeural";//缅甸语男
    private string m_SpeechSLKVoiceFemale = "si-LK-ThiliniNeural";//缅甸语女
    private string m_SpeechSLKVoiceMale = "si-LK-SameeraNeural";//缅甸语男


    string language_TLG = "te-IN";
    string language_MM = "my-MM";
    string language_SLK = "si-LK";
    //private string m_SpeechSynthesisVoiceName = "te-IN-ShrutiNeural";//泰卢固语（印度）女
    //private string m_SpeechSynthesisVoiceName = "si-LK-SameeraNeural";

    public string GetVoice()
    {
        PaliSpeakVoiceGender gender = SettingManager.Instance().GetPaliVoiceGender();
        PaliSpeakVoiceType vt = SettingManager.Instance().GetPaliVoiceType();
        if (gender == PaliSpeakVoiceGender.Male)
        {
            if (vt == PaliSpeakVoiceType.Telugu)
            {
                return m_SpeechTLGVoiceMale;
            }
            else if (vt == PaliSpeakVoiceType.Myanmar)
            {
                return m_SpeechMMVoiceMale;
            }
            //else if (vt == PaliSpeakVoiceType.Sinhala)
            //{
            //    return m_SpeechSLKVoiceMale;
            //}
        }
        else
        {
            if (vt == PaliSpeakVoiceType.Telugu)
            {
                return m_SpeechTLGVoiceFemale;
            }
            else if (vt == PaliSpeakVoiceType.Myanmar)
            {
                return m_SpeechMMVoiceFemale;
            }
            //else if (vt == PaliSpeakVoiceType.Sinhala)
            //{
            //    return m_SpeechSLKVoiceFemale;
            //}
        }
        return "";
    }
    public string GetLanguage()
    {
        PaliSpeakVoiceType vt = SettingManager.Instance().GetPaliVoiceType();
        if (vt == PaliSpeakVoiceType.Telugu)
        {
            return language_TLG;
        }
        else if (vt == PaliSpeakVoiceType.Myanmar)
        {
            return language_MM;
        }
        //else if (vt == PaliSpeakVoiceType.Sinhala)
        //{
        //    return language_SLK;
        //}
        return "";
    }
    //数字不读
    public AudioClip SpeekPali(string word, int speed = 0)
    {
        // Creates an instance of a speech config with specified subscription key and service region.
        // Replace with your own subscription key and service region (e.g., "westus").
        var config = SpeechConfig.FromSubscription("82563fdf180f434aaf8c8f14171bae6c", "eastus");
        string voice = GetVoice();
        //config.SpeechSynthesisLanguage = m_SpeechSynthesisLanguage;
        config.SpeechSynthesisVoiceName = voice;
        // Creates a speech synthesizer.
        // Make sure to dispose the synthesizer after use!
        using (var synthsizer = new SpeechSynthesizer(config, null))
        {
            //lock (threadLocker)
            //{
            //    waitingForSpeak = true;
            //}
            // string temp = "සම්පන්නපාතිමොක්ඛා ති ප‍රිපුණ්ණපාතිමොක්ඛා .";
            speed = (int)SettingManager.Instance().GetPaliVoiceSpeed();
            //speed = -20;
            string text = @"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='" + GetLanguage() + "'><voice name='" + voice + "'><prosody rate='" + speed.ToString() + "%'>" + word + "</prosody></voice></speak>";
            // string text = @"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis'><voice name='" + voice + "'><prosody rate='" + speed.ToString() + "%'>" + word + "</prosody></voice></speak>";
            //UnityEngine.Debug.LogError(text);
            var result = synthsizer.SpeakSsmlAsync(text).Result;
            // var result = synthsizer.SpeakTextAsync(word).Result;
            //print("after   " + DateTime.Now);

            // Checks result.
            string newMessage = string.Empty;

            if (result.Reason == ResultReason.SynthesizingAudioCompleted)
            {
                // Since native playback is not yet supported on Unity yet (currently only supported on Windows/Linux Desktop),
                // use the Unity API to play audio here as a short term solution.
                // Native playback support will be added in the future release.
                var sampleCount = result.AudioData.Length / 2;
                var audioData = new float[sampleCount];
                for (var i = 0; i < sampleCount; ++i)
                {
                    audioData[i] = (short)(result.AudioData[i * 2 + 1] << 8 | result.AudioData[i * 2]) / 32768.0F;

                }
                // The default output audio format is 16K 16bit mono
                var audioClip = AudioClip.Create("SynthesizedAudio", sampleCount, 1, 16000, false);
                audioClip.SetData(audioData, 0);
                return audioClip;
                //audioSource.clip = audioClip;
                //audioSource.Play();
                //endTime = DateTime.Now;
                //timeText.text = "合成前时间：" + startTime + "     合成成功时间：" + endTime;

                //newMessage = "Speech synthesis succeeded!";
            }

            else if (result.Reason == ResultReason.Canceled)
            {
                var cancellation = SpeechSynthesisCancellationDetails.FromResult(result);
                newMessage = $"CANCELED:\nReason=[{cancellation.Reason}]\nErrorDetails=[{cancellation.ErrorDetails}]\nDid you update the subscription info?";
            }
            return null;
            //lock (threadLocker)
            //{
            //    message = newMessage;
            //    waitingForSpeak = false;
            //}
        }
    }

    public string ReplaceWord(string word)
    {
        //不读数字
        word = RemoveNumber(word);
        PaliSpeakVoiceType vt = SettingManager.Instance().GetPaliVoiceType();
        if (vt == PaliSpeakVoiceType.Telugu)
        {
            word = ReplaceWordTLG(word);
        }
        else if (vt == PaliSpeakVoiceType.Myanmar)
        {
            word = ReplaceWordMy(word);

        }
        //else if (vt == PaliSpeakVoiceType.Sinhala)
        //{
        //    word = ReplaceWordSI(word);
        //}

        return word;
    }
    public string RemoveNumber(string key)
    {
        return System.Text.RegularExpressions.Regex.Replace(key, @"\d", "");
    }
    public string ReplaceWordEN(string word)
    {
        word = word.Replace("r", "l");
        word = word.Replace("ṭṭh", "t");
        word = word.Replace("ṭh", "t");
        word = word.Replace("bbh", "p");
        word = word.Replace("bh", "p");
        word = word.Replace("ggh", "k");
        word = word.Replace("gh", "k");
        word = word.Replace("c", "j");
        word = word.Replace("tth", "t");
        word = word.Replace("th", "t");
        word = word.Replace("ddh", "t");
        word = word.Replace("dh", "t");
        return word;
    }

    public string ReplaceWordSI(string word)
    {
        foreach (KeyValuePair<string, string> kvp in char_unicode_to_si)
        {
            word = word.Replace(kvp.Key, kvp.Value);
        }
        return word;
    }
    public string ReplaceWordTLG(string word)
    {
        foreach (KeyValuePair<string, string> kvp in char_unicode_to_tlg_txt)
        {
            word = word.Replace(kvp.Key, kvp.Value);
        }
        return word;
    }

    public string ReplaceWordMy(string word)
    {
        foreach (KeyValuePair<string, string> kvp in char_unicode_to_my_txt)
        {
            word = word.Replace(kvp.Key, kvp.Value);
        }
        foreach (KeyValuePair<string, string> kvp in char_unicode_my_correct)
        {
            word = word.Replace(kvp.Key, kvp.Value);
        }
        return word;
    }

    string tlg_Path = Application.streamingAssetsPath + "/tlg.txt";
    string my_Path = Application.streamingAssetsPath + "/my.txt";
    public void LoadTxt()
    {
        if (File.Exists(tlg_Path))
        {
            string[] lines = null;
            lines = File.ReadAllLines(tlg_Path);
            int c = lines.Length;
            for (int i = 0; i < c; i++)
            {
                string[] temp = lines[i].Split(',');
                if (!char_unicode_to_tlg_txt.ContainsKey(temp[0]))
                    char_unicode_to_tlg_txt.Add(temp[0], temp[1]);
            }
        }
        if (File.Exists(my_Path))
        {
            string[] lines = null;
            lines = File.ReadAllLines(my_Path);
            int c = lines.Length;
            for (int i = 0; i < c; i++)
            {
                string[] temp = lines[i].Split(',');
                if (!char_unicode_to_my_txt.ContainsKey(temp[0]))
                    char_unicode_to_my_txt.Add(temp[0], temp[1]);
            }
        }

    }

    Dictionary<string, string> char_unicode_to_tlg_txt = new Dictionary<string, string>();
    Dictionary<string, string> char_unicode_to_my_txt = new Dictionary<string, string>();
    Dictionary<string, string> char_unicode_to_si = new Dictionary<string, string>{
  { "bbhr",  "බ්භ්ර්" },
  { "bbhv",  "බ්භ්ව්" },
  { "bbhy",  "බ්භ්ය්" },
  { "cchr",  "ච්ඡ්ර්" },
  { "cchv",  "ච්ඡ්ව්" },
  { "cchy",  "ච්ඡ්ය්" },
  { "ddhr",  "ද්ධ්ර්" },
  { "ddhv",  "ද්ධ්ව්" },
  { "ddhy",  "ද්ධ්ය්" },
  { "ḍḍhr",  "ඩ්ඪ්ර්" },
  { "ḍḍhv",  "ඩ්ඪ්ව්" },
  { "ḍḍhy",  "ඩ්ඪ්ය්" },
  { "gghr",  "ග්ඝ්ර්" },
  { "gghv",  "ග්ඝ්ව්" },
  { "gghy",  "ග්ඝ්ය්" },
  { "ṅkhr",  "ඞ්ඛ්ර්" },
  { "ṅkhv",  "ඞ්ඛ්ව්" },
  { "ṅkhy",  "ඞ්ඛ්ය්" },
  { "ṅghr",  "ඞ්ඝ්ර්" },
  { "ṅghv",  "ඞ්ඝ්ව්" },
  { "ṅghy",  "ඞ්ඝ්ය්" },
  { "jjhr",  "ජ්ඣ්ර්" },
  { "jjhv",  "ජ්ඣ්ව්" },
  { "jjhy",  "ජ්ඣ්ය්" },
  { "kkhr",  "ක්ඛ්ර්" },
  { "kkhv",  "ක්ඛ්ව්" },
  { "kkhy",  "ක්ඛ්ය්" },
  { "ñchr",  "ඤ්ඡ්ර්" },
  { "ñchv",  "ඤ්ඡ්ව්" },
  { "ñchy",  "ඤ්ඡ්ය්" },
  { "ñjhr",  "ඤ්ඣ්ර්" },
  { "ñjhv",  "ඤ්ඣ්ව්" },
  { "ñjhy",  "ඤ්ඣ්ය්" },
  { "ṇṭhr",  "ණ්ඨ්ර්" },
  { "ṇṭhv",  "ණ්ඨ්ව්" },
  { "ṇṭhy",  "ණ්ඨ්ය්" },
  { "ṇḍhr",  "ණ්ඪ්ර්" },
  { "ṇḍhv",  "ණ්ඪ්ව්" },
  { "ṇḍhy",  "ණ්ඪ්ය්" },
  { "nthr",  "න්ථ්ර්" },
  { "nthv",  "න්ථ්ව්" },
  { "nthy",  "න්ථ්ය්" },
  { "ndhr",  "න්ධ්ර්" },
  { "ndhv",  "න්ධ්ව්" },
  { "ndhy",  "න්ධ්ය්" },
  { "pphr",  "ප්ඵ්ර්" },
  { "pphv",  "ප්ඵ්ව්" },
  { "pphy",  "ප්ඵ්ය්" },
  { "mphr",  "ම්ඵ්ර්" },
  { "mphv",  "ම්ඵ්ව්" },
  { "mphy",  "ම්ඵ්ය්" },
  { "mbhr",  "ම්භ්ර්" },
  { "mbhv",  "ම්භ්ව්" },
  { "mbhy",  "ම්භ්ය්" },
  { "tthr",  "ත්ථ්ර්" },
  { "tthv",  "ත්ථ්ව්" },
  { "tthy",  "ත්ථ්ය්" },
  { "ṭṭhr",  "ට්ඨ්ර්" },
  { "ṭṭhv",  "ට්ඨ්ව්" },
  { "ṭṭhy",  "ට්ඨ්ය්" },
  { "bbr",  "බ්බ්ර්" },
  { "bbv",  "බ්බ්ව්" },
  { "bby",  "බ්බ්ය්" },
  { "ccr",  "ච්ච්ර්" },
  { "ccv",  "ච්ච්ව්" },
  { "ccy",  "ච්ච්ය්" },
  { "ddr",  "ද්ද්ර්" },
  { "ddv",  "ද්ද්ව්" },
  { "ddy",  "ද්ද්ය්" },
  { "ḍḍr",  "ඩ්ඩ්ර්" },
  { "ḍḍv",  "ඩ්ඩ්ව්" },
  { "ḍḍy",  "ඩ්ඩ්ය්" },
  { "ggr",  "ග්ග්ර්" },
  { "ggv",  "ග්ග්ව්" },
  { "ggy",  "ග්ග්ය්" },
  { "jjr",  "ජ්ජ්ර්" },
  { "jjv",  "ජ්ජ්ව්" },
  { "jjy",  "ජ්ජ්ය්" },
  { "ṅkr",  "ඞ්ක්ර්" },
  { "ṅkv",  "ඞ්ක්ව්" },
  { "ṅky",  "ඞ්ක්ය්" },
  { "ṅgr",  "ඞ්ග්ර්" },
  { "ṅgv",  "ඞ්ග්ව්" },
  { "ṅgy",  "ඞ්ග්ය්" },
  { "kkr",  "ක්ක්ර්" },
  { "kkv",  "ක්ක්ව්" },
  { "kky",  "ක්ක්ය්" },
  { "ñcr",  "ඤ්ච්ර්" },
  { "ñcv",  "ඤ්ච්ව්" },
  { "ñcy",  "ඤ්ච්ය්" },
  { "ñjr",  "ඤ්ජ්ර්" },
  { "ñjv",  "ඤ්ජ්ව්" },
  { "ñjy",  "ඤ්ජ්ය්" },
  { "mmr",  "ම්ම්ර්" },
  { "mmv",  "ම්ම්ව්" },
  { "mmy",  "ම්ම්ය්" },
  { "nnr",  "න්න්ර්" },
  { "nnv",  "න්න්ව්" },
  { "nny",  "න්න්ය්" },
  { "ṇṭr",  "ණ්ට්ර්" },
  { "ṇṭv",  "ණ්ට්ව්" },
  { "ṇṭy",  "ණ්ට්ය්" },
  { "ṇḍr",  "ණ්ඩ්ර්" },
  { "ṇḍv",  "ණ්ඩ්ව්" },
  { "ṇḍy",  "ණ්ඩ්ය්" },
  { "ññr",  "ඤ්ඤ්ර්" },
  { "ññv",  "ඤ්ඤ්ව්" },
  { "ññy",  "ඤ්ඤ්ය්" },
  { "ṇṇr",  "ණ්ණ්ර්" },
  { "ṇṇv",  "ණ්ණ්ව්" },
  { "ṇṇy",  "ණ්ණ්ය්" },
  { "ppr",  "ප්ප්ර්" },
  { "ppv",  "ප්ප්ව්" },
  { "ppy",  "ප්ප්ය්" },
  { "ntr",  "න්ත්ර්" },
  { "ntv",  "න්ත්ව්" },
  { "nty",  "න්ත්ය්" },
  { "ndr",  "න්ද්ර්" },
  { "ndv",  "න්ද්ව්" },
  { "ndy",  "න්ද්ය්" },
  { "ttr",  "ත්ත්ර්" },
  { "ttv",  "ත්ත්ව්" },
  { "tty",  "ත්ත්ය්" },
  { "mpr",  "ම්ප්ර්" },
  { "mpv",  "ම්ප්ව්" },
  { "mpy",  "ම්ප්ය්" },
  { "mbr",  "ම්බ්ර්" },
  { "mbv",  "ම්බ්ව්" },
  { "mby",  "ම්බ්ය්" },
  { "ṭṭr",  "ට්ට්ර්" },
  { "ṭṭv",  "ට්ට්ව්" },
  { "ṭṭy",  "ට්ට්ය්" },
  { "llr",  "ල්ල්ර්" },
  { "llv",  "ල්ල්ව්" },
  { "lly",  "ල්ල්ය්" },
  { "ssr",  "ස්ස්ර්" },
  { "ssv",  "ස්ස්ව්" },
  { "ssy",  "ස්ස්ය්" },
  { "yyr",  "ය්ය්ර්" },
  { "yyv",  "ය්ය්ව්" },
  { "yyy",  "ය්ය්ය්" },
  { "bbh",  "බ්භ්" },
  { "cch",  "ච්ඡ්" },
  { "ddh",  "ද්ධ්" },
  { "ḍḍh",  "ඩ්ඪ්" },
  { "ggh",  "ග්ඝ්" },
  { "jjh",  "ජ්ඣ්" },
  { "kkh",  "ක්ඛ්" },
  { "mbh",  "ම්භ්" },
  { "mph",  "ම්ඵ්" },
  { "ñch",  "ඤ්ඡ්" },
  { "bhr",  "භ්ර්" },
  { "bhv",  "භ්ව්" },
  { "bhy",  "භ්ය්" },
  { "chr",  "ඡ්ර්" },
  { "chv",  "ඡ්ව්" },
  { "chy",  "ඡ්ය්" },
  { "dhr",  "ධ්ර්" },
  { "dhv",  "ධ්ව්" },
  { "dhy",  "ධ්ය්" },
  { "ḍhr",  "ඪ්ර්" },
  { "ḍhv",  "ඪ්ව්" },
  { "ḍhy",  "ඪ්ය්" },
  { "ghr",  "ඝ්ර්" },
  { "ghv",  "ඝ්ව්" },
  { "ghy",  "ඝ්ය්" },
  { "jhr",  "ඣ්ර්" },
  { "jhv",  "ඣ්ව්" },
  { "jhy",  "ඣ්ය්" },
  { "khr",  "ඛ්ර්" },
  { "khv",  "ඛ්ව්" },
  { "khy",  "ඛ්ය්" },
  { "phr",  "ඵ්ර්" },
  { "phv",  "ඵ්ව්" },
  { "phy",  "ඵ්ය්" },
  { "thr",  "ථ්ර්" },
  { "thv",  "ථ්ව්" },
  { "thy",  "ථ්ය්" },
  { "ṭhr",  "ඨ්ර්" },
  { "ṭhv",  "ඨ්ව්" },
  { "ṭhy",  "ඨ්ය්" },
  { "ndh",  "න්ධ්" },
  { "ṇḍh",  "ණ්ඪ්" },
  { "ṅgh",  "ඞ්ඝ්" },
  { "ñjh",  "ඤ්ඣ්" },
  { "ṅkh",  "ඞ්ඛ්" },
  { "nth",  "න්ථ්" },
  { "ṇṭh",  "ණ්ඨ්" },
  { "pph",  "ප්ඵ්" },
  { "tth",  "ත්ථ්" },
  { "ṭṭh",  "ට්ඨ්" },
  { "bb",  "බ්බ්" },
  { "bh",  "භ්" },
  { "cc",  "ච්ච්" },
  { "ch",  "ඡ්" },
  { "dd",  "ද්ද්" },
  { "ḍḍ",  "ඩ්ඩ්" },
  { "dh",  "ධ්" },
  { "ḍh",  "ඪ්" },
  { "gg",  "ග්ග්" },
  { "gh",  "ඝ්" },
  { "jh",  "ඣ්" },
  { "jj",  "ජ්ජ්" },
  { "kh",  "ඛ්" },
  { "kk",  "ක්ක්" },
  { "ll",  "ල්ල්" },
  { "mb",  "ම්බ්" },
  { "mm",  "ම්ම්" },
  { "mp",  "ම්ප්" },
  { "ñc",  "ඤ්ච්" },
  { "nd",  "න්ද්" },
  { "ṇḍ",  "ණ්ඩ්" },
  { "ṅg",  "ඞ්ග්" },
  { "ñj",  "ඤ්ජ්" },
  { "ṅk",  "ඞ්ක්" },
  { "nn",  "න්න්" },
  { "ññ",  "ඤ්ඤ්" },
  { "ṇṇ",  "ණ්ණ්" },
  { "nt",  "න්ත්" },
  { "br",  "බ්ර්" },
  { "bv",  "බ්ව්" },
  { "by",  "බ්ය්" },
  { "cr",  "ච්ර්" },
  { "cv",  "ච්ව්" },
  { "cy",  "ච්ය්" },
  { "dr",  "ද්ර්" },
  { "dv",  "ද්ව්" },
  { "dy",  "ද්ය්" },
  { "ḍr",  "ඩ්ර්" },
  { "ḍv",  "ඩ්ව්" },
  { "ḍy",  "ඩ්ය්" },
  { "gr",  "ග්ර්" },
  { "gv",  "ග්ව්" },
  { "gy",  "ග්ය්" },
  { "jr",  "ජ්ර්" },
  { "jv",  "ජ්ව්" },
  { "jy",  "ජ්ය්" },
  { "kr",  "ක්ර්" },
  { "kv",  "ක්ව්" },
  { "ky",  "ක්ය්" },
  { "pr",  "ප්ර්" },
  { "pv",  "ප්ව්" },
  { "py",  "ප්ය්" },
  { "tr",  "ත්ර්" },
  { "tv",  "ත්ව්" },
  { "ty",  "ත්ය්" },
  { "ṭr",  "ට්ර්" },
  { "ṭv",  "ට්ව්" },
  { "ṭy",  "ට්ය්" },
  { "ñh",  "ඤ්හ්" },
  { "ṇh",  "ණ්හ්" },
  { "nh",  "න්හ්" },
  { "mh",  "ම්හ්" },
  { "yh",  "ය්හ්" },
  { "ly",  "ල්ය්" },
  { "lh",  "ල්හ්" },
  { "vh",  "ව්හ්" },
  { "sm",  "ස්ම්" },
  { "sv",  "ස්ව්" },
  { "hm",  "හ්ම්" },
  { "hv",  "හ්ව්" },
  { "ḷh",  "ළ්හ්" },
  { "ṇṭ",  "ණ්ට්" },
  { "ph",  "ඵ්" },
  { "pp",  "ප්ප්" },
  { "ss",  "ස්ස්" },
  { "th",  "ථ්" },
  { "ṭh",  "ඨ්" },
  { "tt",  "ත්ත්" },
  { "ṭṭ",  "ට්ට්" },
  { "yy",  "ය්ය්" },
  { "b",  "බ්" },
  { "c",  "ච්" },
  { "d",  "ද්" },
  { "ḍ",  "ඩ්" },
  { "g",  "ග්" },
  { "h",  "හ්" },
  { "j",  "ජ්" },
  { "k",  "ක්" },
  { "l",  "ල්" },
  { "ḷ",  "ළ්" },
  { "m",  "ම්" },
  { "n",  "න්" },
  { "ṅ",  "ඞ්" },
  { "ñ",  "ඤ්" },
  { "ṇ",  "ණ්" },
  { "p",  "ප්" },
  { "r",  "‍ර්" },
  { "s",  "ස්" },
  { "t",  "ත්" },
  { "ṭ",  "ට්" },
  { "v",  "ව්" },
  { "y",  "‍ය්" },
  { "්iṃ",  "ිං" },
  { "්uṃ",  "ුං" },
  { "්aṃ",  "ං" },
  { "්ā",  "ා" },
  { "්i",  "ි" },
  { "්ī",  "ී" },
  { "්u",  "ු" },
  { "්ū",  "ූ" },
  { "්e",  "ෙ" },
  { "්ē",  "ේ" },
  { "්o",  "ො" },
  { "්ō",  "ෝ" },
  { "්",  "්" },
  { "aṃ",  "අං" },
  { "iṃ",  "ඉං" },
  { "uṃ",  "උං" },
  { "්a",  "" },
  { "a",  "අ" },
  { "ā",  "ආ" },
  { "i",  "ඉ" },
  { "ī",  "ඊ" },
  { "u",  "උ" },
  { "ū",  "ඌ" },
  { "e",  "එ" },
  { "o",  "ඔ" },
};
    Dictionary<string, string> char_unicode_to_tlg = new Dictionary<string, string> {
{ "ththru", "ధ్ధృ" },
{ "dhdhru" , "ధ్ధృ" },
{ "phphru" , "ఫ్ఫృ" },
{ "bhbhru" , "భ్భృ" },
{ "shshru" , "ష్షృ" },
{ "ththrū" , "ధ్ధౄ" },
{ "dhdhrū" , "ధ్ధౄ" },
{ "phphrū" , "ఫ్ఫౄ" },
{ "bhbhrū" , "భ్భౄ" },
{ "shshrū" , "ష్షౄ" },
{ "ththai" , "ధ్ధై" },
{ "dhdhai" , "ధ్ధై" },
{ "phphai" , "ఫ్ఫై" },
{ "bhbhai" , "భ్భై" },
{ "shshai" , "ష్షై" },
{ "ththao" , "ధ్ధౌ" },
{ "dhdhao" , "ధ్ధౌ" },
{ "phphao" , "ఫ్ఫౌ" },
{ "bhbhao" , "భ్భౌ" },
{ "shshao" , "ష్షౌ" },
{ "ththaṃ" , "ధ్ధం" },
{ "dhdhaṃ" , "ధ్ధం" },
{ "phphaṃ" , "ఫ్ఫం" },
{ "bhbhaṃ" , "భ్భం" },
{ "shshaṃ" , "ష్షం" },
{ "ththiṃ" , "ధ్ధిం" },
{ "dhdhiṃ" , "ధ్ధిం" },
{ "phphiṃ" , "ఫ్ఫిం" },
{ "bhbhiṃ" , "భ్భిం" },
{ "shshiṃ" , "ష్షిం" },
{ "ththuṃ" , "ధ్ధుం" },
{ "dhdhuṃ" , "ధ్ధుం" },
{ "phphuṃ" , "ఫ్ఫుం" },
{ "bhbhuṃ" , "భ్భుం" },
{ "shshuṃ" , "ష్షుం" },
{ "ththra" , "ధ్ధ్ర" },
{ "dhdhra" , "ధ్ధ్ర" },
{ "phphra" , "ఫ్ఫ్ర" },
{ "bhbhra" , "భ్భ్ర" },
{ "shshra" , "ష్ష్ర" },
{ "ththya" , "ధ్ధ్య" },
{ "dhdhya" , "ధ్ధ్య" },
{ "phphya" , "ఫ్ఫ్య" },
{ "bhbhya" , "భ్భ్య" },
{ "shshya" , "ష్ష్య" },
{ "ththva" , "ధ్ధ్వ" },
{ "dhdhva" , "ధ్ధ్వ" },
{ "phphva" , "ఫ్ఫ్వ" },
{ "bhbhva" , "భ్భ్వ" },
{ "shshva" , "ష్ష్వ" },
{ "ththma" , "ధ్ధ్మ" },
{ "dhdhma" , "ధ్ధ్మ" },
{ "phphma" , "ఫ్ఫ్మ" },
{ "bhbhma" , "భ్భ్మ" },
{ "shshma" , "ష్ష్మ" },
{ "ththa" , "ధ్ధ" },
{ "dhdha" , "ధ్ధ" },
{ "phpha" , "ఫ్ఫ" },
{ "bhbha" , "భ్భ" },
{ "shsha" , "ష్ష" },
{ "ththā" , "ధ్ధా" },
{ "dhdhā" , "ధ్ధా" },
{ "phphā" , "ఫ్ఫా" },
{ "bhbhā" , "భ్భా" },
{ "shshā" , "ష్షా" },
{ "ththi" , "ధ్ధి" },
{ "dhdhi" , "ధ్ధి" },
{ "phphi" , "ఫ్ఫి" },
{ "bhbhi" , "భ్భి" },
{ "shshi" , "ష్షి" },
{ "ththī" , "ధ్ధీ" },
{ "dhdhī" , "ధ్ధీ" },
{ "phphī" , "ఫ్ఫీ" },
{ "bhbhī" , "భ్భీ" },
{ "shshī" , "ష్షీ" },
{ "ththu" , "ధ్ధు" },
{ "dhdhu" , "ధ్ధు" },
{ "phphu" , "ఫ్ఫు" },
{ "bhbhu" , "భ్భు" },
{ "shshu" , "ష్షు" },
{ "ththū" , "ధ్ధూ" },
{ "dhdhū" , "ధ్ధూ" },
{ "phphū" , "ఫ్ఫూ" },
{ "bhbhū" , "భ్భూ" },
{ "shshū" , "ష్షూ" },
{ "kkhru" , "క్ఖృ" },
{ "gghru" , "ఘ్ఘృ" },
{ "cchru" , "ఛ్ఛృ" },
{ "jjhru" , "ఝ్ఝృ" },
{ "ñchru" , "ఞ్ఛృ" },
{ "ñjhru" , "ఞ్ఝృ" },
{ "ṭṭhru" , "ఠ్ఠృ" },
{ "ḍḍhru" , "ఢ్ఢృ" },
{ "ṇṭhru" , "ణ్ఠృ" },
{ "ṇḍhru" , "ణ్ఢృ" },
{ "tthru" , "త్థృ" },
{ "nthru" , "న్థృ" },
{ "ddhru" , "ద్ధృ" },
{ "ndhru" , "న్ధృ" },
{ "pphru" , "ప్ఫృ" },
{ "mphru" , "మ్ఫృ" },
{ "bbhru" , "బ్భృ" },
{ "mbhru" , "మ్భృ" },
{ "kkhrū" , "క్ఖౄ" },
{ "gghrū" , "ఘ్ఘౄ" },
{ "cchrū" , "ఛ్ఛౄ" },
{ "jjhrū" , "ఝ్ఝౄ" },
{ "ñchrū" , "ఞ్ఛౄ" },
{ "ñjhrū" , "ఞ్ఝౄ" },
{ "ṭṭhrū" , "ఠ్ఠౄ" },
{ "ḍḍhrū" , "ఢ్ఢౄ" },
{ "ṇṭhrū" , "ణ్ఠౄ" },
{ "ṇḍhrū" , "ణ్ఢౄ" },
{ "tthrū" , "త్థౄ" },
{ "nthrū" , "న్థౄ" },
{ "ddhrū" , "ద్ధౄ" },
{ "ndhrū" , "న్ధౄ" },
{ "pphrū" , "ప్ఫౄ" },
{ "mphrū" , "మ్ఫౄ" },
{ "bbhrū" , "బ్భౄ" },
{ "mbhrū" , "మ్భౄ" },
{ "ththe" , "ధ్ధె" },
{ "dhdhe" , "ధ్ధె" },
{ "phphe" , "ఫ్ఫె" },
{ "bhbhe" , "భ్భె" },
{ "shshe" , "ష్షె" },
{ "ththē" , "ధ్ధే" },
{ "dhdhē" , "ధ్ధే" },
{ "phphē" , "ఫ్ఫే" },
{ "bhbhē" , "భ్భే" },
{ "shshē" , "ష్షే" },
{ "kkhai" , "క్ఖై" },
{ "gghai" , "ఘ్ఘై" },
{ "cchai" , "ఛ్ఛై" },
{ "jjhai" , "ఝ్ఝై" },
{ "ñchai" , "ఞ్ఛై" },
{ "ñjhai" , "ఞ్ఝై" },
{ "ṭṭhai" , "ఠ్ఠై" },
{ "ḍḍhai" , "ఢ్ఢై" },
{ "ṇṭhai" , "ణ్ఠై" },
{ "ṇḍhai" , "ణ్ఢై" },
{ "tthai" , "త్థై" },
{ "nthai" , "న్థై" },
{ "ddhai" , "ద్ధై" },
{ "ndhai" , "న్ధై" },
{ "pphai" , "ప్ఫై" },
{ "mphai" , "మ్ఫై" },
{ "bbhai" , "బ్భై" },
{ "mbhai" , "మ్భై" },
{ "ththo" , "ధ్ధొ" },
{ "dhdho" , "ధ్ధొ" },
{ "phpho" , "ఫ్ఫొ" },
{ "bhbho" , "భ్భొ" },
{ "shsho" , "ష్షొ" },
{ "ththō" , "ధ్ధో" },
{ "dhdhō" , "ధ్ధో" },
{ "phphō" , "ఫ్ఫో" },
{ "bhbhō" , "భ్భో" },
{ "shshō" , "ష్షో" },
{ "kkhao" , "క్ఖౌ" },
{ "gghao" , "ఘ్ఘౌ" },
{ "cchao" , "ఛ్ఛౌ" },
{ "jjhao" , "ఝ్ఝౌ" },
{ "ñchao" , "ఞ్ఛౌ" },
{ "ñjhao" , "ఞ్ఝౌ" },
{ "ṭṭhao" , "ఠ్ఠౌ" },
{ "ḍḍhao" , "ఢ్ఢౌ" },
{ "ṇṭhao" , "ణ్ఠౌ" },
{ "ṇḍhao" , "ణ్ఢౌ" },
{ "tthao" , "త్థౌ" },
{ "nthao" , "న్థౌ" },
{ "ddhao" , "ద్ధౌ" },
{ "ndhao" , "న్ధౌ" },
{ "pphao" , "ప్ఫౌ" },
{ "mphao" , "మ్ఫౌ" },
{ "bbhao" , "బ్భౌ" },
{ "mbhao" , "మ్భౌ" },
{ "kkhaṃ" , "క్ఖం" },
{ "gghaṃ" , "ఘ్ఘం" },
{ "cchaṃ" , "ఛ్ఛం" },
{ "jjhaṃ" , "ఝ్ఝం" },
{ "ñchaṃ" , "ఞ్ఛం" },
{ "ñjhaṃ" , "ఞ్ఝం" },
{ "ṭṭhaṃ" , "ఠ్ఠం" },
{ "ḍḍhaṃ" , "ఢ్ఢం" },
{ "ṇṭhaṃ" , "ణ్ఠం" },
{ "ṇḍhaṃ" , "ణ్ఢం" },
{ "tthaṃ" , "త్థం" },
{ "nthaṃ" , "న్థం" },
{ "ddhaṃ" , "ద్ధం" },
{ "ndhaṃ" , "న్ధం" },
{ "pphaṃ" , "ప్ఫం" },
{ "mphaṃ" , "మ్ఫం" },
{ "bbhaṃ" , "బ్భం" },
{ "mbhaṃ" , "మ్భం" },
{ "kkhiṃ" , "క్ఖిం" },
{ "gghiṃ" , "ఘ్ఘిం" },
{ "cchiṃ" , "ఛ్ఛిం" },
{ "jjhiṃ" , "ఝ్ఝిం" },
{ "ñchiṃ" , "ఞ్ఛిం" },
{ "ñjhiṃ" , "ఞ్ఝిం" },
{ "ṭṭhiṃ" , "ఠ్ఠిం" },
{ "ḍḍhiṃ" , "ఢ్ఢిం" },
{ "ṇṭhiṃ" , "ణ్ఠిం" },
{ "ṇḍhiṃ" , "ణ్ఢిం" },
{ "tthiṃ" , "త్థిం" },
{ "nthiṃ" , "న్థిం" },
{ "ddhiṃ" , "ద్ధిం" },
{ "ndhiṃ" , "న్ధిం" },
{ "pphiṃ" , "ప్ఫిం" },
{ "mphiṃ" , "మ్ఫిం" },
{ "bbhiṃ" , "బ్భిం" },
{ "mbhiṃ" , "మ్భిం" },
{ "kkhuṃ" , "క్ఖుం" },
{ "gghuṃ" , "ఘ్ఘుం" },
{ "cchuṃ" , "ఛ్ఛుం" },
{ "jjhuṃ" , "ఝ్ఝుం" },
{ "ñchuṃ" , "ఞ్ఛుం" },
{ "ñjhuṃ" , "ఞ్ఝుం" },
{ "ṭṭhuṃ" , "ఠ్ఠుం" },
{ "ḍḍhuṃ" , "ఢ్ఢుం" },
{ "ṇṭhuṃ" , "ణ్ఠుం" },
{ "ṇḍhuṃ" , "ణ్ఢుం" },
{ "tthuṃ" , "త్థుం" },
{ "nthuṃ" , "న్థుం" },
{ "ddhuṃ" , "ద్ధుం" },
{ "ndhuṃ" , "న్ధుం" },
{ "pphuṃ" , "ప్ఫుం" },
{ "mphuṃ" , "మ్ఫుం" },
{ "bbhuṃ" , "బ్భుం" },
{ "mbhuṃ" , "మ్భుం" },
{ "kkhra" , "క్ఖ్ర" },
{ "gghra" , "ఘ్ఘ్ర" },
{ "cchra" , "ఛ్ఛ్ర" },
{ "jjhra" , "ఝ్ఝ్ర" },
{ "ñchra" , "ఞ్ఛ్ర" },
{ "ñjhra" , "ఞ్ఝ్ర" },
{ "ṭṭhra" , "ఠ్ఠ్ర" },
{ "ḍḍhra" , "ఢ్ఢ్ర" },
{ "ṇṭhra" , "ణ్ఠ్ర" },
{ "ṇḍhra" , "ణ్ఢ్ర" },
{ "tthra" , "త్థ్ర" },
{ "nthra" , "న్థ్ర" },
{ "ddhra" , "ద్ధ్ర" },
{ "ndhra" , "న్ధ్ర" },
{ "pphra" , "ప్ఫ్ర" },
{ "mphra" , "మ్ఫ్ర" },
{ "bbhra" , "బ్భ్ర" },
{ "mbhra" , "మ్భ్ర" },
{ "kkhya" , "క్ఖ్య" },
{ "gghya" , "ఘ్ఘ్య" },
{ "cchya" , "ఛ్ఛ్య" },
{ "jjhya" , "ఝ్ఝ్య" },
{ "ñchya" , "ఞ్ఛ్య" },
{ "ñjhya" , "ఞ్ఝ్య" },
{ "ṭṭhya" , "ఠ్ఠ్య" },
{ "ḍḍhya" , "ఢ్ఢ్య" },
{ "ṇṭhya" , "ణ్ఠ్య" },
{ "ṇḍhya" , "ణ్ఢ్య" },
{ "tthya" , "త్థ్య" },
{ "nthya" , "న్థ్య" },
{ "ddhya" , "ద్ధ్య" },
{ "ndhya" , "న్ధ్య" },
{ "pphya" , "ప్ఫ్య" },
{ "mphya" , "మ్ఫ్య" },
{ "bbhya" , "బ్భ్య" },
{ "mbhya" , "మ్భ్య" },
{ "kkhva" , "క్ఖ్వ" },
{ "gghva" , "ఘ్ఘ్వ" },
{ "cchva" , "ఛ్ఛ్వ" },
{ "jjhva" , "ఝ్ఝ్వ" },
{ "ñchva" , "ఞ్ఛ్వ" },
{ "ñjhva" , "ఞ్ఝ్వ" },
{ "ṭṭhva" , "ఠ్ఠ్వ" },
{ "ḍḍhva" , "ఢ్ఢ్వ" },
{ "ṇṭhva" , "ణ్ఠ్వ" },
{ "ṇḍhva" , "ణ్ఢ్వ" },
{ "tthva" , "త్థ్వ" },
{ "nthva" , "న్థ్వ" },
{ "ddhva" , "ద్ధ్వ" },
{ "ndhva" , "న్ధ్వ" },
{ "pphva" , "ప్ఫ్వ" },
{ "mphva" , "మ్ఫ్వ" },
{ "bbhva" , "బ్భ్వ" },
{ "mbhva" , "మ్భ్వ" },
{ "kkhma" , "క్ఖ్మ" },
{ "gghma" , "ఘ్ఘ్మ" },
{ "cchma" , "ఛ్ఛ్మ" },
{ "jjhma" , "ఝ్ఝ్మ" },
{ "ñchma" , "ఞ్ఛ్మ" },
{ "ñjhma" , "ఞ్ఝ్మ" },
{ "ṭṭhma" , "ఠ్ఠ్మ" },
{ "ḍḍhma" , "ఢ్ఢ్మ" },
{ "ṇṭhma" , "ణ్ఠ్మ" },
{ "ṇḍhma" , "ణ్ఢ్మ" },
{ "tthma" , "త్థ్మ" },
{ "nthma" , "న్థ్మ" },
{ "ddhma" , "ద్ధ్మ" },
{ "ndhma" , "న్ధ్మ" },
{ "pphma" , "ప్ఫ్మ" },
{ "mphma" , "మ్ఫ్మ" },
{ "bbhma" , "బ్భ్మ" },
{ "mbhma" , "మ్భ్మ" },
{ "thth" , "ధ్ధ్" },
{ "dhdh" , "ధ్ధ్" },
{ "phph" , "ఫ్ఫ్" },
{ "bhbh" , "భ్భ్" },
{ "shsh" , "ష్ష్" },
{ "kkha" , "క్ఖ" },
{ "ggha" , "ఘ్ఘ" },
{ "ccha" , "ఛ్ఛ" },
{ "jjha" , "ఝ్ఝ" },
{ "ñcha" , "ఞ్ఛ" },
{ "ñjha" , "ఞ్ఝ" },
{ "ṭṭha" , "ఠ్ఠ" },
{ "ḍḍha" , "ఢ్ఢ" },
{ "ṇṭha" , "ణ్ఠ" },
{ "ṇḍha" , "ణ్ఢ" },
{ "ttha" , "త్థ" },
{ "ntha" , "న్థ" },
{ "ddha" , "ద్ధ" },
{ "ndha" , "న్ధ" },
{ "ppha" , "ప్ఫ" },
{ "mpha" , "మ్ఫ" },
{ "bbha" , "బ్భ" },
{ "mbha" , "మ్భ" },
{ "kkhā" , "క్ఖా" },
{ "gghā" , "ఘ్ఘా" },
{ "cchā" , "ఛ్ఛా" },
{ "jjhā" , "ఝ్ఝా" },
{ "ñchā" , "ఞ్ఛా" },
{ "ñjhā" , "ఞ్ఝా" },
{ "ṭṭhā" , "ఠ్ఠా" },
{ "ḍḍhā" , "ఢ్ఢా" },
{ "ṇṭhā" , "ణ్ఠా" },
{ "ṇḍhā" , "ణ్ఢా" },
{ "tthā" , "త్థా" },
{ "nthā" , "న్థా" },
{ "ddhā" , "ద్ధా" },
{ "ndhā" , "న్ధా" },
{ "pphā" , "ప్ఫా" },
{ "mphā" , "మ్ఫా" },
{ "bbhā" , "బ్భా" },
{ "mbhā" , "మ్భా" },
{ "kkhi" , "క్ఖి" },
{ "gghi" , "ఘ్ఘి" },
{ "cchi" , "ఛ్ఛి" },
{ "jjhi" , "ఝ్ఝి" },
{ "ñchi" , "ఞ్ఛి" },
{ "ñjhi" , "ఞ్ఝి" },
{ "ṭṭhi" , "ఠ్ఠి" },
{ "ḍḍhi" , "ఢ్ఢి" },
{ "ṇṭhi" , "ణ్ఠి" },
{ "ṇḍhi" , "ణ్ఢి" },
{ "tthi" , "త్థి" },
{ "nthi" , "న్థి" },
{ "ddhi" , "ద్ధి" },
{ "ndhi" , "న్ధి" },
{ "pphi" , "ప్ఫి" },
{ "mphi" , "మ్ఫి" },
{ "bbhi" , "బ్భి" },
{ "mbhi" , "మ్భి" },
{ "kkhī" , "క్ఖీ" },
{ "gghī" , "ఘ్ఘీ" },
{ "cchī" , "ఛ్ఛీ" },
{ "jjhī" , "ఝ్ఝీ" },
{ "ñchī" , "ఞ్ఛీ" },
{ "ñjhī" , "ఞ్ఝీ" },
{ "ṭṭhī" , "ఠ్ఠీ" },
{ "ḍḍhī" , "ఢ్ఢీ" },
{ "ṇṭhī" , "ణ్ఠీ" },
{ "ṇḍhī" , "ణ్ఢీ" },
{ "tthī" , "త్థీ" },
{ "nthī" , "న్థీ" },
{ "ddhī" , "ద్ధీ" },
{ "ndhī" , "న్ధీ" },
{ "pphī" , "ప్ఫీ" },
{ "mphī" , "మ్ఫీ" },
{ "bbhī" , "బ్భీ" },
{ "mbhī" , "మ్భీ" },
{ "kkhu" , "క్ఖు" },
{ "gghu" , "ఘ్ఘు" },
{ "cchu" , "ఛ్ఛు" },
{ "jjhu" , "ఝ్ఝు" },
{ "ñchu" , "ఞ్ఛు" },
{ "ñjhu" , "ఞ్ఝు" },
{ "ṭṭhu" , "ఠ్ఠు" },
{ "ḍḍhu" , "ఢ్ఢు" },
{ "ṇṭhu" , "ణ్ఠు" },
{ "ṇḍhu" , "ణ్ఢు" },
{ "tthu" , "త్థు" },
{ "nthu" , "న్థు" },
{ "ddhu" , "ద్ధు" },
{ "ndhu" , "న్ధు" },
{ "pphu" , "ప్ఫు" },
{ "mphu" , "మ్ఫు" },
{ "bbhu" , "బ్భు" },
{ "mbhu" , "మ్భు" },
{ "kkhū" , "క్ఖూ" },
{ "gghū" , "ఘ్ఘూ" },
{ "cchū" , "ఛ్ఛూ" },
{ "jjhū" , "ఝ్ఝూ" },
{ "ñchū" , "ఞ్ఛూ" },
{ "ñjhū" , "ఞ్ఝూ" },
{ "ṭṭhū" , "ఠ్ఠూ" },
{ "ḍḍhū" , "ఢ్ఢూ" },
{ "ṇṭhū" , "ణ్ఠూ" },
{ "ṇḍhū" , "ణ్ఢూ" },
{ "tthū" , "త్థూ" },
{ "nthū" , "న్థూ" },
{ "ddhū" , "ద్ధూ" },
{ "ndhū" , "న్ధూ" },
{ "pphū" , "ప్ఫూ" },
{ "mphū" , "మ్ఫూ" },
{ "bbhū" , "బ్భూ" },
{ "mbhū" , "మ్భూ" },
{ "kkru" , "క్కృ" },
{ "kmru" , "క్మృ" },
{ "khru" , "ఖృ" },
{ "ggru" , "గ్గృ" },
{ "ghru" , "ఘృ" },
{ "ccru" , "చ్చృ" },
{ "chru" , "ఛృ" },
{ "jjru" , "జ్జృ" },
{ "jhru" , "ఝృ" },
{ "jñru" , "జ్ఞృ" },
{ "ññru" , "ఞ్ఞృ" },
{ "ñhru" , "ఞ్హృ" },
{ "ñcru" , "ఞ్చృ" },
{ "ñjru" , "ఞ్జృ" },
{ "ṭṭru" , "ట్టృ" },
{ "ṭhru" , "ఠృ" },
{ "ḍḍru" , "డ్డృ" },
{ "ḍhru" , "ఢృ" },
{ "ṇṇru" , "ణ్ణృ" },
{ "ṇhru" , "ణ్హృ" },
{ "ṇṭru" , "ణ్టృ" },
{ "nṭru" , "న్టృ" },
{ "ṇḍru" , "ణ్డృ" },
{ "ttru" , "త్తృ" },
{ "ntru" , "న్తృ" },
{ "thru" , "థృ" },
{ "ddru" , "ద్దృ" },
{ "ndru" , "న్దృ" },
{ "dhru" , "ధృ" },
{ "nnru" , "న్నృ" },
{ "nhru" , "న్హృ" },
{ "ppru" , "ప్పృ" },
{ "mpru" , "మ్పృ" },
{ "phru" , "ఫృ" },
{ "bbru" , "బ్బృ" },
{ "mbru" , "మ్బృ" },
{ "bhru" , "భృ" },
{ "mmru" , "మ్మృ" },
{ "mhru" , "మ్హృ" },
{ "yyru" , "య్యృ" },
{ "yhru" , "య్హృ" },
{ "rrru" , "ర్రృ" },
{ "ṛṛru" , "ఱ్ఱృ" },
{ "llru" , "ల్లృ" },
{ "lhru" , "ల్హృ" },
{ "ḷḷru" , "ళ్ళృ" },
{ "ḷhru" , "ళ్హృ" },
{ "vvru" , "వ్వృ" },
{ "vhru" , "వ్హృ" },
{ "śśru" , "శ్శృ" },
{ "shru" , "షృ" },
{ "ssru" , "స్సృ" },
{ "smru" , "స్మృ" },
{ "hhru" , "హ్హృ" },
{ "hmru" , "హ్మృ" },
{ "kkrū" , "క్కౄ" },
{ "kmrū" , "క్మౄ" },
{ "khrū" , "ఖౄ" },
{ "ggrū" , "గ్గౄ" },
{ "ghrū" , "ఘౄ" },
{ "ccrū" , "చ్చౄ" },
{ "chrū" , "ఛౄ" },
{ "jjrū" , "జ్జౄ" },
{ "jhrū" , "ఝౄ" },
{ "jñrū" , "జ్ఞౄ" },
{ "ññrū" , "ఞ్ఞౄ" },
{ "ñhrū" , "ఞ్హౄ" },
{ "ñcrū" , "ఞ్చౄ" },
{ "ñjrū" , "ఞ్జౄ" },
{ "ṭṭrū" , "ట్టౄ" },
{ "ṭhrū" , "ఠౄ" },
{ "ḍḍrū" , "డ్డౄ" },
{ "ḍhrū" , "ఢౄ" },
{ "ṇṇrū" , "ణ్ణౄ" },
{ "ṇhrū" , "ణ్హౄ" },
{ "ṇṭrū" , "ణ్టౄ" },
{ "nṭrū" , "న్టౄ" },
{ "ṇḍrū" , "ణ్డౄ" },
{ "ttrū" , "త్తౄ" },
{ "ntrū" , "న్తౄ" },
{ "thrū" , "థౄ" },
{ "ddrū" , "ద్దౄ" },
{ "ndrū" , "న్దౄ" },
{ "dhrū" , "ధౄ" },
{ "nnrū" , "న్నౄ" },
{ "nhrū" , "న్హౄ" },
{ "pprū" , "ప్పౄ" },
{ "mprū" , "మ్పౄ" },
{ "phrū" , "ఫౄ" },
{ "bbrū" , "బ్బౄ" },
{ "mbrū" , "మ్బౄ" },
{ "bhrū" , "భౄ" },
{ "mmrū" , "మ్మౄ" },
{ "mhrū" , "మ్హౄ" },
{ "yyrū" , "య్యౄ" },
{ "yhrū" , "య్హౄ" },
{ "rrrū" , "ర్రౄ" },
{ "ṛṛrū" , "ఱ్ఱౄ" },
{ "llrū" , "ల్లౄ" },
{ "lhrū" , "ల్హౄ" },
{ "ḷḷrū" , "ళ్ళౄ" },
{ "ḷhrū" , "ళ్హౄ" },
{ "vvrū" , "వ్వౄ" },
{ "vhrū" , "వ్హౄ" },
{ "śśrū" , "శ్శౄ" },
{ "shrū" , "షౄ" },
{ "ssrū" , "స్సౄ" },
{ "smrū" , "స్మౄ" },
{ "hhrū" , "హ్హౄ" },
{ "hmrū" , "హ్మౄ" },
{ "kkhe" , "క్ఖె" },
{ "gghe" , "ఘ్ఘె" },
{ "cche" , "ఛ్ఛె" },
{ "jjhe" , "ఝ్ఝె" },
{ "ñche" , "ఞ్ఛె" },
{ "ñjhe" , "ఞ్ఝె" },
{ "ṭṭhe" , "ఠ్ఠె" },
{ "ḍḍhe" , "ఢ్ఢె" },
{ "ṇṭhe" , "ణ్ఠె" },
{ "ṇḍhe" , "ణ్ఢె" },
{ "tthe" , "త్థె" },
{ "nthe" , "న్థె" },
{ "ddhe" , "ద్ధె" },
{ "ndhe" , "న్ధె" },
{ "pphe" , "ప్ఫె" },
{ "mphe" , "మ్ఫె" },
{ "bbhe" , "బ్భె" },
{ "mbhe" , "మ్భె" },
{ "kkhē" , "క్ఖే" },
{ "gghē" , "ఘ్ఘే" },
{ "cchē" , "ఛ్ఛే" },
{ "jjhē" , "ఝ్ఝే" },
{ "ñchē" , "ఞ్ఛే" },
{ "ñjhē" , "ఞ్ఝే" },
{ "ṭṭhē" , "ఠ్ఠే" },
{ "ḍḍhē" , "ఢ్ఢే" },
{ "ṇṭhē" , "ణ్ఠే" },
{ "ṇḍhē" , "ణ్ఢే" },
{ "tthē" , "త్థే" },
{ "nthē" , "న్థే" },
{ "ddhē" , "ద్ధే" },
{ "ndhē" , "న్ధే" },
{ "pphē" , "ప్ఫే" },
{ "mphē" , "మ్ఫే" },
{ "bbhē" , "బ్భే" },
{ "mbhē" , "మ్భే" },
{ "kkai" , "క్కై" },
{ "kmai" , "క్మై" },
{ "khai" , "ఖై" },
{ "ggai" , "గ్గై" },
{ "ghai" , "ఘై" },
{ "ccai" , "చ్చై" },
{ "chai" , "ఛై" },
{ "jjai" , "జ్జై" },
{ "jhai" , "ఝై" },
{ "jñai" , "జ్ఞై" },
{ "ññai" , "ఞ్ఞై" },
{ "ñhai" , "ఞ్హై" },
{ "ñcai" , "ఞ్చై" },
{ "ñjai" , "ఞ్జై" },
{ "ṭṭai" , "ట్టై" },
{ "ṭhai" , "ఠై" },
{ "ḍḍai" , "డ్డై" },
{ "ḍhai" , "ఢై" },
{ "ṇṇai" , "ణ్ణై" },
{ "ṇhai" , "ణ్హై" },
{ "ṇṭai" , "ణ్టై" },
{ "nṭai" , "న్టై" },
{ "ṇḍai" , "ణ్డై" },
{ "ttai" , "త్తై" },
{ "ntai" , "న్తై" },
{ "thai" , "థై" },
{ "ddai" , "ద్దై" },
{ "ndai" , "న్దై" },
{ "dhai" , "ధై" },
{ "nnai" , "న్నై" },
{ "nhai" , "న్హై" },
{ "ppai" , "ప్పై" },
{ "mpai" , "మ్పై" },
{ "phai" , "ఫై" },
{ "bbai" , "బ్బై" },
{ "mbai" , "మ్బై" },
{ "bhai" , "భై" },
{ "mmai" , "మ్మై" },
{ "mhai" , "మ్హై" },
{ "yyai" , "య్యై" },
{ "yhai" , "య్హై" },
{ "rrai" , "ర్రై" },
{ "ṛṛai" , "ఱ్ఱై" },
{ "llai" , "ల్లై" },
{ "lhai" , "ల్హై" },
{ "ḷḷai" , "ళ్ళై" },
{ "ḷhai" , "ళ్హై" },
{ "vvai" , "వ్వై" },
{ "vhai" , "వ్హై" },
{ "śśai" , "శ్శై" },
{ "shai" , "షై" },
{ "ssai" , "స్సై" },
{ "smai" , "స్మై" },
{ "hhai" , "హ్హై" },
{ "hmai" , "హ్మై" },
{ "kkho" , "క్ఖొ" },
{ "ggho" , "ఘ్ఘొ" },
{ "ccho" , "ఛ్ఛొ" },
{ "jjho" , "ఝ్ఝొ" },
{ "ñcho" , "ఞ్ఛొ" },
{ "ñjho" , "ఞ్ఝొ" },
{ "ṭṭho" , "ఠ్ఠొ" },
{ "ḍḍho" , "ఢ్ఢొ" },
{ "ṇṭho" , "ణ్ఠొ" },
{ "ṇḍho" , "ణ్ఢొ" },
{ "ttho" , "త్థొ" },
{ "ntho" , "న్థొ" },
{ "ddho" , "ద్ధొ" },
{ "ndho" , "న్ధొ" },
{ "ppho" , "ప్ఫొ" },
{ "mpho" , "మ్ఫొ" },
{ "bbho" , "బ్భొ" },
{ "mbho" , "మ్భొ" },
{ "kkhō" , "క్ఖో" },
{ "gghō" , "ఘ్ఘో" },
{ "cchō" , "ఛ్ఛో" },
{ "jjhō" , "ఝ్ఝో" },
{ "ñchō" , "ఞ్ఛో" },
{ "ñjhō" , "ఞ్ఝో" },
{ "ṭṭhō" , "ఠ్ఠో" },
{ "ḍḍhō" , "ఢ్ఢో" },
{ "ṇṭhō" , "ణ్ఠో" },
{ "ṇḍhō" , "ణ్ఢో" },
{ "tthō" , "త్థో" },
{ "nthō" , "న్థో" },
{ "ddhō" , "ద్ధో" },
{ "ndhō" , "న్ధో" },
{ "pphō" , "ప్ఫో" },
{ "mphō" , "మ్ఫో" },
{ "bbhō" , "బ్భో" },
{ "mbhō" , "మ్భో" },
{ "kkao" , "క్కౌ" },
{ "kmao" , "క్మౌ" },
{ "khao" , "ఖౌ" },
{ "ggao" , "గ్గౌ" },
{ "ghao" , "ఘౌ" },
{ "ccao" , "చ్చౌ" },
{ "chao" , "ఛౌ" },
{ "jjao" , "జ్జౌ" },
{ "jhao" , "ఝౌ" },
{ "jñao" , "జ్ఞౌ" },
{ "ññao" , "ఞ్ఞౌ" },
{ "ñhao" , "ఞ్హౌ" },
{ "ñcao" , "ఞ్చౌ" },
{ "ñjao" , "ఞ్జౌ" },
{ "ṭṭao" , "ట్టౌ" },
{ "ṭhao" , "ఠౌ" },
{ "ḍḍao" , "డ్డౌ" },
{ "ḍhao" , "ఢౌ" },
{ "ṇṇao" , "ణ్ణౌ" },
{ "ṇhao" , "ణ్హౌ" },
{ "ṇṭao" , "ణ్టౌ" },
{ "nṭao" , "న్టౌ" },
{ "ṇḍao" , "ణ్డౌ" },
{ "ttao" , "త్తౌ" },
{ "ntao" , "న్తౌ" },
{ "thao" , "థౌ" },
{ "ddao" , "ద్దౌ" },
{ "ndao" , "న్దౌ" },
{ "dhao" , "ధౌ" },
{ "nnao" , "న్నౌ" },
{ "nhao" , "న్హౌ" },
{ "ppao" , "ప్పౌ" },
{ "mpao" , "మ్పౌ" },
{ "phao" , "ఫౌ" },
{ "bbao" , "బ్బౌ" },
{ "mbao" , "మ్బౌ" },
{ "bhao" , "భౌ" },
{ "mmao" , "మ్మౌ" },
{ "mhao" , "మ్హౌ" },
{ "yyao" , "య్యౌ" },
{ "yhao" , "య్హౌ" },
{ "rrao" , "ర్రౌ" },
{ "ṛṛao" , "ఱ్ఱౌ" },
{ "llao" , "ల్లౌ" },
{ "lhao" , "ల్హౌ" },
{ "ḷḷao" , "ళ్ళౌ" },
{ "ḷhao" , "ళ్హౌ" },
{ "vvao" , "వ్వౌ" },
{ "vhao" , "వ్హౌ" },
{ "śśao" , "శ్శౌ" },
{ "shao" , "షౌ" },
{ "ssao" , "స్సౌ" },
{ "smao" , "స్మౌ" },
{ "hhao" , "హ్హౌ" },
{ "hmao" , "హ్మౌ" },
{ "kkaṃ" , "క్కం" },
{ "kmaṃ" , "క్మం" },
{ "khaṃ" , "ఖం" },
{ "ggaṃ" , "గ్గం" },
{ "ghaṃ" , "ఘం" },
{ "ccaṃ" , "చ్చం" },
{ "chaṃ" , "ఛం" },
{ "jjaṃ" , "జ్జం" },
{ "jhaṃ" , "ఝం" },
{ "jñaṃ" , "జ్ఞం" },
{ "ññaṃ" , "ఞ్ఞం" },
{ "ñhaṃ" , "ఞ్హం" },
{ "ñcaṃ" , "ఞ్చం" },
{ "ñjaṃ" , "ఞ్జం" },
{ "ṭṭaṃ" , "ట్టం" },
{ "ṭhaṃ" , "ఠం" },
{ "ḍḍaṃ" , "డ్డం" },
{ "ḍhaṃ" , "ఢం" },
{ "ṇṇaṃ" , "ణ్ణం" },
{ "ṇhaṃ" , "ణ్హం" },
{ "ṇṭaṃ" , "ణ్టం" },
{ "nṭaṃ" , "న్టం" },
{ "ṇḍaṃ" , "ణ్డం" },
{ "ttaṃ" , "త్తం" },
{ "ntaṃ" , "న్తం" },
{ "thaṃ" , "థం" },
{ "ddaṃ" , "ద్దం" },
{ "ndaṃ" , "న్దం" },
{ "dhaṃ" , "ధం" },
{ "nnaṃ" , "న్నం" },
{ "nhaṃ" , "న్హం" },
{ "ppaṃ" , "ప్పం" },
{ "mpaṃ" , "మ్పం" },
{ "phaṃ" , "ఫం" },
{ "bbaṃ" , "బ్బం" },
{ "mbaṃ" , "మ్బం" },
{ "bhaṃ" , "భం" },
{ "mmaṃ" , "మ్మం" },
{ "mhaṃ" , "మ్హం" },
{ "yyaṃ" , "య్యం" },
{ "yhaṃ" , "య్హం" },
{ "rraṃ" , "ర్రం" },
{ "ṛṛaṃ" , "ఱ్ఱం" },
{ "llaṃ" , "ల్లం" },
{ "lhaṃ" , "ల్హం" },
{ "ḷḷaṃ" , "ళ్ళం" },
{ "ḷhaṃ" , "ళ్హం" },
{ "vvaṃ" , "వ్వం" },
{ "vhaṃ" , "వ్హం" },
{ "śśaṃ" , "శ్శం" },
{ "shaṃ" , "షం" },
{ "ssaṃ" , "స్సం" },
{ "smaṃ" , "స్మం" },
{ "hhaṃ" , "హ్హం" },
{ "hmaṃ" , "హ్మం" },
{ "kkiṃ" , "క్కిం" },
{ "kmiṃ" , "క్మిం" },
{ "khiṃ" , "ఖిం" },
{ "ggiṃ" , "గ్గిం" },
{ "ghiṃ" , "ఘిం" },
{ "cciṃ" , "చ్చిం" },
{ "chiṃ" , "ఛిం" },
{ "jjiṃ" , "జ్జిం" },
{ "jhiṃ" , "ఝిం" },
{ "jñiṃ" , "జ్ఞిం" },
{ "ññiṃ" , "ఞ్ఞిం" },
{ "ñhiṃ" , "ఞ్హిం" },
{ "ñciṃ" , "ఞ్చిం" },
{ "ñjiṃ" , "ఞ్జిం" },
{ "ṭṭiṃ" , "ట్టిం" },
{ "ṭhiṃ" , "ఠిం" },
{ "ḍḍiṃ" , "డ్డిం" },
{ "ḍhiṃ" , "ఢిం" },
{ "ṇṇiṃ" , "ణ్ణిం" },
{ "ṇhiṃ" , "ణ్హిం" },
{ "ṇṭiṃ" , "ణ్టిం" },
{ "nṭiṃ" , "న్టిం" },
{ "ṇḍiṃ" , "ణ్డిం" },
{ "ttiṃ" , "త్తిం" },
{ "ntiṃ" , "న్తిం" },
{ "thiṃ" , "థిం" },
{ "ddiṃ" , "ద్దిం" },
{ "ndiṃ" , "న్దిం" },
{ "dhiṃ" , "ధిం" },
{ "nniṃ" , "న్నిం" },
{ "nhiṃ" , "న్హిం" },
{ "ppiṃ" , "ప్పిం" },
{ "mpiṃ" , "మ్పిం" },
{ "phiṃ" , "ఫిం" },
{ "bbiṃ" , "బ్బిం" },
{ "mbiṃ" , "మ్బిం" },
{ "bhiṃ" , "భిం" },
{ "mmiṃ" , "మ్మిం" },
{ "mhiṃ" , "మ్హిం" },
{ "yyiṃ" , "య్యిం" },
{ "yhiṃ" , "య్హిం" },
{ "rriṃ" , "ర్రిం" },
{ "ṛṛiṃ" , "ఱ్ఱిం" },
{ "lliṃ" , "ల్లిం" },
{ "lhiṃ" , "ల్హిం" },
{ "ḷḷiṃ" , "ళ్ళిం" },
{ "ḷhiṃ" , "ళ్హిం" },
{ "vviṃ" , "వ్విం" },
{ "vhiṃ" , "వ్హిం" },
{ "śśiṃ" , "శ్శిం" },
{ "shiṃ" , "షిం" },
{ "ssiṃ" , "స్సిం" },
{ "smiṃ" , "స్మిం" },
{ "hhiṃ" , "హ్హిం" },
{ "hmiṃ" , "హ్మిం" },
{ "kkuṃ" , "క్కుం" },
{ "kmuṃ" , "క్ముం" },
{ "khuṃ" , "ఖుం" },
{ "gguṃ" , "గ్గుం" },
{ "ghuṃ" , "ఘుం" },
{ "ccuṃ" , "చ్చుం" },
{ "chuṃ" , "ఛుం" },
{ "jjuṃ" , "జ్జుం" },
{ "jhuṃ" , "ఝుం" },
{ "jñuṃ" , "జ్ఞుం" },
{ "ññuṃ" , "ఞ్ఞుం" },
{ "ñhuṃ" , "ఞ్హుం" },
{ "ñcuṃ" , "ఞ్చుం" },
{ "ñjuṃ" , "ఞ్జుం" },
{ "ṭṭuṃ" , "ట్టుం" },
{ "ṭhuṃ" , "ఠుం" },
{ "ḍḍuṃ" , "డ్డుం" },
{ "ḍhuṃ" , "ఢుం" },
{ "ṇṇuṃ" , "ణ్ణుం" },
{ "ṇhuṃ" , "ణ్హుం" },
{ "ṇṭuṃ" , "ణ్టుం" },
{ "nṭuṃ" , "న్టుం" },
{ "ṇḍuṃ" , "ణ్డుం" },
{ "ttuṃ" , "త్తుం" },
{ "ntuṃ" , "న్తుం" },
{ "thuṃ" , "థుం" },
{ "dduṃ" , "ద్దుం" },
{ "nduṃ" , "న్దుం" },
{ "dhuṃ" , "ధుం" },
{ "nnuṃ" , "న్నుం" },
{ "nhuṃ" , "న్హుం" },
{ "ppuṃ" , "ప్పుం" },
{ "mpuṃ" , "మ్పుం" },
{ "phuṃ" , "ఫుం" },
{ "bbuṃ" , "బ్బుం" },
{ "mbuṃ" , "మ్బుం" },
{ "bhuṃ" , "భుం" },
{ "mmuṃ" , "మ్ముం" },
{ "mhuṃ" , "మ్హుం" },
{ "yyuṃ" , "య్యుం" },
{ "yhuṃ" , "య్హుం" },
{ "rruṃ" , "ర్రుం" },
{ "ṛṛuṃ" , "ఱ్ఱుం" },
{ "lluṃ" , "ల్లుం" },
{ "lhuṃ" , "ల్హుం" },
{ "ḷḷuṃ" , "ళ్ళుం" },
{ "ḷhuṃ" , "ళ్హుం" },
{ "vvuṃ" , "వ్వుం" },
{ "vhuṃ" , "వ్హుం" },
{ "śśuṃ" , "శ్శుం" },
{ "shuṃ" , "షుం" },
{ "ssuṃ" , "స్సుం" },
{ "smuṃ" , "స్ముం" },
{ "hhuṃ" , "హ్హుం" },
{ "hmuṃ" , "హ్ముం" },
{ "kkra" , "క్క్ర" },
{ "kmra" , "క్మ్ర" },
{ "khra" , "ఖ్ర" },
{ "ggra" , "గ్గ్ర" },
{ "ghra" , "ఘ్ర" },
{ "ccra" , "చ్చ్ర" },
{ "chra" , "ఛ్ర" },
{ "jjra" , "జ్జ్ర" },
{ "jhra" , "ఝ్ర" },
{ "jñra" , "జ్ఞ్ర" },
{ "ññra" , "ఞ్ఞ్ర" },
{ "ñhra" , "ఞ్హ్ర" },
{ "ñcra" , "ఞ్చ్ర" },
{ "ñjra" , "ఞ్జ్ర" },
{ "ṭṭra" , "ట్ట్ర" },
{ "ṭhra" , "ఠ్ర" },
{ "ḍḍra" , "డ్డ్ర" },
{ "ḍhra" , "ఢ్ర" },
{ "ṇṇra" , "ణ్ణ్ర" },
{ "ṇhra" , "ణ్హ్ర" },
{ "ṇṭra" , "ణ్ట్ర" },
{ "nṭra" , "న్ట్ర" },
{ "ṇḍra" , "ణ్డ్ర" },
{ "ttra" , "త్త్ర" },
{ "ntra" , "న్త్ర" },
{ "thra" , "థ్ర" },
{ "ddra" , "ద్ద్ర" },
{ "ndra" , "న్ద్ర" },
{ "dhra" , "ధ్ర" },
{ "nnra" , "న్న్ర" },
{ "nhra" , "న్హ్ర" },
{ "ppra" , "ప్ప్ర" },
{ "mpra" , "మ్ప్ర" },
{ "phra" , "ఫ్ర" },
{ "bbra" , "బ్బ్ర" },
{ "mbra" , "మ్బ్ర" },
{ "bhra" , "భ్ర" },
{ "mmra" , "మ్మ్ర" },
{ "mhra" , "మ్హ్ర" },
{ "yyra" , "య్య్ర" },
{ "yhra" , "య్హ్ర" },
{ "rrra" , "ర్ర్ర" },
{ "ṛṛra" , "ఱ్ఱ్ర" },
{ "llra" , "ల్ల్ర" },
{ "lhra" , "ల్హ్ర" },
{ "ḷḷra" , "ళ్ళ్ర" },
{ "ḷhra" , "ళ్హ్ర" },
{ "vvra" , "వ్వ్ర" },
{ "vhra" , "వ్హ్ర" },
{ "śśra" , "శ్శ్ర" },
{ "shra" , "ష్ర" },
{ "ssra" , "స్స్ర" },
{ "smra" , "స్మ్ర" },
{ "hhra" , "హ్హ్ర" },
{ "hmra" , "హ్మ్ర" },
{ "kkya" , "క్క్య" },
{ "kmya" , "క్మ్య" },
{ "khya" , "ఖ్య" },
{ "ggya" , "గ్గ్య" },
{ "ghya" , "ఘ్య" },
{ "ccya" , "చ్చ్య" },
{ "chya" , "ఛ్య" },
{ "jjya" , "జ్జ్య" },
{ "jhya" , "ఝ్య" },
{ "jñya" , "జ్ఞ్య" },
{ "ññya" , "ఞ్ఞ్య" },
{ "ñhya" , "ఞ్హ్య" },
{ "ñcya" , "ఞ్చ్య" },
{ "ñjya" , "ఞ్జ్య" },
{ "ṭṭya" , "ట్ట్య" },
{ "ṭhya" , "ఠ్య" },
{ "ḍḍya" , "డ్డ్య" },
{ "ḍhya" , "ఢ్య" },
{ "ṇṇya" , "ణ్ణ్య" },
{ "ṇhya" , "ణ్హ్య" },
{ "ṇṭya" , "ణ్ట్య" },
{ "nṭya" , "న్ట్య" },
{ "ṇḍya" , "ణ్డ్య" },
{ "ttya" , "త్త్య" },
{ "ntya" , "న్త్య" },
{ "thya" , "థ్య" },
{ "ddya" , "ద్ద్య" },
{ "ndya" , "న్ద్య" },
{ "dhya" , "ధ్య" },
{ "nnya" , "న్న్య" },
{ "nhya" , "న్హ్య" },
{ "ppya" , "ప్ప్య" },
{ "mpya" , "మ్ప్య" },
{ "phya" , "ఫ్య" },
{ "bbya" , "బ్బ్య" },
{ "mbya" , "మ్బ్య" },
{ "bhya" , "భ్య" },
{ "mmya" , "మ్మ్య" },
{ "mhya" , "మ్హ్య" },
{ "yyya" , "య్య్య" },
{ "yhya" , "య్హ్య" },
{ "rrya" , "ర్ర్య" },
{ "ṛṛya" , "ఱ్ఱ్య" },
{ "llya" , "ల్ల్య" },
{ "lhya" , "ల్హ్య" },
{ "ḷḷya" , "ళ్ళ్య" },
{ "ḷhya" , "ళ్హ్య" },
{ "vvya" , "వ్వ్య" },
{ "vhya" , "వ్హ్య" },
{ "śśya" , "శ్శ్య" },
{ "shya" , "ష్య" },
{ "ssya" , "స్స్య" },
{ "smya" , "స్మ్య" },
{ "hhya" , "హ్హ్య" },
{ "hmya" , "హ్మ్య" },
{ "kkva" , "క్క్వ" },
{ "kmva" , "క్మ్వ" },
{ "khva" , "ఖ్వ" },
{ "ggva" , "గ్గ్వ" },
{ "ghva" , "ఘ్వ" },
{ "ccva" , "చ్చ్వ" },
{ "chva" , "ఛ్వ" },
{ "jjva" , "జ్జ్వ" },
{ "jhva" , "ఝ్వ" },
{ "jñva" , "జ్ఞ్వ" },
{ "ññva" , "ఞ్ఞ్వ" },
{ "ñhva" , "ఞ్హ్వ" },
{ "ñcva" , "ఞ్చ్వ" },
{ "ñjva" , "ఞ్జ్వ" },
{ "ṭṭva" , "ట్ట్వ" },
{ "ṭhva" , "ఠ్వ" },
{ "ḍḍva" , "డ్డ్వ" },
{ "ḍhva" , "ఢ్వ" },
{ "ṇṇva" , "ణ్ణ్వ" },
{ "ṇhva" , "ణ్హ్వ" },
{ "ṇṭva" , "ణ్ట్వ" },
{ "nṭva" , "న్ట్వ" },
{ "ṇḍva" , "ణ్డ్వ" },
{ "ttva" , "త్త్వ" },
{ "ntva" , "న్త్వ" },
{ "thva" , "థ్వ" },
{ "ddva" , "ద్ద్వ" },
{ "ndva" , "న్ద్వ" },
{ "dhva" , "ధ్వ" },
{ "nnva" , "న్న్వ" },
{ "nhva" , "న్హ్వ" },
{ "ppva" , "ప్ప్వ" },
{ "mpva" , "మ్ప్వ" },
{ "phva" , "ఫ్వ" },
{ "bbva" , "బ్బ్వ" },
{ "mbva" , "మ్బ్వ" },
{ "bhva" , "భ్వ" },
{ "mmva" , "మ్మ్వ" },
{ "mhva" , "మ్హ్వ" },
{ "yyva" , "య్య్వ" },
{ "yhva" , "య్హ్వ" },
{ "rrva" , "ర్ర్వ" },
{ "ṛṛva" , "ఱ్ఱ్వ" },
{ "llva" , "ల్ల్వ" },
{ "lhva" , "ల్హ్వ" },
{ "ḷḷva" , "ళ్ళ్వ" },
{ "ḷhva" , "ళ్హ్వ" },
{ "vvva" , "వ్వ్వ" },
{ "vhva" , "వ్హ్వ" },
{ "śśva" , "శ్శ్వ" },
{ "shva" , "ష్వ" },
{ "ssva" , "స్స్వ" },
{ "smva" , "స్మ్వ" },
{ "hhva" , "హ్హ్వ" },
{ "hmva" , "హ్మ్వ" },
{ "kkma" , "క్క్మ" },
{ "kmma" , "క్మ్మ" },
{ "khma" , "ఖ్మ" },
{ "ggma" , "గ్గ్మ" },
{ "ghma" , "ఘ్మ" },
{ "ccma" , "చ్చ్మ" },
{ "chma" , "ఛ్మ" },
{ "jjma" , "జ్జ్మ" },
{ "jhma" , "ఝ్మ" },
{ "jñma" , "జ్ఞ్మ" },
{ "ññma" , "ఞ్ఞ్మ" },
{ "ñhma" , "ఞ్హ్మ" },
{ "ñcma" , "ఞ్చ్మ" },
{ "ñjma" , "ఞ్జ్మ" },
{ "ṭṭma" , "ట్ట్మ" },
{ "ṭhma" , "ఠ్మ" },
{ "ḍḍma" , "డ్డ్మ" },
{ "ḍhma" , "ఢ్మ" },
{ "ṇṇma" , "ణ్ణ్మ" },
{ "ṇhma" , "ణ్హ్మ" },
{ "ṇṭma" , "ణ్ట్మ" },
{ "nṭma" , "న్ట్మ" },
{ "ṇḍma" , "ణ్డ్మ" },
{ "ttma" , "త్త్మ" },
{ "ntma" , "న్త్మ" },
{ "thma" , "థ్మ" },
{ "ddma" , "ద్ద్మ" },
{ "ndma" , "న్ద్మ" },
{ "dhma" , "ధ్మ" },
{ "nnma" , "న్న్మ" },
{ "nhma" , "న్హ్మ" },
{ "ppma" , "ప్ప్మ" },
{ "mpma" , "మ్ప్మ" },
{ "phma" , "ఫ్మ" },
{ "bbma" , "బ్బ్మ" },
{ "mbma" , "మ్బ్మ" },
{ "bhma" , "భ్మ" },
{ "mmma" , "మ్మ్మ" },
{ "mhma" , "మ్హ్మ" },
{ "yyma" , "య్య్మ" },
{ "yhma" , "య్హ్మ" },
{ "rrma" , "ర్ర్మ" },
{ "ṛṛma" , "ఱ్ఱ్మ" },
{ "llma" , "ల్ల్మ" },
{ "lhma" , "ల్హ్మ" },
{ "ḷḷma" , "ళ్ళ్మ" },
{ "ḷhma" , "ళ్హ్మ" },
{ "vvma" , "వ్వ్మ" },
{ "vhma" , "వ్హ్మ" },
{ "śśma" , "శ్శ్మ" },
{ "shma" , "ష్మ" },
{ "ssma" , "స్స్మ" },
{ "smma" , "స్మ్మ" },
{ "hhma" , "హ్హ్మ" },
{ "hmma" , "హ్మ్మ" },
{ "kkh" , "క్ఖ్" },
{ "ggh" , "ఘ్ఘ్" },
{ "cch" , "ఛ్ఛ్" },
{ "jjh" , "ఝ్ఝ్" },
{ "ñch" , "ఞ్ఛ్" },
{ "ñjh" , "ఞ్ఝ్" },
{ "ṭṭh" , "ఠ్ఠ్" },
{ "ḍḍh" , "ఢ్ఢ్" },
{ "ṇṭh" , "ణ్ఠ్" },
{ "ṇḍh" , "ణ్ఢ్" },
{ "tth" , "త్థ్" },
{ "nth" , "న్థ్" },
{ "ddh" , "ద్ధ్" },
{ "ndh" , "న్ధ్" },
{ "pph" , "ప్ఫ్" },
{ "mph" , "మ్ఫ్" },
{ "bbh" , "బ్భ్" },
{ "mbh" , "మ్భ్" },
{ "kka" , "క్క" },
{ "kma" , "క్మ" },
{ "kha" , "ఖ" },
{ "gga" , "గ్గ" },
{ "gha" , "ఘ" },
{ "cca" , "చ్చ" },
{ "cha" , "ఛ" },
{ "jja" , "జ్జ" },
{ "jha" , "ఝ" },
{ "jña" , "జ్ఞ" },
{ "ñña" , "ఞ్ఞ" },
{ "ñha" , "ఞ్హ" },
{ "ñca" , "ఞ్చ" },
{ "ñja" , "ఞ్జ" },
{ "ṭṭa" , "ట్ట" },
{ "ṭha" , "ఠ" },
{ "ḍḍa" , "డ్డ" },
{ "ḍha" , "ఢ" },
{ "ṇṇa" , "ణ్ణ" },
{ "ṇha" , "ణ్హ" },
{ "ṇṭa" , "ణ్ట" },
{ "nṭa" , "న్ట" },
{ "ṇḍa" , "ణ్డ" },
{ "tta" , "త్త" },
{ "nta" , "న్త" },
{ "tha" , "థ" },
{ "dda" , "ద్ద" },
{ "nda" , "న్ద" },
{ "dha" , "ధ" },
{ "nna" , "న్న" },
{ "nha" , "న్హ" },
{ "ppa" , "ప్ప" },
{ "mpa" , "మ్ప" },
{ "pha" , "ఫ" },
{ "bba" , "బ్బ" },
{ "mba" , "మ్బ" },
{ "bha" , "భ" },
{ "mma" , "మ్మ" },
{ "mha" , "మ్హ" },
{ "yya" , "య్య" },
{ "yha" , "య్హ" },
{ "rra" , "ర్ర" },
{ "ṛṛa" , "ఱ్ఱ" },
{ "lla" , "ల్ల" },
{ "lha" , "ల్హ" },
{ "ḷḷa" , "ళ్ళ" },
{ "ḷha" , "ళ్హ" },
{ "vva" , "వ్వ" },
{ "vha" , "వ్హ" },
{ "śśa" , "శ్శ" },
{ "sha" , "ష" },
{ "ssa" , "స్స" },
{ "sma" , "స్మ" },
{ "hha" , "హ్హ" },
{ "hma" , "హ్మ" },
{ "kkā" , "క్కా" },
{ "kmā" , "క్మా" },
{ "khā" , "ఖా" },
{ "ggā" , "గ్గా" },
{ "ghā" , "ఘా" },
{ "ccā" , "చ్చా" },
{ "chā" , "ఛా" },
{ "jjā" , "జ్జా" },
{ "jhā" , "ఝా" },
{ "jñā" , "జ్ఞా" },
{ "ññā" , "ఞ్ఞా" },
{ "ñhā" , "ఞ్హా" },
{ "ñcā" , "ఞ్చా" },
{ "ñjā" , "ఞ్జా" },
{ "ṭṭā" , "ట్టా" },
{ "ṭhā" , "ఠా" },
{ "ḍḍā" , "డ్డా" },
{ "ḍhā" , "ఢా" },
{ "ṇṇā" , "ణ్ణా" },
{ "ṇhā" , "ణ్హా" },
{ "ṇṭā" , "ణ్టా" },
{ "nṭā" , "న్టా" },
{ "ṇḍā" , "ణ్డా" },
{ "ttā" , "త్తా" },
{ "ntā" , "న్తా" },
{ "thā" , "థా" },
{ "ddā" , "ద్దా" },
{ "ndā" , "న్దా" },
{ "dhā" , "ధా" },
{ "nnā" , "న్నా" },
{ "nhā" , "న్హా" },
{ "ppā" , "ప్పా" },
{ "mpā" , "మ్పా" },
{ "phā" , "ఫా" },
{ "bbā" , "బ్బా" },
{ "mbā" , "మ్బా" },
{ "bhā" , "భా" },
{ "mmā" , "మ్మా" },
{ "mhā" , "మ్హా" },
{ "yyā" , "య్యా" },
{ "yhā" , "య్హా" },
{ "rrā" , "ర్రా" },
{ "ṛṛā" , "ఱ్ఱా" },
{ "llā" , "ల్లా" },
{ "lhā" , "ల్హా" },
{ "ḷḷā" , "ళ్ళా" },
{ "ḷhā" , "ళ్హా" },
{ "vvā" , "వ్వా" },
{ "vhā" , "వ్హా" },
{ "śśā" , "శ్శా" },
{ "shā" , "షా" },
{ "ssā" , "స్సా" },
{ "smā" , "స్మా" },
{ "hhā" , "హ్హా" },
{ "hmā" , "హ్మా" },
{ "kki" , "క్కి" },
{ "kmi" , "క్మి" },
{ "khi" , "ఖి" },
{ "ggi" , "గ్గి" },
{ "ghi" , "ఘి" },
{ "cci" , "చ్చి" },
{ "chi" , "ఛి" },
{ "jji" , "జ్జి" },
{ "jhi" , "ఝి" },
{ "jñi" , "జ్ఞి" },
{ "ññi" , "ఞ్ఞి" },
{ "ñhi" , "ఞ్హి" },
{ "ñci" , "ఞ్చి" },
{ "ñji" , "ఞ్జి" },
{ "ṭṭi" , "ట్టి" },
{ "ṭhi" , "ఠి" },
{ "ḍḍi" , "డ్డి" },
{ "ḍhi" , "ఢి" },
{ "ṇṇi" , "ణ్ణి" },
{ "ṇhi" , "ణ్హి" },
{ "ṇṭi" , "ణ్టి" },
{ "nṭi" , "న్టి" },
{ "ṇḍi" , "ణ్డి" },
{ "tti" , "త్తి" },
{ "nti" , "న్తి" },
{ "thi" , "థి" },
{ "ddi" , "ద్ది" },
{ "ndi" , "న్ది" },
{ "dhi" , "ధి" },
{ "nni" , "న్ని" },
{ "nhi" , "న్హి" },
{ "ppi" , "ప్పి" },
{ "mpi" , "మ్పి" },
{ "phi" , "ఫి" },
{ "bbi" , "బ్బి" },
{ "mbi" , "మ్బి" },
{ "bhi" , "భి" },
{ "mmi" , "మ్మి" },
{ "mhi" , "మ్హి" },
{ "yyi" , "య్యి" },
{ "yhi" , "య్హి" },
{ "rri" , "ర్రి" },
{ "ṛṛi" , "ఱ్ఱి" },
{ "lli" , "ల్లి" },
{ "lhi" , "ల్హి" },
{ "ḷḷi" , "ళ్ళి" },
{ "ḷhi" , "ళ్హి" },
{ "vvi" , "వ్వి" },
{ "vhi" , "వ్హి" },
{ "śśi" , "శ్శి" },
{ "shi" , "షి" },
{ "ssi" , "స్సి" },
{ "smi" , "స్మి" },
{ "hhi" , "హ్హి" },
{ "hmi" , "హ్మి" },
{ "kkī" , "క్కీ" },
{ "kmī" , "క్మీ" },
{ "khī" , "ఖీ" },
{ "ggī" , "గ్గీ" },
{ "ghī" , "ఘీ" },
{ "ccī" , "చ్చీ" },
{ "chī" , "ఛీ" },
{ "jjī" , "జ్జీ" },
{ "jhī" , "ఝీ" },
{ "jñī" , "జ్ఞీ" },
{ "ññī" , "ఞ్ఞీ" },
{ "ñhī" , "ఞ్హీ" },
{ "ñcī" , "ఞ్చీ" },
{ "ñjī" , "ఞ్జీ" },
{ "ṭṭī" , "ట్టీ" },
{ "ṭhī" , "ఠీ" },
{ "ḍḍī" , "డ్డీ" },
{ "ḍhī" , "ఢీ" },
{ "ṇṇī" , "ణ్ణీ" },
{ "ṇhī" , "ణ్హీ" },
{ "ṇṭī" , "ణ్టీ" },
{ "nṭī" , "న్టీ" },
{ "ṇḍī" , "ణ్డీ" },
{ "ttī" , "త్తీ" },
{ "ntī" , "న్తీ" },
{ "thī" , "థీ" },
{ "ddī" , "ద్దీ" },
{ "ndī" , "న్దీ" },
{ "dhī" , "ధీ" },
{ "nnī" , "న్నీ" },
{ "nhī" , "న్హీ" },
{ "ppī" , "ప్పీ" },
{ "mpī" , "మ్పీ" },
{ "phī" , "ఫీ" },
{ "bbī" , "బ్బీ" },
{ "mbī" , "మ్బీ" },
{ "bhī" , "భీ" },
{ "mmī" , "మ్మీ" },
{ "mhī" , "మ్హీ" },
{ "yyī" , "య్యీ" },
{ "yhī" , "య్హీ" },
{ "rrī" , "ర్రీ" },
{ "ṛṛī" , "ఱ్ఱీ" },
{ "llī" , "ల్లీ" },
{ "lhī" , "ల్హీ" },
{ "ḷḷī" , "ళ్ళీ" },
{ "ḷhī" , "ళ్హీ" },
{ "vvī" , "వ్వీ" },
{ "vhī" , "వ్హీ" },
{ "śśī" , "శ్శీ" },
{ "shī" , "షీ" },
{ "ssī" , "స్సీ" },
{ "smī" , "స్మీ" },
{ "hhī" , "హ్హీ" },
{ "hmī" , "హ్మీ" },
{ "kku" , "క్కు" },
{ "kmu" , "క్ము" },
{ "khu" , "ఖు" },
{ "ggu" , "గ్గు" },
{ "ghu" , "ఘు" },
{ "ccu" , "చ్చు" },
{ "chu" , "ఛు" },
{ "jju" , "జ్జు" },
{ "jhu" , "ఝు" },
{ "jñu" , "జ్ఞు" },
{ "ññu" , "ఞ్ఞు" },
{ "ñhu" , "ఞ్హు" },
{ "ñcu" , "ఞ్చు" },
{ "ñju" , "ఞ్జు" },
{ "ṭṭu" , "ట్టు" },
{ "ṭhu" , "ఠు" },
{ "ḍḍu" , "డ్డు" },
{ "ḍhu" , "ఢు" },
{ "ṇṇu" , "ణ్ణు" },
{ "ṇhu" , "ణ్హు" },
{ "ṇṭu" , "ణ్టు" },
{ "nṭu" , "న్టు" },
{ "ṇḍu" , "ణ్డు" },
{ "ttu" , "త్తు" },
{ "ntu" , "న్తు" },
{ "thu" , "థు" },
{ "ddu" , "ద్దు" },
{ "ndu" , "న్దు" },
{ "dhu" , "ధు" },
{ "nnu" , "న్ను" },
{ "nhu" , "న్హు" },
{ "ppu" , "ప్పు" },
{ "mpu" , "మ్పు" },
{ "phu" , "ఫు" },
{ "bbu" , "బ్బు" },
{ "mbu" , "మ్బు" },
{ "bhu" , "భు" },
{ "mmu" , "మ్ము" },
{ "mhu" , "మ్హు" },
{ "yyu" , "య్యు" },
{ "yhu" , "య్హు" },
{ "rru" , "ర్రు" },
{ "ṛṛu" , "ఱ్ఱు" },
{ "llu" , "ల్లు" },
{ "lhu" , "ల్హు" },
{ "ḷḷu" , "ళ్ళు" },
{ "ḷhu" , "ళ్హు" },
{ "vvu" , "వ్వు" },
{ "vhu" , "వ్హు" },
{ "śśu" , "శ్శు" },
{ "shu" , "షు" },
{ "ssu" , "స్సు" },
{ "smu" , "స్ము" },
{ "hhu" , "హ్హు" },
{ "hmu" , "హ్ము" },
{ "kkū" , "క్కూ" },
{ "kmū" , "క్మూ" },
{ "khū" , "ఖూ" },
{ "ggū" , "గ్గూ" },
{ "ghū" , "ఘూ" },
{ "ccū" , "చ్చూ" },
{ "chū" , "ఛూ" },
{ "jjū" , "జ్జూ" },
{ "jhū" , "ఝూ" },
{ "jñū" , "జ్ఞూ" },
{ "ññū" , "ఞ్ఞూ" },
{ "ñhū" , "ఞ్హూ" },
{ "ñcū" , "ఞ్చూ" },
{ "ñjū" , "ఞ్జూ" },
{ "ṭṭū" , "ట్టూ" },
{ "ṭhū" , "ఠూ" },
{ "ḍḍū" , "డ్డూ" },
{ "ḍhū" , "ఢూ" },
{ "ṇṇū" , "ణ్ణూ" },
{ "ṇhū" , "ణ్హూ" },
{ "ṇṭū" , "ణ్టూ" },
{ "nṭū" , "న్టూ" },
{ "ṇḍū" , "ణ్డూ" },
{ "ttū" , "త్తూ" },
{ "ntū" , "న్తూ" },
{ "thū" , "థూ" },
{ "ddū" , "ద్దూ" },
{ "ndū" , "న్దూ" },
{ "dhū" , "ధూ" },
{ "nnū" , "న్నూ" },
{ "nhū" , "న్హూ" },
{ "ppū" , "ప్పూ" },
{ "mpū" , "మ్పూ" },
{ "phū" , "ఫూ" },
{ "bbū" , "బ్బూ" },
{ "mbū" , "మ్బూ" },
{ "bhū" , "భూ" },
{ "mmū" , "మ్మూ" },
{ "mhū" , "మ్హూ" },
{ "yyū" , "య్యూ" },
{ "yhū" , "య్హూ" },
{ "rrū" , "ర్రూ" },
{ "ṛṛū" , "ఱ్ఱూ" },
{ "llū" , "ల్లూ" },
{ "lhū" , "ల్హూ" },
{ "ḷḷū" , "ళ్ళూ" },
{ "ḷhū" , "ళ్హూ" },
{ "vvū" , "వ్వూ" },
{ "vhū" , "వ్హూ" },
{ "śśū" , "శ్శూ" },
{ "shū" , "షూ" },
{ "ssū" , "స్సూ" },
{ "smū" , "స్మూ" },
{ "hhū" , "హ్హూ" },
{ "hmū" , "హ్మూ" },
{ "kru" , "కృ" },
{ "gru" , "గృ" },
{ "ṅru" , "ఙృ" },
{ "cru" , "చృ" },
{ "jru" , "జృ" },
{ "ñru" , "ఞృ" },
{ "ṭru" , "టృ" },
{ "ḍru" , "డృ" },
{ "ṇru" , "ణృ" },
{ "tru" , "తృ" },
{ "dru" , "దృ" },
{ "nru" , "నృ" },
{ "pru" , "పృ" },
{ "bru" , "బృ" },
{ "mru" , "మృ" },
{ "yru" , "యృ" },
//{ "rru" , "రృ" },
{ "ṛru" , "ఱృ" },
{ "lru" , "లృ" },
{ "ḷru" , "ళృ" },
{ "vru" , "వృ" },
{ "śru" , "శృ" },
{ "sru" , "సృ" },
{ "hru" , "హృ" },
{ "krū" , "కౄ" },
{ "grū" , "గౄ" },
{ "ṅrū" , "ఙౄ" },
{ "crū" , "చౄ" },
{ "jrū" , "జౄ" },
{ "ñrū" , "ఞౄ" },
{ "ṭrū" , "టౄ" },
{ "ḍrū" , "డౄ" },
{ "ṇrū" , "ణౄ" },
{ "trū" , "తౄ" },
{ "drū" , "దౄ" },
{ "nrū" , "నౄ" },
{ "prū" , "పౄ" },
{ "brū" , "బౄ" },
{ "mrū" , "మౄ" },
{ "yrū" , "యౄ" },
//{ "rrū" , "రౄ" },
{ "ṛrū" , "ఱౄ" },
{ "lrū" , "లౄ" },
{ "ḷrū" , "ళౄ" },
{ "vrū" , "వౄ" },
{ "śrū" , "శౄ" },
{ "srū" , "సౄ" },
{ "hrū" , "హౄ" },
{ "kke" , "క్కె" },
{ "kme" , "క్మె" },
{ "khe" , "ఖె" },
{ "gge" , "గ్గె" },
{ "ghe" , "ఘె" },
{ "cce" , "చ్చె" },
{ "che" , "ఛె" },
{ "jje" , "జ్జె" },
{ "jhe" , "ఝె" },
{ "jñe" , "జ్ఞె" },
{ "ññe" , "ఞ్ఞె" },
{ "ñhe" , "ఞ్హె" },
{ "ñce" , "ఞ్చె" },
{ "ñje" , "ఞ్జె" },
{ "ṭṭe" , "ట్టె" },
{ "ṭhe" , "ఠె" },
{ "ḍḍe" , "డ్డె" },
{ "ḍhe" , "ఢె" },
{ "ṇṇe" , "ణ్ణె" },
{ "ṇhe" , "ణ్హె" },
{ "ṇṭe" , "ణ్టె" },
{ "nṭe" , "న్టె" },
{ "ṇḍe" , "ణ్డె" },
{ "tte" , "త్తె" },
{ "nte" , "న్తె" },
{ "the" , "థె" },
{ "dde" , "ద్దె" },
{ "nde" , "న్దె" },
{ "dhe" , "ధె" },
{ "nne" , "న్నె" },
{ "nhe" , "న్హె" },
{ "ppe" , "ప్పె" },
{ "mpe" , "మ్పె" },
{ "phe" , "ఫె" },
{ "bbe" , "బ్బె" },
{ "mbe" , "మ్బె" },
{ "bhe" , "భె" },
{ "mme" , "మ్మె" },
{ "mhe" , "మ్హె" },
{ "yye" , "య్యె" },
{ "yhe" , "య్హె" },
{ "rre" , "ర్రె" },
{ "ṛṛe" , "ఱ్ఱె" },
{ "lle" , "ల్లె" },
{ "lhe" , "ల్హె" },
{ "ḷḷe" , "ళ్ళె" },
{ "ḷhe" , "ళ్హె" },
{ "vve" , "వ్వె" },
{ "vhe" , "వ్హె" },
{ "śśe" , "శ్శె" },
{ "she" , "షె" },
{ "sse" , "స్సె" },
{ "sme" , "స్మె" },
{ "hhe" , "హ్హె" },
{ "hme" , "హ్మె" },
{ "kkē" , "క్కే" },
{ "kmē" , "క్మే" },
{ "khē" , "ఖే" },
{ "ggē" , "గ్గే" },
{ "ghē" , "ఘే" },
{ "ccē" , "చ్చే" },
{ "chē" , "ఛే" },
{ "jjē" , "జ్జే" },
{ "jhē" , "ఝే" },
{ "jñē" , "జ్ఞే" },
{ "ññē" , "ఞ్ఞే" },
{ "ñhē" , "ఞ్హే" },
{ "ñcē" , "ఞ్చే" },
{ "ñjē" , "ఞ్జే" },
{ "ṭṭē" , "ట్టే" },
{ "ṭhē" , "ఠే" },
{ "ḍḍē" , "డ్డే" },
{ "ḍhē" , "ఢే" },
{ "ṇṇē" , "ణ్ణే" },
{ "ṇhē" , "ణ్హే" },
{ "ṇṭē" , "ణ్టే" },
{ "nṭē" , "న్టే" },
{ "ṇḍē" , "ణ్డే" },
{ "ttē" , "త్తే" },
{ "ntē" , "న్తే" },
{ "thē" , "థే" },
{ "ddē" , "ద్దే" },
{ "ndē" , "న్దే" },
{ "dhē" , "ధే" },
{ "nnē" , "న్నే" },
{ "nhē" , "న్హే" },
{ "ppē" , "ప్పే" },
{ "mpē" , "మ్పే" },
{ "phē" , "ఫే" },
{ "bbē" , "బ్బే" },
{ "mbē" , "మ్బే" },
{ "bhē" , "భే" },
{ "mmē" , "మ్మే" },
{ "mhē" , "మ్హే" },
{ "yyē" , "య్యే" },
{ "yhē" , "య్హే" },
{ "rrē" , "ర్రే" },
{ "ṛṛē" , "ఱ్ఱే" },
{ "llē" , "ల్లే" },
{ "lhē" , "ల్హే" },
{ "ḷḷē" , "ళ్ళే" },
{ "ḷhē" , "ళ్హే" },
{ "vvē" , "వ్వే" },
{ "vhē" , "వ్హే" },
{ "śśē" , "శ్శే" },
{ "shē" , "షే" },
{ "ssē" , "స్సే" },
{ "smē" , "స్మే" },
{ "hhē" , "హ్హే" },
{ "hmē" , "హ్మే" },
{ "kai" , "కై" },
{ "gai" , "గై" },
{ "ṅai" , "ఙై" },
{ "cai" , "చై" },
{ "jai" , "జై" },
{ "ñai" , "ఞై" },
{ "ṭai" , "టై" },
{ "ḍai" , "డై" },
{ "ṇai" , "ణై" },
{ "tai" , "తై" },
{ "dai" , "దై" },
{ "nai" , "నై" },
{ "pai" , "పై" },
{ "bai" , "బై" },
{ "mai" , "మై" },
{ "yai" , "యై" },
{ "rai" , "రై" },
{ "ṛai" , "ఱై" },
{ "lai" , "లై" },
{ "ḷai" , "ళై" },
{ "vai" , "వై" },
{ "śai" , "శై" },
{ "sai" , "సై" },
{ "hai" , "హై" },
{ "kko" , "క్కొ" },
{ "kmo" , "క్మొ" },
{ "kho" , "ఖొ" },
{ "ggo" , "గ్గొ" },
{ "gho" , "ఘొ" },
{ "cco" , "చ్చొ" },
{ "cho" , "ఛొ" },
{ "jjo" , "జ్జొ" },
{ "jho" , "ఝొ" },
{ "jño" , "జ్ఞొ" },
{ "ñño" , "ఞ్ఞొ" },
{ "ñho" , "ఞ్హొ" },
{ "ñco" , "ఞ్చొ" },
{ "ñjo" , "ఞ్జొ" },
{ "ṭṭo" , "ట్టొ" },
{ "ṭho" , "ఠొ" },
{ "ḍḍo" , "డ్డొ" },
{ "ḍho" , "ఢొ" },
{ "ṇṇo" , "ణ్ణొ" },
{ "ṇho" , "ణ్హొ" },
{ "ṇṭo" , "ణ్టొ" },
{ "nṭo" , "న్టొ" },
{ "ṇḍo" , "ణ్డొ" },
{ "tto" , "త్తొ" },
{ "nto" , "న్తొ" },
{ "tho" , "థొ" },
{ "ddo" , "ద్దొ" },
{ "ndo" , "న్దొ" },
{ "dho" , "ధొ" },
{ "nno" , "న్నొ" },
{ "nho" , "న్హొ" },
{ "ppo" , "ప్పొ" },
{ "mpo" , "మ్పొ" },
{ "pho" , "ఫొ" },
{ "bbo" , "బ్బొ" },
{ "mbo" , "మ్బొ" },
{ "bho" , "భొ" },
{ "mmo" , "మ్మొ" },
{ "mho" , "మ్హొ" },
{ "yyo" , "య్యొ" },
{ "yho" , "య్హొ" },
{ "rro" , "ర్రొ" },
{ "ṛṛo" , "ఱ్ఱొ" },
{ "llo" , "ల్లొ" },
{ "lho" , "ల్హొ" },
{ "ḷḷo" , "ళ్ళొ" },
{ "ḷho" , "ళ్హొ" },
{ "vvo" , "వ్వొ" },
{ "vho" , "వ్హొ" },
{ "śśo" , "శ్శొ" },
{ "sho" , "షొ" },
{ "sso" , "స్సొ" },
{ "smo" , "స్మొ" },
{ "hho" , "హ్హొ" },
{ "hmo" , "హ్మొ" },
{ "kkō" , "క్కో" },
{ "kmō" , "క్మో" },
{ "khō" , "ఖో" },
{ "ggō" , "గ్గో" },
{ "ghō" , "ఘో" },
{ "ccō" , "చ్చో" },
{ "chō" , "ఛో" },
{ "jjō" , "జ్జో" },
{ "jhō" , "ఝో" },
{ "jñō" , "జ్ఞో" },
{ "ññō" , "ఞ్ఞో" },
{ "ñhō" , "ఞ్హో" },
{ "ñcō" , "ఞ్చో" },
{ "ñjō" , "ఞ్జో" },
{ "ṭṭō" , "ట్టో" },
{ "ṭhō" , "ఠో" },
{ "ḍḍō" , "డ్డో" },
{ "ḍhō" , "ఢో" },
{ "ṇṇō" , "ణ్ణో" },
{ "ṇhō" , "ణ్హో" },
{ "ṇṭō" , "ణ్టో" },
{ "nṭō" , "న్టో" },
{ "ṇḍō" , "ణ్డో" },
{ "ttō" , "త్తో" },
{ "ntō" , "న్తో" },
{ "thō" , "థో" },
{ "ddō" , "ద్దో" },
{ "ndō" , "న్దో" },
{ "dhō" , "ధో" },
{ "nnō" , "న్నో" },
{ "nhō" , "న్హో" },
{ "ppō" , "ప్పో" },
{ "mpō" , "మ్పో" },
{ "phō" , "ఫో" },
{ "bbō" , "బ్బో" },
{ "mbō" , "మ్బో" },
{ "bhō" , "భో" },
{ "mmō" , "మ్మో" },
{ "mhō" , "మ్హో" },
{ "yyō" , "య్యో" },
{ "yhō" , "య్హో" },
{ "rrō" , "ర్రో" },
{ "ṛṛō" , "ఱ్ఱో" },
{ "llō" , "ల్లో" },
{ "lhō" , "ల్హో" },
{ "ḷḷō" , "ళ్ళో" },
{ "ḷhō" , "ళ్హో" },
{ "vvō" , "వ్వో" },
{ "vhō" , "వ్హో" },
{ "śśō" , "శ్శో" },
{ "shō" , "షో" },
{ "ssō" , "స్సో" },
{ "smō" , "స్మో" },
{ "hhō" , "హ్హో" },
{ "hmō" , "హ్మో" },
{ "kao" , "కౌ" },
{ "gao" , "గౌ" },
{ "ṅao" , "ఙౌ" },
{ "cao" , "చౌ" },
{ "jao" , "జౌ" },
{ "ñao" , "ఞౌ" },
{ "ṭao" , "టౌ" },
{ "ḍao" , "డౌ" },
{ "ṇao" , "ణౌ" },
{ "tao" , "తౌ" },
{ "dao" , "దౌ" },
{ "nao" , "నౌ" },
{ "pao" , "పౌ" },
{ "bao" , "బౌ" },
{ "mao" , "మౌ" },
{ "yao" , "యౌ" },
{ "rao" , "రౌ" },
{ "ṛao" , "ఱౌ" },
{ "lao" , "లౌ" },
{ "ḷao" , "ళౌ" },
{ "vao" , "వౌ" },
{ "śao" , "శౌ" },
{ "sao" , "సౌ" },
{ "hao" , "హౌ" },
{ "kaṃ" , "కం" },
{ "gaṃ" , "గం" },
{ "ṅaṃ" , "ఙం" },
{ "caṃ" , "చం" },
{ "jaṃ" , "జం" },
{ "ñaṃ" , "ఞం" },
{ "ṭaṃ" , "టం" },
{ "ḍaṃ" , "డం" },
{ "ṇaṃ" , "ణం" },
{ "taṃ" , "తం" },
{ "daṃ" , "దం" },
{ "naṃ" , "నం" },
{ "paṃ" , "పం" },
{ "baṃ" , "బం" },
{ "maṃ" , "మం" },
{ "yaṃ" , "యం" },
{ "raṃ" , "రం" },
{ "ṛaṃ" , "ఱం" },
{ "laṃ" , "లం" },
{ "ḷaṃ" , "ళం" },
{ "vaṃ" , "వం" },
{ "śaṃ" , "శం" },
{ "saṃ" , "సం" },
{ "haṃ" , "హం" },
{ "kiṃ" , "కిం" },
{ "giṃ" , "గిం" },
{ "ṅiṃ" , "ఙిం" },
{ "ciṃ" , "చిం" },
{ "jiṃ" , "జిం" },
{ "ñiṃ" , "ఞిం" },
{ "ṭiṃ" , "టిం" },
{ "ḍiṃ" , "డిం" },
{ "ṇiṃ" , "ణిం" },
{ "tiṃ" , "తిం" },
{ "diṃ" , "దిం" },
{ "niṃ" , "నిం" },
{ "piṃ" , "పిం" },
{ "biṃ" , "బిం" },
{ "miṃ" , "మిం" },
{ "yiṃ" , "యిం" },
{ "riṃ" , "రిం" },
{ "ṛiṃ" , "ఱిం" },
{ "liṃ" , "లిం" },
{ "ḷiṃ" , "ళిం" },
{ "viṃ" , "విం" },
{ "śiṃ" , "శిం" },
{ "siṃ" , "సిం" },
{ "hiṃ" , "హిం" },
{ "kuṃ" , "కుం" },
{ "guṃ" , "గుం" },
{ "ṅuṃ" , "ఙుం" },
{ "cuṃ" , "చుం" },
{ "juṃ" , "జుం" },
{ "ñuṃ" , "ఞుం" },
{ "ṭuṃ" , "టుం" },
{ "ḍuṃ" , "డుం" },
{ "ṇuṃ" , "ణుం" },
{ "tuṃ" , "తుం" },
{ "duṃ" , "దుం" },
{ "nuṃ" , "నుం" },
{ "puṃ" , "పుం" },
{ "buṃ" , "బుం" },
{ "muṃ" , "ముం" },
{ "yuṃ" , "యుం" },
{ "ruṃ" , "రుం" },
{ "ṛuṃ" , "ఱుం" },
{ "luṃ" , "లుం" },
{ "ḷuṃ" , "ళుం" },
{ "vuṃ" , "వుం" },
{ "śuṃ" , "శుం" },
{ "suṃ" , "సుం" },
{ "huṃ" , "హుం" },
{ "kra" , "క్ర" },
{ "gra" , "గ్ర" },
{ "ṅra" , "ఙ్ర" },
{ "cra" , "చ్ర" },
{ "jra" , "జ్ర" },
{ "ñra" , "ఞ్ర" },
{ "ṭra" , "ట్ర" },
{ "ḍra" , "డ్ర" },
{ "ṇra" , "ణ్ర" },
{ "tra" , "త్ర" },
{ "dra" , "ద్ర" },
{ "nra" , "న్ర" },
{ "pra" , "ప్ర" },
{ "bra" , "బ్ర" },
{ "mra" , "మ్ర" },
{ "yra" , "య్ర" },
//{ "rra" , "ర్ర" },
{ "ṛra" , "ఱ్ర" },
{ "lra" , "ల్ర" },
{ "ḷra" , "ళ్ర" },
{ "vra" , "వ్ర" },
{ "śra" , "శ్ర" },
{ "sra" , "స్ర" },
{ "hra" , "హ్ర" },
{ "kya" , "క్య" },
{ "gya" , "గ్య" },
{ "ṅya" , "ఙ్య" },
{ "cya" , "చ్య" },
{ "jya" , "జ్య" },
{ "ñya" , "ఞ్య" },
{ "ṭya" , "ట్య" },
{ "ḍya" , "డ్య" },
{ "ṇya" , "ణ్య" },
{ "tya" , "త్య" },
{ "dya" , "ద్య" },
{ "nya" , "న్య" },
{ "pya" , "ప్య" },
{ "bya" , "బ్య" },
{ "mya" , "మ్య" },
//{ "yya" , "య్య" },
{ "rya" , "ర్య" },
{ "ṛya" , "ఱ్య" },
{ "lya" , "ల్య" },
{ "ḷya" , "ళ్య" },
{ "vya" , "వ్య" },
{ "śya" , "శ్య" },
{ "sya" , "స్య" },
{ "hya" , "హ్య" },
{ "kva" , "క్వ" },
{ "gva" , "గ్వ" },
{ "ṅva" , "ఙ్వ" },
{ "cva" , "చ్వ" },
{ "jva" , "జ్వ" },
{ "ñva" , "ఞ్వ" },
{ "ṭva" , "ట్వ" },
{ "ḍva" , "డ్వ" },
{ "ṇva" , "ణ్వ" },
{ "tva" , "త్వ" },
{ "dva" , "ద్వ" },
{ "nva" , "న్వ" },
{ "pva" , "ప్వ" },
{ "bva" , "బ్వ" },
{ "mva" , "మ్వ" },
{ "yva" , "య్వ" },
{ "rva" , "ర్వ" },
{ "ṛva" , "ఱ్వ" },
{ "lva" , "ల్వ" },
{ "ḷva" , "ళ్వ" },
//{ "vva" , "వ్వ" },
{ "śva" , "శ్వ" },
{ "sva" , "స్వ" },
{ "hva" , "హ్వ" },
//{ "kma" , "క్మ" },
{ "gma" , "గ్మ" },
{ "ṅma" , "ఙ్మ" },
{ "cma" , "చ్మ" },
{ "jma" , "జ్మ" },
{ "ñma" , "ఞ్మ" },
{ "ṭma" , "ట్మ" },
{ "ḍma" , "డ్మ" },
{ "ṇma" , "ణ్మ" },
{ "tma" , "త్మ" },
{ "dma" , "ద్మ" },
{ "nma" , "న్మ" },
{ "pma" , "ప్మ" },
{ "bma" , "బ్మ" },
//{ "mma" , "మ్మ" },
{ "yma" , "య్మ" },
{ "rma" , "ర్మ" },
{ "ṛma" , "ఱ్మ" },
{ "lma" , "ల్మ" },
{ "ḷma" , "ళ్మ" },
{ "vma" , "వ్మ" },
{ "śma" , "శ్మ" },
//{ "sma" , "స్మ" },
//{ "hma" , "హ్మ" },
{ "kk" , "క్క్" },
{ "km" , "క్మ్" },
{ "kh" , "ఖ్" },
{ "gg" , "గ్గ్" },
{ "gh" , "ఘ్" },
{ "cc" , "చ్చ్" },
{ "ch" , "ఛ్" },
{ "jj" , "జ్జ్" },
{ "jh" , "ఝ్" },
{ "jñ" , "జ్ఞ్" },
{ "ññ" , "ఞ్ఞ్" },
{ "ñh" , "ఞ్హ్" },
{ "ñc" , "ఞ్చ్" },
{ "ñj" , "ఞ్జ్" },
{ "ṭṭ" , "ట్ట్" },
{ "ṭh" , "ఠ్" },
{ "ḍḍ" , "డ్డ్" },
{ "ḍh" , "ఢ్" },
{ "ṇṇ" , "ణ్ణ్" },
{ "ṇh" , "ణ్హ్" },
{ "ṇṭ" , "ణ్ట్" },
{ "nṭ" , "న్ట్" },
{ "ṇḍ" , "ణ్డ్" },
{ "tt" , "త్త్" },
{ "nt" , "న్త్" },
{ "th" , "థ్" },
{ "dd" , "ద్ద్" },
{ "nd" , "న్ద్" },
{ "dh" , "ధ్" },
{ "nn" , "న్న్" },
{ "nh" , "న్హ్" },
{ "pp" , "ప్ప్" },
{ "mp" , "మ్ప్" },
{ "ph" , "ఫ్" },
{ "bb" , "బ్బ్" },
{ "mb" , "మ్బ్" },
{ "bh" , "భ్" },
{ "mm" , "మ్మ్" },
{ "mh" , "మ్హ్" },
{ "yy" , "య్య్" },
{ "yh" , "య్హ్" },
{ "rr" , "ర్ర్" },
{ "ṛṛ" , "ఱ్ఱ్" },
{ "ll" , "ల్ల్" },
{ "lh" , "ల్హ్" },
{ "ḷḷ" , "ళ్ళ్" },
{ "ḷh" , "ళ్హ్" },
{ "vv" , "వ్వ్" },
{ "vh" , "వ్హ్" },
{ "śś" , "శ్శ్" },
{ "sh" , "ష్" },
{ "ss" , "స్స్" },
{ "sm" , "స్మ్" },
{ "hh" , "హ్హ్" },
{ "hm" , "హ్మ్" },
{ "ka" , "క" },
{ "ga" , "గ" },
{ "ṅa" , "ఙ" },
{ "ca" , "చ" },
{ "ja" , "జ" },
{ "ña" , "ఞ" },
{ "ṭa" , "ట" },
{ "ḍa" , "డ" },
{ "ṇa" , "ణ" },
{ "ta" , "త" },
{ "da" , "ద" },
{ "na" , "న" },
{ "pa" , "ప" },
{ "ba" , "బ" },
{ "ma" , "మ" },
{ "ya" , "య" },
{ "ra" , "ర" },
{ "ṛa" , "ఱ" },
{ "la" , "ల" },
{ "ḷa" , "ళ" },
{ "va" , "వ" },
{ "śa" , "శ" },
{ "sa" , "స" },
{ "ha" , "హ" },
{ "kā" , "కా" },
{ "gā" , "గా" },
{ "ṅā" , "ఙా" },
{ "cā" , "చా" },
{ "jā" , "జా" },
{ "ñā" , "ఞా" },
{ "ṭā" , "టా" },
{ "ḍā" , "డా" },
{ "ṇā" , "ణా" },
{ "tā" , "తా" },
{ "dā" , "దా" },
{ "nā" , "నా" },
{ "pā" , "పా" },
{ "bā" , "బా" },
{ "mā" , "మా" },
{ "yā" , "యా" },
{ "rā" , "రా" },
{ "ṛā" , "ఱా" },
{ "lā" , "లా" },
{ "ḷā" , "ళా" },
{ "vā" , "వా" },
{ "śā" , "శా" },
{ "sā" , "సా" },
{ "hā" , "హా" },
{ "ki" , "కి" },
{ "gi" , "గి" },
{ "ṅi" , "ఙి" },
{ "ci" , "చి" },
{ "ji" , "జి" },
{ "ñi" , "ఞి" },
{ "ṭi" , "టి" },
{ "ḍi" , "డి" },
{ "ṇi" , "ణి" },
{ "ti" , "తి" },
{ "di" , "ది" },
{ "ni" , "ని" },
{ "pi" , "పి" },
{ "bi" , "బి" },
{ "mi" , "మి" },
{ "yi" , "యి" },
{ "ri" , "రి" },
{ "ṛi" , "ఱి" },
{ "li" , "లి" },
{ "ḷi" , "ళి" },
{ "vi" , "వి" },
{ "śi" , "శి" },
{ "si" , "సి" },
{ "hi" , "హి" },
{ "kī" , "కీ" },
{ "gī" , "గీ" },
{ "ṅī" , "ఙీ" },
{ "cī" , "చీ" },
{ "jī" , "జీ" },
{ "ñī" , "ఞీ" },
{ "ṭī" , "టీ" },
{ "ḍī" , "డీ" },
{ "ṇī" , "ణీ" },
{ "tī" , "తీ" },
{ "dī" , "దీ" },
{ "nī" , "నీ" },
{ "pī" , "పీ" },
{ "bī" , "బీ" },
{ "mī" , "మీ" },
{ "yī" , "యీ" },
{ "rī" , "రీ" },
{ "ṛī" , "ఱీ" },
{ "lī" , "లీ" },
{ "ḷī" , "ళీ" },
{ "vī" , "వీ" },
{ "śī" , "శీ" },
{ "sī" , "సీ" },
{ "hī" , "హీ" },
{ "ku" , "కు" },
{ "gu" , "గు" },
{ "ṅu" , "ఙు" },
{ "cu" , "చు" },
{ "ju" , "జు" },
{ "ñu" , "ఞు" },
{ "ṭu" , "టు" },
{ "ḍu" , "డు" },
{ "ṇu" , "ణు" },
{ "tu" , "తు" },
{ "du" , "దు" },
{ "nu" , "ను" },
{ "pu" , "పు" },
{ "bu" , "బు" },
{ "mu" , "ము" },
{ "yu" , "యు" },
{ "ru" , "రు" },
{ "ṛu" , "ఱు" },
{ "lu" , "లు" },
{ "ḷu" , "ళు" },
{ "vu" , "వు" },
{ "śu" , "శు" },
{ "su" , "సు" },
{ "hu" , "హు" },
{ "kū" , "కూ" },
{ "gū" , "గూ" },
{ "ṅū" , "ఙూ" },
{ "cū" , "చూ" },
{ "jū" , "జూ" },
{ "ñū" , "ఞూ" },
{ "ṭū" , "టూ" },
{ "ḍū" , "డూ" },
{ "ṇū" , "ణూ" },
{ "tū" , "తూ" },
{ "dū" , "దూ" },
{ "nū" , "నూ" },
{ "pū" , "పూ" },
{ "bū" , "బూ" },
{ "mū" , "మూ" },
{ "yū" , "యూ" },
{ "rū" , "రూ" },
{ "ṛū" , "ఱూ" },
{ "lū" , "లూ" },
{ "ḷū" , "ళూ" },
{ "vū" , "వూ" },
{ "śū" , "శూ" },
{ "sū" , "సూ" },
{ "hū" , "హూ" },
{ "ke" , "కె" },
{ "ge" , "గె" },
{ "ṅe" , "ఙె" },
{ "ce" , "చె" },
{ "je" , "జె" },
{ "ñe" , "ఞె" },
{ "ṭe" , "టె" },
{ "ḍe" , "డె" },
{ "ṇe" , "ణె" },
{ "te" , "తె" },
{ "de" , "దె" },
{ "ne" , "నె" },
{ "pe" , "పె" },
{ "be" , "బె" },
{ "me" , "మె" },
{ "ye" , "యె" },
{ "re" , "రె" },
{ "ṛe" , "ఱె" },
{ "le" , "లె" },
{ "ḷe" , "ళె" },
{ "ve" , "వె" },
{ "śe" , "శె" },
{ "se" , "సె" },
{ "he" , "హె" },
{ "kē" , "కే" },
{ "gē" , "గే" },
{ "ṅē" , "ఙే" },
{ "cē" , "చే" },
{ "jē" , "జే" },
{ "ñē" , "ఞే" },
{ "ṭē" , "టే" },
{ "ḍē" , "డే" },
{ "ṇē" , "ణే" },
{ "tē" , "తే" },
{ "dē" , "దే" },
{ "nē" , "నే" },
{ "pē" , "పే" },
{ "bē" , "బే" },
{ "mē" , "మే" },
{ "yē" , "యే" },
{ "rē" , "రే" },
{ "ṛē" , "ఱే" },
{ "lē" , "లే" },
{ "ḷē" , "ళే" },
{ "vē" , "వే" },
{ "śē" , "శే" },
{ "sē" , "సే" },
{ "hē" , "హే" },
{ "ko" , "కొ" },
{ "go" , "గొ" },
{ "ṅo" , "ఙొ" },
{ "co" , "చొ" },
{ "jo" , "జొ" },
{ "ño" , "ఞొ" },
{ "ṭo" , "టొ" },
{ "ḍo" , "డొ" },
{ "ṇo" , "ణొ" },
{ "to" , "తొ" },
{ "do" , "దొ" },
{ "no" , "నొ" },
{ "po" , "పొ" },
{ "bo" , "బొ" },
{ "mo" , "మొ" },
{ "yo" , "యొ" },
{ "ro" , "రొ" },
{ "ṛo" , "ఱొ" },
{ "lo" , "లొ" },
{ "ḷo" , "ళొ" },
{ "vo" , "వొ" },
{ "śo" , "శొ" },
{ "so" , "సొ" },
{ "ho" , "హొ" },
{ "kō" , "కో" },
{ "gō" , "గో" },
{ "ṅō" , "ఙో" },
{ "cō" , "చో" },
{ "jō" , "జో" },
{ "ñō" , "ఞో" },
{ "ṭō" , "టో" },
{ "ḍō" , "డో" },
{ "ṇō" , "ణో" },
{ "tō" , "తో" },
{ "dō" , "దో" },
{ "nō" , "నో" },
{ "pō" , "పో" },
{ "bō" , "బో" },
{ "mō" , "మో" },
{ "yō" , "యో" },
{ "rō" , "రో" },
{ "ṛō" , "ఱో" },
{ "lō" , "లో" },
{ "ḷō" , "ళో" },
{ "vō" , "వో" },
{ "śō" , "శో" },
{ "sō" , "సో" },
{ "hō" , "హో" },
//{ "ru" , "బు" },
//{ "rū" , "బుూ" },
{ "ai" , "ఐ" },
{ "ao" , "ఔ" },
{ "aṃ" , "అం" },
{ "iṃ" , "ఇం" },
{ "uṃ" , "ఉం" },
{ "k" , "క్" },
{ "g" , "గ్" },
{ "ṅ" , "ఙ్" },
{ "c" , "చ్" },
{ "j" , "జ్" },
{ "ñ" , "ఞ్" },
{ "ṭ" , "ట్" },
{ "ḍ" , "డ్" },
{ "ṇ" , "ణ్" },
{ "t" , "త్" },
{ "d" , "ద్" },
{ "n" , "న్" },
{ "p" , "ప్" },
{ "b" , "బ్" },
{ "m" , "మ్" },
{ "y" , "య్" },
{ "r" , "ర్" },
{ "ṛ" , "ఱ్" },
{ "l" , "ల్" },
{ "ḷ" , "ళ్" },
{ "v" , "వ్" },
{ "ś" , "శ్" },
{ "s" , "స్" },
{ "h" , "హ్" },
{ "a" , "అ" },
{ "ā" , "ఆ" },
{ "i" , "ఇ" },
{ "ī" , "ఈ" },
{ "u" , "ఉ" },
{ "ū" , "ఊ" },
{ "e" , "ఎ" },
{ "ē" , "ఏ" },
{ "o" , "ఒ" },
{ "ō" , "ఓ" }
};

    Dictionary<string, string> char_unicode_to_my = new Dictionary<string, string> {
  {   "ggho",  "ဂ္ဃေါ" },
  {   "gghā",  "ဂ္ဃါ" },

  {   "ddho",  "ဒ္ဓေါ" },
  {   "ddhā",  "ဒ္ဓါ" },

  {   "ndho",  "န္ဓော" }, //
  {   "ndo",  "န္ဒော" }, //
  {   "ndā",  "န္ဒာ" }, //
  {   "ndhā",  "န္ဓာ" }, //

  {   "kho",  "ခေါ" }, //
  {   "khā",  "ခါ" }, //
  {   "kkho",  "က္ခော" }, //
  {   "kkhā",  "က္ခာ" }, //
  {   "go",  "ဂေါ" }, //
  {   "ṅo",  "ငေါ" }, //
  {   "dho",  "ဓေါ" }, //
  {   "do",  "ဒေါ" }, //
  {   "po",  "ပေါ" }, //
  {   "vo",  "ဝေါ" }, //
  {   "gā",  "ဂါ" }, //
  {   "ṅā",  "ငါ" }, //
  {   "dā",  "ဒါ" }, //
  {   "dhā",  "ဓါ" }, //
  {   "pā",  "ပါ" }, //
  {   "dvā",  "ဒွါ" }, //
  {   "tvā",  "တွာ" }, //
  {   "vā",  "ဝါ" }, //

  //{   "ppho",  "ပ္ဖေါ" },
  //{   "pphā",  "ပ္ဖါ" },

  {   "ss",  "ဿ္" },

  {   "vh",  "ဝှ္" },
  {   "vy",  "ဝျ္" },
  {   "vr",  "ဝြ္" },

  {   "yh",  "ယှ္" },
  {   "yy",  "ယျ္" },
  {   "yr",  "ယြ္" },
  {   "yv",  "ယွ္" },

  {   "hy",  "ဟျ္" },
  {   "hr",  "ဟြ္" },
  {   "hv",  "ဟွ္" },

  {   "rv",  "ရွ္" },
  {   "rh",  "ရှ္" },
  {   "ry",  "ရျ္" },

  {   "kh",  "ခ္" },
  {   "gh",  "ဃ္" },
  {   "ch",  "ဆ္" },
  {   "jh",  "ဈ္" },
  {   "ññ",  "ည္" },
  {   "ṭh",  "ဌ္" },
  {   "ḍh",  "ဎ္" },
  {   "th",  "ထ္" },
  {   "dh",  "ဓ္" },
  {   "ph",  "ဖ္" },
  {   "bh",  "ဘ္" },
  {   "k",  "က္" },
  {   "g",  "ဂ္" },
  {   "c",  "စ္" },
  {   "j",  "ဇ္" },
  {   "ñ",  "ဉ္" },
  {   "ḷ",  "ဠ္" },
  {   "ṭ",  "ဋ္" },
  {   "ḍ",  "ဍ္" },
  {   "ṇ",  "ဏ္" },
  {   "t",  "တ္" },
  {   "d",  "ဒ္" },
  {   "n",  "န္" },
  {   "p",  "ပ္" },
  {   "b",  "ဗ္" },
  {   "m",  "မ္" },
  {   "l",  "လ္" },
  {   "s",  "သ္" },
  {   "ṅ",  "င်္" },

  {   "္h",  "ှ္" },
  {   "h",  "ဟ္" },
  {   "္y",  "ျ္" },
  {   "y",  "ယ္" },
  {   "္r",  "ြ္" },
  {   "r",  "ရ္" },
  {   "္v",  "ွ္" },
  {   "v",  "ဝ္" },
  {   "္aṃ",  "ံ" },
  {   "္iṃ",  "ိံ" },
  {   "္uṃ",  "ုံ" },
  {   "္ā",  "ာ" },
  {   "္i",  "ိ" },
  {   "္ī",  "ီ" },
  {   "္u",  "ု" },
  {   "္ū",  "ူ" },
  {   "္e",  "ေ" },
  {   "္o",  "ော" },
  {   "aṃ",  "အံ" },
  {   "iṃ",  "ဣံ" },
  {   "uṃ",  "ဥံ" },
  {   "a",  "အ" },
  {   "ā",  "အာ" },
  {   "i",  "ဣ" },
  {   "ī",  "ဤ" },
  {   "u",  "ဥ" },
  {   "ū",  "ဦ" },
  {   "e",  "ဧ" },
  {   "o",  "ဩ" },
  {   "်္အ",  "" },
  {   "္အ",  "" },
  {   "1",  "၁" }, //新增数字
  {   "2",  "၂" },
  {   "3",  "၃" },
  {   "4",  "၄" },
  {   "5",  "၅" },
  {   "6",  "၆" },
  {   "7",  "၇" },
  {   "8",  "၈" },
  {   "9",  "၉" },
  {   "0",  "၀" },
    };
    //  Dictionary<string, string> char_unicode_to_my_reverse = new Dictionary<string, string> {
    //{   "ႁႏၵ",   "ndra" }, //後加
    //{   "ခ္",   "kh" },
    //{   "ဃ္",   "gh" },
    //{   "ဆ္",   "ch" },
    //{   "ဈ္",   "jh" },
    //{   "ည္",   "ññ" },
    //{   "ဌ္",   "ṭh" },
    //{   "ဎ္",   "ḍh" },
    //{   "ထ္",   "th" },
    //{   "ဓ္",   "dh" },
    //{   "ဖ္",   "ph" },
    //{   "ဘ္",   "bh" },
    //{   "က္",   "k" },
    //{   "ဂ္",   "g" },
    //{   "စ္",   "c" },
    //{   "ဇ္",   "j" },
    //{   "ဉ္",   "ñ" },
    //{   "ဠ္",   "ḷ" },
    //{   "ဋ္",   "ṭ" },
    //{   "ဍ္",   "ḍ" },
    //{   "ဏ္",   "ṇ" },
    //{   "တ္",   "t" },
    //{   "ဒ္",   "d" },
    //{   "န္",   "n" },
    //{   "ဟ္",   "h" },
    //{   "ပ္",   "p" },
    //{   "ဗ္",   "b" },
    //{   "မ္",   "m" },
    //{   "ယ္",   "y" },
    //{   "ရ္",   "r" },
    //{   "လ္",   "l" },
    //{   "ဝ္",   "v" },
    //{   "သ္",   "s" },
    //{   "င္",   "ṅ" },
    //{   "င်္",   "ṅ" },
    //{   "ဿ",   "ssa" },
    //{   "ခ",   "kha" },
    //{   "ဃ",   "gha" },
    //{   "ဆ",   "cha" },
    //{   "ဈ",   "jha" },
    //{   "စျ",   "jha" },
    //{   "ည",   "ñña" },
    //{   "ဌ",   "ṭha" },
    //{   "ဎ",   "ḍha" },
    //{   "ထ",   "tha" },
    //{   "ဓ",   "dha" },
    //{   "ဖ",   "pha" },
    //{   "ဘ",   "bha" },
    //{   "က",   "ka" },
    //{   "ဂ",   "ga" },
    //{   "စ",   "ca" },
    //{   "ဇ",   "ja" },
    //{   "ဉ",   "ña" },
    //{   "ဠ",   "ḷa" },
    //{   "ဋ",   "ṭa" },
    //{   "ဍ",   "ḍa" },
    //{   "ဏ",   "ṇa" },
    //{   "တ",   "ta" },
    //{   "ဒ",   "da" },
    //{   "န",   "na" },
    //{   "ဟ",   "ha" },
    //{   "ပ",   "pa" },
    //{   "ဗ",   "ba" },
    //{   "မ",   "ma" },
    //{   "ယ",   "ya" },
    //{   "ရ",   "ra" },
    //{   "႐",   "ra" }, //后加
    //{   "လ",   "la" },
    //{   "ဝ",   "va" },
    //{   "သ",   "sa" },
    //{   "aျ္",   "ya" },
    //{   "aွ္",   "va" },
    //{   "aြ္",   "ra" },
    //{   "aြ",   "ra" },

    //{   "ၱ",   "္ta" }, //后加
    //{   "ၳ",   "္tha" }, //后加
    //{   "ၵ",   "္da" }, //后加
    //{   "ၶ",   "္dha" }, //后加

    //{   "ၬ",   "္ṭa" }, //后加
    //{   "ၭ",   "္ṭha" }, //后加

    //{   "ၠ",   "္ka" }, //后加
    //{   "ၡ",   "္kha" }, //后加
    //{   "ၢ",   "္ga" }, //后加
    //{   "ၣ",   "္gha" }, //后加

    //{   "ၸ",   "္pa" }, //后加
    //{   "ၹ",   "္pha" }, //后加
    //{   "ၺ",   "္ba" }, //后加
    //{   "႓",   "္bha" }, //后加

    //{   "ၥ",   "္ca" }, //后加
    //{   "ၧ",   "္cha" }, //后加
    //{   "ၨ",   "္ja" }, //后加
    //{   "ၩ",   "္jha" }, //后加

    //{   "်",   "္a" }, //后加
    //{   "ျ",   "္ya" }, //后加
    //{   "ႅ",   "္la" }, //后加
    //{   "ၼ",   "္ma" }, //后加
    //{   "ွ",   "္va" }, //后加
    //{   "ႇ",   "္ha" }, //后加
    //{   "ႆ",   "ssa" }, //后加
    //{   "ၷ",   "na" }, //后加
    //{   "ၲ",   "ta" }, //后加

    //{   "႒",   "ṭṭha" }, //后加
    //{   "႗",   "ṭṭa" }, //后加
    //{   "ၯ",   "ḍḍha" }, //后加
    //{   "ၮ",   "ḍḍa" }, //后加
    //{   "႑",   "ṇḍa" }, //后加

    //{   "kaၤ",   "ṅka" }, //后加
    //{   "gaၤ",   "ṅga" }, //后加
    //{   "khaၤ",   "ṅkha" }, //后加
    //{   "ghaၤ",   "ṅgha" }, //后加

    //{   "aှ",   "ha" },
    //{   "aိံ",   "iṃ" },
    //{   "aုံ",   "uṃ" },
    //{   "aော",   "o" },
    //{   "aေါ",   "o" },
    //{   "aအံ",   "aṃ" },
    //{   "aဣံ",   "iṃ" },
    //{   "aဥံ",   "uṃ" },
    //{   "aံ",   "aṃ" },
    //{   "aာ",   "ā" },
    //{   "aါ",   "ā" },
    //{   "aိ",   "i" },
    //{   "aီ",   "ī" },
    //{   "aု",   "u" },
    //{   "aဳ",   "u" }, //後加
    //{   "aူ",   "ū" },
    //{   "aေ",   "e" },
    //{   "အါ",   "ā" },
    //{   "အာ",   "ā" },
    //{   "အ",   "a" },
    //{   "ဣ",   "i" },
    //{   "ဤ",   "ī" },
    //{   "ဥ",   "u" },
    //{   "ဦ",   "ū" },
    //{   "ဧ",   "e" },
    //{   "ဩ",   "o" },
    //{   "ႏ",   "n" }, //後加
    //{   "ၪ",   "ñ" }, //後加
    //{   "a္",   "" }, //後加
    //{   "္",   "" }, //後加
    //{   "aံ",   "aṃ" },

    //{   "ေss",   "sse" }, //后加
    //{   "ေkh",   "khe" }, //后加
    //{   "ေgh",   "ghe" }, //后加
    //{   "ေch",   "che" }, //后加
    //{   "ေjh",   "jhe" }, //后加
    //{   "ေññ",   "ññe" }, //后加
    //{   "ေṭh",   "ṭhe" }, //后加
    //{   "ေḍh",   "ḍhe" }, //后加
    //{   "ေth",   "the" }, //后加
    //{   "ေdh",   "dhe" }, //后加
    //{   "ေph",   "phe" }, //后加
    //{   "ေbh",   "bhe" }, //后加
    //{   "ေk",   "ke" }, //后加
    //{   "ေg",   "ge" }, //后加
    //{   "ေc",   "ce" }, //后加
    //{   "ေj",   "je" }, //后加
    //{   "ေñ",   "ñe" }, //后加
    //{   "ေḷ",   "ḷe" }, //后加
    //{   "ေṭ",   "ṭe" }, //后加
    //{   "ေḍ",   "ḍe" }, //后加
    //{   "ေṇ",   "ṇe" }, //后加
    //{   "ေt",   "te" }, //后加
    //{   "ေd",   "de" }, //后加
    //{   "ေn",   "ne" }, //后加
    //{   "ေh",   "he" }, //后加
    //{   "ေp",   "pe" }, //后加
    //{   "ေb",   "be" }, //后加
    //{   "ေm",   "me" }, //后加
    //{   "ေy",   "ye" }, //后加
    //{   "ေr",   "re" }, //后加
    //{   "ေl",   "le" }, //后加
    //{   "ေv",   "ve" }, //后加
    //{   "ေs",   "se" }, //后加
    //{   "ေy",   "ye" }, //后加
    //{   "ေv",   "ve" }, //后加
    //{   "ေr",   "re" }, //后加

    //{   "ea",   "e" }, //后加
    //{   "eā",   "o" }, //后加

    //{  "၁",   "1" },
    //{  "၂",   "2" },
    //{  "၃",   "3" },
    //{  "၄",   "4" },
    //{  "၅",   "5" },
    //{  "၆",   "6" },
    //{  "၇",   "7" },
    //{  "၈",   "8" },
    //{  "၉",   "9" },
    //{  "၀",   "0" },
    //{  "း",   "”" },
    //{  "့",   "’" },
    //{  "။",   "．" },
    //{  "၊",   "，" },
    //  };
    Dictionary<string, string> char_unicode_my_correct = new Dictionary<string, string>
    {
        { "ခော",  "ခေါ" }, //矫正缅文转码错误
  { "ခာ",  "ခါ" }, //kh
  { "က္ခေါ",  "က္ခော" }, //kkho
  { "က္ခါ",  "က္ခာ" }, //kkhā
  { "ဂော",  "ဂေါ" }, //go
  { "ငော",  "ငေါ" }, //ṅo
  { "ဓော",  "ဓေါ" }, //dho
  { "ဒော",  "ဒေါ" }, //do
  { "ပော",  "ပေါ" }, //po
  { "ဝော",  "ဝေါ" }, //vo
  { "ဂာ",  "ဂါ" }, //gā
  { "ငာ",  "ငါ" }, //ṅā
  { "ဒာ",  "ဒါ" }, //dā
  { "ဓာ",  "ဓါ" }, //dhā
  { "ပာ",  "ပါ" }, //pā
  { "ဝာ",  "ဝါ" }, //vā
  { "ဒွာ",  "ဒွါ" }, //dvā

    };


    Dictionary<string, string> char_unicode_to_pali_int = new Dictionary<string, string>()
    {
    { "1",  "eka" },
    { "2",  "dve" },
    { "3",  "taya" },
    { "4",  "catu" },
    { "5",  "pañca" },
    { "6",  "cha" },
    { "7",  "satta" },
    { "8",  "aṭṭha" },
    { "9",  "nava" },
    { "10",  "dasa" },
    };
}
