using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UserGrammar
{
    public static Dictionary<string, string[]> grammar_cn = new Dictionary<string, string[]>(){
  {"grammar_loc",  new string[]{
"# 处格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|Bhumma-vacana\\(常见于注释书\\)<br>sattamī-vibhatti\\(常见于语法书\\)|",
"|汉|**处**|处格<br>位置格<br>位格<br>在格<br>于格<br>依格<br>第七变格|",
"|英|**loc.**|locative case|",
}},
  {"studio_parent2",  new string[]{
"## 衍生原型",
"范例：",
"- 拼写：karontassa",
"- 词典原型：karonta（现代分词）",
"- 此处：karo(ti)",
"- 下拉菜单选择：prp（现代分词）",
}},
  {"grammar_2p",  new string[]{
"## 第二人称",
"",
"缩写： 2p",
"",
"动词的一种变化形式。动作的发出者是第二人称（你、你们）。",
}},
  {"grammar_3p",  new string[]{
"## 第三人称",
"",
"缩写： 3p",
"",
"动词的一种变化形式。动作的发出者是第三人称（他、他们、她、她们、它、它们）。",
}},
  {"grammar_impf",  new string[]{
"# 过去未完成时",
"",
"* 其他名称： 未完成时",
"* 巴利术语： Hiyyattanã / Anajjatana",
"* 英文缩写： imperf. / impf.",
"* 英文全称： Past Imperfect Tense",
}},
  {"grammar_nt",  new string[]{
"# 中性",
"- 如果在查**词典源型**时出现，则代表该**词**的语法信息中应选择**名词**&**中性**",
"- 如果在查**语尾**时出现，则代表该**语尾**有应用在**中性词**中的可能性",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|**na**|napuṃsaka<br>napuṃsakaliṅga|",
"|汉|**中**|**中性**|",
"|英|**nt.**<br>**n.**|Neutral|",
"",
"**名词**、**三性词**所具有的属性之一，谓语动词和不变词不具有性",
}},
  {"grammar_gen",  new string[]{
"# 属格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|sa|sāmivacana 常见于注释书<br>chaṭṭhī-vibhatti 常见于语法书|",
"|汉|属|属格<br>所有格<br>领格<br>领属格<br>第六变格|",
"|英|gen.|genitive case|",
}},
  {"studio",  new string[]{
}},
  {"grammar_base",  new string[]{
"# 词典源型",
"即词典中实际出现的，能够找到其原本含义的拼写",
"对应的类似内容有**语基**，**语干**，**词干**，**词基**，**原型**等。",
}},
  {"grammar_pres",  new string[]{
"# 现在式",
"",
"**动词**变位之一，表示当下发生的动作。",
"其中，动词的现在式的第三人称单数变化，作为词典收录动词的标准形式——**词典源型**。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|paccuppanna|",
"|汉|现|现在式|",
"|英|pres.|present tense|",
"",
"## 常用语尾表",
"",
"|现在时|单数|复数|",
"| -- | -- | -- |",
"|第三人称|-ti<br>TA**正在**…|-nti<br>TA们**正在**…|",
"|第二人称|-si<br>你**正在**…|-tha<br>你们**正在**…|",
"|第一人称|-āmi<br>我**正在**…|-āma<br>我们**正在**…|",
"",
}},
  {"channel_guide",  new string[]{
"## 什么是版本风格?",
"",
"在我们在学习、翻译某段巴利文献时，需要记录一些东西，例如：母语译文、非母语译文、随堂笔记、注释等等。",
"在记录这些内容时，我们需要**标注**这些文字是**什么内容类型**和**什么语言**，这就是**版本风格**。",
"",
"可以实现**多语言**和多种**行文风格**，例如：",
"- 巴利直译",
"- 注释",
"- 演讲稿",
"- 草稿",
"- grammatical translation",
"- commentaries",
"- speech text",
"- draft",
"",
"这些**版本风格**会显示为：名称-语言@用户昵称，例如：",
"",
"- 巴利直译-中文@Bhikkhu Kosalla",
"",
"还可以利用此功能实现的其他功能，等待大家的挖掘。",
}},
  {"grammar_inf",  new string[]{
"# 不定式",
"",
"相当于动词不定式",
"",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利||——|",
"|汉|不定|不定体|",
"|英|inf.|Infinitive|",
}},
  {"term_pedia_sys",  new string[]{
"## 术语百科系统",
"术语+注释书名词解释=巴利百科词条",
"### 视频演示",
"* [YouTube](https://youtu.be/YxVwxYA4spU)",
"",
"### 具体操作",
"* 首先创建术语",
"* 然后复制句子编号",
"* 将句子编号黏贴到下面的输入框中",
"* 系统会自动根据句子编号，返回巴利原文、译文以及引用路径",
"### 结果呈现",
"[巴利百科](https://www.wikipali.org/app/wiki/)",
}},
  {"grammar_fpp",  new string[]{
"# 未来被动分词",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|——|",
"|汉|**未来被分**|未来被动分词<br>义务分词|",
"|英|**fpp.**<br>**grd.**|future passive participle<br>gerundive<br>participle of necessity|",
"",
"<a href=\"https://visuddhinanda.gitbook.io/palihand-book/verbal/fpp.md\" target=\"_blank\">详情</a>",
}},
  {"grammar_acc",  new string[]{
"# 宾格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|Upayoga-vacana<br>(常见于注释书)<br>dutiyā-vibhatti<br>(常见于语法书)|",
"|汉|**宾**|宾格<br>业格<br>受格<br>对格<br>第二变格|",
"|英|**acc.**|accusative case|",
}},
  {"grammar_my_def",  new string[]{
"# 缅文语尾",
"",
"## 时间状语从句",
"",
"用分词或普通名词引导从句",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**主**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**目标动词发生的时间**|当……时|[分词 ➡ 动词<br>DEF](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/advance-relation/20_nouns.html)|",
"|[**属**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/gen.html)|表达**目标动词发生的时间**|当……时|[分词 ➡ 动词<br>DEF](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/verb/abs_clause.html)|",
"|[**处**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/loc.html)|表达**目标动词发生的时间**|当……时|[分词 ➡ 动词<br>DEF](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/verb/abs_clause.html)|",
"",
}},
  {"grammar_my_inst1",  new string[]{
"# 缅文语尾",
"## 方式karaṇa",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**具**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/instr.html)|表达**方式**|用……，以……，通过……|[方式 ➡ 动词<br>IMP](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-imp.html)|",
"|[来**源**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/abl.html)|表达**方式**|用……，以……，通过……|[方式 ➡ 动词<br>IMP](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-imp.html)|",
}},
  {"markdown_guide",  new string[]{
"# 译文输入范例指南",
"[详细范例](https://www.markdownguide.org/basic-syntax/)",
"## 文本样式",
"|输入|显示|",
"|-|-|",
"|`[[pāḷi]]`|[术语<sub>1</sub>]()(pāḷi, 术语<sub>2</sub>)|",
"|`**粗体**`|**粗体**|",
"|`*斜体*`|*斜体*|",
"|`***粗斜体***`|***粗斜体***|",
"|`~~校对删除~~`|~~校对删除~~|",
"|`[链接标题](www.wikipali.org \"注&#10;释\")`|[链接标题](www.wikipali.org \"注&#10;释\")|",
"",
"## 段落样式",
"",
"",
"<div style=\"display:flex;\">",
"",
"<div style=\"flex:1;margin-right:1em;\">",
"",
"### **输入**",
"",
"",
"```",
"单回车不折行",
"双回车",
"",
"真换行",
"",
"---",
"分割线---前需要双回车",
"```",
"</div>",
"<div style=\"flex:1;\">",
"",
"### **显示**",
"",
"单回车不折行",
"双回车",
"",
"真换行",
"",
"---",
"分割线---前需要双回车",
"</div></div>",
}},
  {"grammar_my_abl2",  new string[]{
"# 缅文语尾",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[来**源**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/abl.html)|表达**比较**|比……多|[**参照** ➡ 比较级<br>COC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-coc.html)|",
}},
  {"grammar_fut",  new string[]{
"# 将来时",
"",
"**动词**变位之一，表示将要发生或将要做（的事情），动作。相当于英语的一般将来时。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|Anāgata|",
"|汉|**将**|将来式|",
"|英|**fur.**|Future tense|",
"",
"## 常用语尾表",
"",
"|将来时|单数|复数|",
"| -- | -- | -- |",
"|第三人称|-(i)ssati<br>TA**将**…|-(i)ssanti<br>TA们**将**…|",
"|第二人称|-(i)ssasi<br>你**将**…|-(i)ssatha<br>你们**将**…|",
"|第一人称|-(i)ssāmi<br>我**将**…|-(i)ssāma<br>我们**将**…|",
}},
  {"grammar_pr",  new string[]{
"# 现在式",
"",
}},
  {"grammar_f",  new string[]{
"# 阴性",
"- 如果在查**词典源型**时出现，则代表该**词**的语法信息中应选择**名词**&**阴性**",
"- 如果在查**语尾**时出现，则代表该**语尾**有应用在**阴性词**中的可能性",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|**thī**|itthi<br>itthiliṅga<br>thīliṅga|",
"|汉|**阴**|**阴性**|",
"|英|**f.**|Feminine|",
"",
"**名词**、**三性词**所具有的属性之一，谓语动词和不变词不具有性",
}},
  {"grammar_pl",  new string[]{
"# 复数",
"",
"> Bahūnamatthānaṃ vacanaṃ bahuvacanaṃ.",
"> 表达“有多个”含义的用语，为复数。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|**bahu**|bahuvacana|",
"|汉|**复**|**复数**|",
"|英|**pl.**<br>**p.**|plural|",
}},
  {"grammar_cond",  new string[]{
"# 条件式（动词变位之一）",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利||Kālātipatti|",
"|汉|条|条件式|",
"|英|cond.|Conditional Tense|",
"",
"* 巴利语： ",
"* 英语: ",
"* 缩写：",
"* 其他名称：",
}},
  {"grammar_prp",  new string[]{
"## 现在分词",
"",
"- 有两种",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|mānanta|",
"|汉|**现分**|现在分词|",
"|英|**prp.**<br>**pr.p.**<br>**ppr.**|Present Participle<br>|",
}},
  {"grammar_abs",  new string[]{
"# 连续体",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——||",
"|汉|**绝对**<br>**连续**|绝对体<br>连续体<br>独立体<br>不变分词|",
"|英|**abs.**<br>**ger.**|absolutive<br>gerund|",
}},
  {"grammar_voc",  new string[]{
"# 呼格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|Āmantana-vacana\\(常见于注释书\\)<br>paṭhamā-vibhatti\\(常见于语法书\\)|",
"|汉|**呼**|呼格<br>第一变格|",
"|英|**voc.**|vocative case|",
}},
  {"studio_message",  new string[]{
"## 消息功能",
"通过消息功能，实现翻译的网络协作。",
"",
"只有具备**共享属性**的文档，才可以发消息。",
"",
"逐词译、译文的每次修改，都会发消息给协作者",
"",
"数据合并逻辑：",
"- 用户数据大体包括四种状态",
"  - 用户**手动**修改",
"  - 他人**消息**推动",
"  - 机器**自动**匹配",
"  - 新经文中的**未填充**部分",
"- 覆盖逻辑",
"  - 手动>消息>自动>未填充",
"-  未能覆盖则在改数据位置上显示<span style=\"color:#f9468f\">消息数量</span>提示",
}},
  {"grammar_my_nom1",  new string[]{
"# 缅文语尾",
"",
"## 主语",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**主**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|表达**施动者**|——|[施动者 ➡ 动词<br>ASV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/nom/nom-asv.html)|",
"|[工**具**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**施动者**|被……|[施动者 ➡ 被动动词<br>ISV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-isv.html)|",
"|[**属**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**施动者**|……的|[施动者 ➡ 动词<br>ISV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/gen/gen-isv.html)|",
}},
  {"grammar_ind",  new string[]{
"# 不变词",
"",
"|语种|全称|",
"|-|-|",
"|巴利|bya<br>nipāta|",
"|汉|不变词|",
"|英|indeclinable|",
}},
  {"grammar_denom",  new string[]{
"# 名动词",
"",
"从名词衍化成动词的词。",
}},
  {"grammar_num",  new string[]{
"# 数词",
"## 1-4",
"为**三性**词",
"## 5以上的数词",
"有变格的写**数**词",
"没有变格的选**数词干**",
}},
  {"grammar_cf",  new string[]{
"# 参考",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|——|",
"|汉|**参考**|参考|",
"|英|**cf.**||",
"",
}},
  {"grammar_nom",  new string[]{
"# 主格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|sa|Paccatta-vacana\\(常见于注释书\\)<br>paṭhamā-vibhatti\\(常见于语法书\\)|",
"|汉|**主**|主格<br>体格<br>第一变格|",
"|英|**nom.**|nominative case|",
"",
}},
  {"dict_search_input",  new string[]{
"## 智能词典",
"",
"输入框中支持用**加号**分隔单词中各个组成部分。",
"",
"-   如：输入 citta+kamma",
"",
"其组分将在输入框下方显示，点击搜索框下方的**组分**查询每个组分的意思。",
"",
"点击左侧的词典列表中的**词典名称**，可以进行词条跳转。",
"",
"词典列表下方的**拼写列表**中，穷举了一切存在的**变化形式**以及在语料库中的出现频率。",
"",
"nama",
"后缀",
}},
  {"grammar_my_pl",  new string[]{
"# 缅文语尾",
"",
"- 复数（主/呼）",
}},
  {"grammar_aor",  new string[]{
"## 过去式",
"",
"**动词**变位之一，巴利语中表达过去发生动作的时态。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利||Kālātipatti|",
"|汉|过|过去式|",
"|英|aor.|aorist|",
"",
}},
  {"grammar_1p",  new string[]{
"## 第一人称",
"",
"缩写： 1p",
"",
"动词的一种变化形式。动作的发出者是第一人称（我、我们）。",
}},
  {"grammar_abbr",  new string[]{
"## 语法信息（第3步）",
"- 通过查询**词典源型**可以初步确定部分内容",
"- 之后查询**语尾**可以穷举所有可能的**套餐**",
"- 如果如法确定唯一的**套餐**，则需要[综合分析]()来进行筛查",
"",
"|查询内容|查询结果|第1格|第2格|第3格|第4格|",
"|-|-|-|-|-|-|",
"|词典<br>源型|阳 中 阴|名|阳/中/阴|——|——|",
"|语尾|——|——|取交集|单<br>复|主 宾 具 目的<br>源 属 处 呼|",
"|-|-|-|-|-|-|",
"|词典<br>源型|三性|三性|——|——|——|",
"|语尾|——|——|阳/中/阴|单<br>复|主 宾 具 目的<br>源 属 处 呼|",
"|-|-|-|-|-|-|",
"|词典<br>源型|无信息|动|——|——|——|",
"|语尾|——|——|人称|单<br>复|现 将 过<br>命令 潜 条件|",
}},
  {"library",  new string[]{
}},
  {"grammar_my_inst2",  new string[]{
"# 缅文语尾",
"## 伴随关系",
"sahādiyoga 或 sahatthayoga",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**具**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/instr.html)|表达**连带**关系（有连词）|跟……一起，与……一起|[伴随 ➡ 连词<br>SOE](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-soe.html)|",
"|[**具**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/instr.html)|表达**连带**关系（无连词）|跟……，与……|[伴随 ➡ 动词<br>SOI](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-soi.html)|",
}},
  {"grammar_inst",  new string[]{
"# 工具格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|na|Karaṇa-vacana<br>\\(常见于注释书\\)<br>tatiyā-vibhatti<br>\\(常见于语法书\\)|",
"|汉|**具**|工具格<br>具作格<br>具格<br>第三变格|",
"|英|**inst.**<br>instr.|instrumental case|",
}},
  {"grammar_my_loc1",  new string[]{
"# 缅文语尾",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**处**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/loc.html)|表达**时空背景**关系|在……时<br>在……处|[时空 ➡ 动词<br>LOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-lov.html)|",
"|[宾**格**](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html#%E8%BF%9B%E9%98%B6%E7%94%A8%E6%B3%95)|表达**时空背景**关系|在……时<br>在……处|[时空 ➡ 动词<br>LOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-lov.html)|",
"|[不变]()|表达**时空背景**关系|在……时<br>在……处|[时空 ➡ 动词<br>LOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-lov.html)|",
}},
  {"grammar_sk",  new string[]{
"# 梵语",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——||",
"|汉|**梵**|梵语|",
"|英|**sk.**|Sanskrit|",
}},
  {"grammar_my_gen1",  new string[]{
"# 缅文语尾",
"",
"- 名词：属格/表达从属，……的",
"- 句子结尾：放在首要动词之后",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**属**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/gen.html)|表达**从属关系**|……的|[所有者 ➡ 所属物<br>POS](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/gen/gen-pos.html)|",
"|——|表达句子结尾：放在首要动词之后|——|——|",
}},
  {"grammar_my_loc2",  new string[]{
"# 缅文语尾",
"",
"- 处格/表达动机，因……，旨在……",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**处**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/loc.html)|表达**动机/理由**关系|旨在……<br>因为|[动机 ➡ 动词<br>LOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-mot.html)|",
}},
  {"grammar_my_gen2",  new string[]{
"# 缅文语尾",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**处**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/loc.html)|表达**范围**|……中的|[集合 ➡ 元素<br>COI](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-coi.html)|",
"|[**处**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/loc.html)|表达**范围**|……中的|[整体 ➡ 局部<br>COI](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/loc/loc-whp.html)|",
"|[**属**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/gen.html)|表达**范围**|……中的|[集合 ➡ 元素<br>COI](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/gen/gen-coi.html)|",
}},
  {"SUMMARY",  new string[]{
"# 用户指南",
"",
"* [藏经阁](library.md)",
"  * [查词](dict_search_input.md)",
"  * [强力拆分](comp_split.md)",
"  * [性]",
"    * [阳性](grammar_m.md)",
"    * [阴性](grammar_f.md)",
"    * [中性](grammar_nt.md)",
"  * [数]",
"    * [单数](grammar_sg.md)",
"    * [复数](grammar_pl.md)",
"  * [格]",
"    * [主格](grammar_nom.md)",
"    * [宾格](grammar_acc.md)",
"    * [工具格](grammar_inst.md)",
"    * [目的格](grammar_dat.md)",
"    * [来源格](grammar_abl.md)",
"    * [属格](grammar_gen.md)",
"    * [处格](grammar_loc.md)",
"    * [呼格](grammar_voc.md)",
"* [译经楼](studio.md)",
"  * [整体含义](studio_general_meaning.md)",
"  * [拆分方式](studio_break_down.md)",
"  * [拆分含义](studio_part_meaning.md)",
"  * [语法信息](grammar_abbr.md)",
"  * [词典原型](studio_parent.md)",
"  * [衍生原型](studio_parent2.md)",
"  * [协作消息](studio_message.md)",
"  * [句子编号](sent_func.md)",
"* [圣书院](academy.md)",
"",
"## 下载页",
"如果字体不正常可以下载此开源字体包：",
"百度网盘：[链接](https://pan.baidu.com/s/1LXJ1Tc5IaiaAeJwLm5gajg)   提取码：pali",
}},
  {"sent_trans",  new string[]{
"## 译文输入",
"此处的设计是针对**信达雅**三大翻译指标中的**雅**，即文学性。在词源拆分上满足了**信**，在单词含义上满足了**达**，我们便可以更加自由地追求**雅**。",
"### 操作方法",
"- 视频演示    ",
"  - [YouTube](https://youtu.be/Pd1W0fPi9Ks \"按住Ctrl键点开\")    ",
"  - [优酷](https://v.youku.com/v_show/id_XNDgxMjU5NDIwMA==.html \"按住Ctrl键点开\")",
"- 点击输入框，输入框会自动展开；",
"- 在其中键入文字，输入框上方将自动显示预览；",
"- 当鼠标点击其他地方时（输入框失去焦点），输入框里的内容将自动保存。",
}},
  {"studio_parent",  new string[]{
"## 词典原型（第1步）",
"此处为该处词语在查词时，词典中能够找到数据且符合语法变化的拼写，常用方法有：",
"- 去尾查询法",
"  - 从拼写的最后一个字母开始删除，找到相似度高且被很多词典收录的拼写",
"- 去尾加尾查询法",
"  - 动词去掉变位尾后，加上ti",
"  - 如：karo**ma**的原型写为karoti",
"- 社区词典查询法",
"  - 当上述两种方法无法查到时，则查看社区词典是否有数据",
"",
"[更多内容](https://visuddhinanda.gitbook.io/wikipali-help-zh-hans/v/master/wbw/edit_win)",
}},
  {"grammar_my_abs",  new string[]{
"# 缅文语尾",
"",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**连续**体](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/abl.html)|表达先发生的动作|……完之后|[**前生动词** ➡ 后生动词<br>ADV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-coc.html)|",
"|[动名词](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/verbal/pp.html)|表达先发生的动作|……完之后|[**前生动词** ➡ 后生动词<br>ADV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-coc.html)|",
"|[过去分词](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/verbal/pp.html)|表达先发生的动作|……完之后|[**前生动词** ➡ 后生动词<br>ADV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-coc.html)|",
}},
  {"grammar_imp",  new string[]{
"# 动词命令式",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|āṇatti|",
"|汉|**命令**|命令式<br>祈使语气|",
"|英|**imp.**|imperative mood|",
}},
  {"sent_func",  new string[]{
"## 句子编号功能",
"### 在逐词解析中添加巴利原文注释",
"(文本暂无)",
"- [YouTube](https://youtu.be/phRFoQbAh8s \"按住Ctrl键点开\")",
"- [优酷](https://v.youku.com/v_show/id_XNDgwOTg4OTA0NA==.html \"按住Ctrl键点开\")",
"",
"### 术语百科",
"术语+巴利原文注释",
"- * [YouTube](https://youtu.be/YxVwxYA4spU)",
}},
  {"studio_term",  new string[]{
"## 术语大兼容系统",
"在佛教翻译中，术语使用在历史沿革中一直存在大量争论，这是在纸媒体的时代永远无法解决的。",
"",
"然而在电子阅读时代，这个问题是可以通过兼容的方式，同时照顾**译者**和**读者**两大群体的感受。",
"",
"### 视频演示",
"- [YouTube](https://youtu.be/NdXgxo5YAIo \"按住Ctrl键点开\")",
"- 优酷",
"### 操作方法",
"- 点击逐词解析中的术语",
"- 检查**词典原型**是否为空，如果为空请填入去掉变化之后的能够在词典中查询到的**原型**",
"- 点击页面右上角的<svg id=\"icon_term\" viewBox=\"0 0 24 24\" style='fill:#6baaff;height: 15px; width: 15px;'><path d=\"M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z\"></path></svg>调出侧边栏",
"- 点击**新建**按钮，在其中键入**首选术语**(必填)，其他为选填",
"- 之后，在键入译文的时候，如下：",
"```",
"[[isipatana]] [[migadāya]]：由仙人们起飞和降落而得名。由于给予[[miga]]安全感，而划定为[[migadāya]]的区域。",
"```",
"<b>[[pāḷi]]</b>会被自动替换，最终显示为：",
"```",
"落仙坪(isipatana 仙人降落处,仙人堕处,仙人落处 ) 野生保护(区)(migadāya 鹿野苑 )：由仙人们起飞和降落而得名。由于给予野兽(miga 鹿,野生动物 )安全感，而划定为野生保护(区)的区域。",
"```",
"注：该替换优先依照读者的个性化术语系统",
}},
  {"grammar_pref",  new string[]{
"# 前缀",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|upasagga|",
"|汉|**前缀**|绝对体<br>连续<br>不变分词|",
"|英|**pref.**|prefix|",
}},
  {"academy",  new string[]{
"## 圣书院",
}},
  {"grammar_my_dat1",  new string[]{
"# 缅文语尾",
"## 目标对象",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**目的**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/dat.html)|表达**动作的目标对象**<br>相当于英语“to”|向……，对……来说|[接受者 ➡ 动词<br>REC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/dat/dat-rec.html)|",
}},
  {"grammar_verb",  new string[]{
"# 动词",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|kri|kriyā|",
"|汉|**动**|动词|",
"|英|**v.**|verb|",
}},
  {"grammar_my_time",  new string[]{
"# 缅文语尾",
"",
"表示持续一段时间",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**宾**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|表达**持续**一段时间/空间|经过……|[时空连续性<br>STC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-stc.html)|",
"|副词|表达**持续**一段时间/空间|经过……|[时空连续性<br>STC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-stc.html)|",
}},
  {"grammar_adv",  new string[]{
"# 副词",
"",
"不变词的一种。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|karaṇattha|",
"|汉|**副**|副词|",
"|英|**adv.**|Adverbial|",
}},
  {"grammar_caus",  new string[]{
"# 使役",
"",
"表示A令B做……",
}},
  {"grammar_fr",  new string[]{
"# 来自",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|——|",
"|汉|**来自**|来自|",
"|英|**fr.**|from|",
"",
"此词由另一个词演变而来。",
}},
  {"grammar_ti",  new string[]{
"# 三性词",
"这种词没有固定的性，即可能是阳性，也可能是中性，也可能是阴性；它的性会跟随它修饰的词而变化。",
"包含内容：形容词、[动词分词](https://visuddhinanda.gitbook.io/pali-handbook/verbal/participle)、代词、数词",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|ti|tiliṅga|",
"|汉|**三性**|三性词<br>形容词|",
}},
  {"grammar_pp",  new string[]{
"## 过去分词",
"表达**过去**动作含义的**三性词**/形容词，已……的，",
">例句：这是一杯**已煮过的**牛奶。",
"",
"常用后缀：-ta, -na",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|——|",
"|汉|**过分**|过去分词<br>完成分词|",
"|英|**pp.**|Past Participle<br>Perfect Participle|",
}},
  {"grammar_my_abl1",  new string[]{
"# 缅文语尾",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[来**源**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/abl.html)|表达来源|从……|[**来源** ➡ 动词<br>DET](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-det.html)|",
}},
  {"grammar_sg",  new string[]{
"# 单数",
"",
">ekassatthassa vacanaṃ ekavacanaṃ.——“Saddanītippakaraṇaṃ”",
">表示“一个”含义的用语，为单数。——《论语法》",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|**eka**|ekavacana|",
"|汉|**单**|**单数**|",
"|英|**sg.**<br>**s.**|singular|",
}},
  {"grammar_adj",  new string[]{
"# 形容词",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|||",
"|汉|形|形容词|",
"|英|adj.|adjective|",
"",
"巴利传统语法中常使用**三性词**来代表形容词在内的词",
}},
  {"grammar_my_acc2",  new string[]{
"# 缅文语尾",
"",
"- 修饰动词，起到副词作用",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**宾**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|用于修饰动词|……地|[副词 ➡ 动词<br>ADV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-adv.html)|",
"|副词|用于修饰动词|……地|[副词 ➡ 动词<br>ADV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-adv.html)|",
}},
  {"comp_split",  new string[]{
"## 复合词强力拆分",
"",
"点击此按钮可以拆分长复合词",
"1. 基于AI算法，我们给出**可能性**最高的拆分结果。",
"2. 点击拆分结果后面的**数字**可以显示可能的拆分列表。",
"3. 用户可以通过点击**每个组分**来进行字典查询。",
}},
  {"grammar_my_abl3",  new string[]{
"# 缅文语尾",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[来**源**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/abl.html)|表达**比较**|比……少|[**参照** ➡ 比较级<br>COC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-coc.html)|",
}},
  {"grammar_my_nom3",  new string[]{
"# 缅文语尾",
"",
"- 主格/主语",
}},
  {"power_set",  new string[]{
"# 隐私与权限",
"",
"|权限级别|私享|公开|应用范例|",
"|-|-|-|-|",
"|无|不可见|查看<br>提建议|陌生读者<br>开源协作|",
"|只读|查看<br>提建议|查看<br>提建议|上课学员<br>尝鲜试读|",
"|修改|查看<br>修改|查看<br>修改|审稿人<br>校对者<br>协作者<br>润色者|",
"|拥有者|查看<br>修改<br>设权限|查看<br>修改<br>设权限|——|",
}},
  {"studio_case_fomular",  new string[]{
"### 虚词公式",
"- 我们在本行的",
"<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>",
"    中列举了与该**语法信息**相应的虚词公式",
"- 如果对自动套用的虚词公式不满意，可用从<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>中选择。",
"- 自动给出的公式显示为<span style='color:#BD8B18;'>金黄色</span>，且该公式不会进入[个人单词本](./setting.php?item=userdict)",
"- 手动选择的公式显示为<span style='color:#f9468f;'>粉红色</span>，且该公式会进入[个人单词本](./setting.php?item=userdict)",
"- 通过**虚词公式**可以加深我们对语法概念的理解",
"- 初学者也可以透过调整**语法信息**和**虚词公式**来实现**格位**、**变位**的抉择",
}},
  {"grammar_my_acc1",  new string[]{
"# 缅文语尾",
"",
"- 宾语",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**宾**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|表达**受动者**|把……|[受动者 ➡ 动词<br>IOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-iov.html)|",
"|[**宾**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|表达主动语态的**双宾语**|使**A**变成B|[受动者·主 ➡ 动词<br>DIO-P](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-dio.html#dio-p)|",
"|[**宾**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/acc.html)|表达**主动**语态的**双宾语**|使A变成**B**|[受动者·次 ➡ 动词<br>DIO-S](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/acc/acc-dio.html#dio-s)|",
"|[**主**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**被动**语态**双宾语**|**A**被弄成B|[被动者·主 ➡ 被动动词<br>DAO-P](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/nom/nom-dao.html)|",
"|[**主**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**被动**语态**双宾语**|A被弄成**B**|[被动者·次 ➡ 被动动词<br>DAO-P](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/nom/nom-dao.html)|",
"|[**主**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**被动者**|被……|[被动者 ➡ 被动动词<br>AOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/nom/nom-aov.html)|",
"|[**属**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/nom.html)|表达**被动者**|……的|[受动者 ➡ 动词<br>IOV](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/gen/gen-iov.html)|",
}},
  {"grammar_abl",  new string[]{
"# 来源格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|Nissakka-vacana\\(常见于注释书\\)<br>pañcamī-vibhatti\\(常见于语法书\\)|",
"|汉|**来源**|来源格<br>离格<br>夺格<br>从格<br>第五变格|",
"|英|**abl.**|ablative case|",
"",
"## 常见用法：",
">表达动作之**所由**",
">1. 表达动作的**起点**：从**何处**发生",
">2. 表达动作发生的**原因、起源**：从**何因**发生 ",
">>——《简明实用文法》",
}},
  {"grammar_m",  new string[]{
"# 阳性",
"- 如果在查**词典源型**时出现，则代表该**词**的语法信息中应选择**名词**&**阳性**",
"- 如果在查**语尾**时出现，则代表该**语尾**有应用在**阳性词**中的可能性",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|**pu**|puma<br>pumaliṅga<br>pulliṅga|",
"|汉|**阳**|**阳性**|",
"|英|**m.**|masculine|",
"",
"**名词**、**三性词**所具有的属性之一，谓语动词和不变词不具有性",
}},
  {"studio_break_down",  new string[]{
"## 拆分信息（第2步）",
"- 简单拆分：**词典源型**+[语尾]",
">通过查询**词典源型**的拆分方法，可以探索到更复杂的拆分方式，用户可以根据自己的意愿，决定把单词拆解到什么样的复杂度。",
"- 如果用加号“**+**”分隔每个组分，机器会自动识别并查询相应的组分",
">如果用“**-**”分隔则没有相应的效果。",
"",
"巴利语拆分是从词源入手进行语义解析的重要手段，",
"",
"[更多内容](https://visuddhinanda.gitbook.io/wikipali-help-zh-hans/v/master/wbw/edit_win)",
}},
  {"grammar_my_inst3",  new string[]{
"# 缅文语尾",
"",
"表示原因，有以下可能：",
"",
"|可能的情况|翻译建议|",
"|-|-|",
"|[工**具**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/instr/instr-cau.html)|根据……|",
"|[来**源**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/abl/abl-cau.html)|由于……|",
"|[引号**iti**](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/other/iti.html#%E5%8E%9F%E5%9B%A0%E7%8A%B6%E8%AF%ADcausative-particle)|因为……|",
"|[**连续**体](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/verb/ger.html#%E4%BE%8B%E5%8F%A53)|基于……|",
}},
  {"grammar_vism",  new string[]{
"# 清净道论",
"",
"|语种|全称|",
"|-|-|",
"|巴利|Vism.|visuddhimagga|",
"|汉|清净道论<br>清净之道|",
"|英|Path of Purification|",
}},
  {"studio_general_meaning",  new string[]{
"## 整体意思与虚词公式（第5步）",
"在这里输入的含义，会被系统自动根据**语法信息**来套用**虚词公式**，因此不建议大家填入带有格位虚词的含义，而是通过虚词选择公式来进行。",
"",
"范例：",
"",
"|pāli|不兼容的写法|兼容的写法|",
"|-|-|-|",
"|pabbajit**ena**|被出家人|出家人<br>[被]出家人|",
"|anāthapiṇḍika**ssa**|给孤独长者的|给孤独长者<br>给孤独长者[的]|",
"  ",
"[更多内容](https://visuddhinanda.gitbook.io/wikipali-help-zh-hans/v/master/wbw/edit_win)",
}},
  {"grammar_consonant",  new string[]{
"# 辅音",
"又名子音。",
"",
"子音语尾语基，即在**词典源型**中的结尾为以下几种情况：",
"* -ant",
"* -ar",
"* -as",
"* -in",
"* -an",
}},
  {"grammar_vinaya",  new string[]{
"# 律藏",
}},
  {"grammar_bsk",  new string[]{
"# 佛教梵语",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|——|",
"|汉|——|佛教梵语|",
"|英|**bsk.**|Bodhist Sanskrit|",
}},
  {"studio_part_meaning",  new string[]{
"## 拆分含义（第4步）",
"此处的设计是针对**信达雅**三大翻译指标中的**信**，即学术严谨性，可以通过拆分和拆分含义，实现词源学的探索。",
"",
"在**拆分方式**中用加号+将巴利拼写分隔之后，系统会根据每个组分的拼写进行自动查询",
"",
"[更多内容](https://visuddhinanda.gitbook.io/wikipali-help-zh-hans/v/master/wbw/edit_win)",
}},
  {"readme",  new string[]{
}},
  {"grammar_my_nom2",  new string[]{
"# 缅文语尾",
"",
"- 主格/主语",
}},
  {"grammar_opt",  new string[]{
"# 潜能式",
"",
"**动词**变位之一，表示可能发生的动作。",
"常用语虚拟语气。",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——|parikappa|",
"|汉|潜|潜能式<br>愿望式<br>祈愿式|",
"|英|Opt.|Optative Tense|",
"",
"",
}},
  {"grammar_dat",  new string[]{
"# 目的格",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|sa|Sampadāna-vacana\\(常见于注释书\\)<br>catutthī-vibhatti\\(常见于语法书\\)|",
"|汉|**目的**|目的格<br>与事格<br>与格<br>为格<br>第四变格|",
"|英|**dat.**|dative case|",
}},
  {"grammar_pron",  new string[]{
"# 代词",
}},
  {"grammar_my_dat2",  new string[]{
"# 缅文语尾",
"",
"## 目的",
"",
"|格位|含义|翻译建议|关系|",
"|-|-|-|-|",
"|[**目的**格](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/declension/dat.html)|表达**动作的目的**<br>相当于英语“for”|为了……|[目的 ➡ 动词<br>REC](https://assets-hk.wikipali.org/pali-handbook/zh-Hans/basic-relation/dat/dat-rec.html)|",
}},
};

    public static Dictionary<string, string[]> grammar_en = new Dictionary<string, string[]>(){
  {"grammar_nt",  new string[]{
"# neuter gender",
"pāḷi：napuṃsaka",
}},
  {"grammar_acc",  new string[]{
"# accusative case",
"pāḷi：upayogavacana",
"```",
"Upayogavacanaṃ nāma yo yaṃ karoti, tena tadupayuttaparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"studio_part_meaning",  new string[]{
"## 拆分含义",
"此处的设计是针对**信达雅**三大翻译指标中的**信**，即学术严谨性，可以通过拆分和拆分含义，实现词源学的探索。",
"",
"在**拆分方式**中用加号“+”将巴利拼写分隔之后，系统会根据每个组分的拼写进行自动查询",
"",
"查询结果的第一个会显示，其他结果在下拉菜单中",
"",
"点击<svg viewBox=\"0 0 24 24\" id=\"ic_vertical_align_top\" style='fill:#6baaff;height: 12px; width: 20px;'><path d=\"M8 11h3v10h2V11h3l-4-4-4 4zM4 3v2h16V3H4z\"></path></svg>按钮可以将未 **[括起来]** 的部分覆盖到 **整体含义** 来实现快捷输入",
"",
"如果对译文不满意，可以点击<svg viewBox=\"0 0 24 24\" id=\"ic_mode_edit\" style='fill:#6baaff;height: 12px; width: 20px;'><path d=\"M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04a.996.996 0 0 0 0-1.41l-2.34-2.34a.996.996 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z\"></path></svg>按钮来手动修改译文",
"- 注意保证**拆分含义**的“+”和**拆分方式**中的“+”数量保持一致",
"- 如果**拆分含义**的“+”数量小于**拆分方式**中的“+”，那么系统将自动填充 **↓↓** 来提示用户查看此处的下拉菜单",
"- 如果**拆分含义**的“+”数量大于**拆分方式**中的“+”，那么系统将自动把最后两个组分含义合并",
"  ",
"## 个人单词本",
"拆分方式和拆分含义在进入[单词本](./setting.php?item=userdict)的时候，会在基础单词数据块的基础上，增加和拆分数目相同的单词数据块",
"",
"- 内容会被简化为拼写+含义，语法类型代码为**待定组分**",
"- 比如：attha+saṃhita 义+已携带，会增加2条单词数据到[单词本](./setting.php?item=userdict)",
"",
"| 拼写    | 含义   | 类型     |",
"| ------- | ------ | -------- |",
"| attha   | 义     | 待定组分 |",
"| saṃhita | 已携带 | 待定组分 |",
}},
  {"sent_func",  new string[]{
"## Sentence numbering function",
"### Add Pāḷi as comment in word-by-word analysis",
"Vedio as below (No text yet)",
"- [YouTube](https://youtu.be/phRFoQbAh8s \"Press Ctrl and Click On\")",
"- [优酷](https://v.youku.com/v_show/id_XNDgwOTg4OTA0NA==.html \"Press Ctrl and Click On\")",
"- [百度网盘](https://pan.baidu.com/s/1Vs0evu9q6np1l8GRU9auug \"Press Ctrl and Click On\") 提取码：pali",
}},
  {"grammar_abbr",  new string[]{
"## Basic Operations",
"- Fill syntax information by selecting the drop-down list",
"- First, select the type with outline, such as: verb",
"- Then, select the following content, such as: **3p sg. pres.**",
"- For the above-mentioned **syntax abbreviations**, please refer to the following table",
"- Adjust **grammatical information** and **function word formula** to list the possible meanings of this word",
"- Find out the optimal solution",
"",
"## Splitting of Slur",
"The tutorial of splitting a slur word (unavailable)",
"",
"##  Splitting of Compound Word",
"The tutorial of splitting compound word (text not yet available)",
"- [YouTube](https://youtu.be/iN1t0Rq9aKk \"Press Ctrl and Click On\")  ",
"- [优酷](https://v.youku.com/v_show/id_XNDgwOTg4NDQ4MA==.html \"Press Ctrl and Click On\")",
"- [百度网盘](https://pan.baidu.com/s/1nXZG2GQkkkfblNnshDuS_w \"Press Ctrl and Click On\")  提取码：pali ",
"",
"## grammatical abbr. list",
"| 缩略语   | abbr.     | note                         |",
"| :------- | :-------- | :--------------------------- |",
"| 名       | n.        | noun                         |",
"| 动       | v.        | verb                         |",
"| 三性     | n.a.      | three genders.               |",
"| 形       | adj.      | 形容词                       |",
"| 不变     | ind.      | indeclinable (nipāta)        |",
"| 代       | pron.     | pronoun                      |",
"| 动不变   | v. ind.   | indeclinable (-tvā, sighaṃ)  |",
"| 数       | num.      | numerals                     |",
"| 黏音     | slur.     | sandhi                       |",
"| 复合     | comp.     | compound(samāsa)             |",
"| 代词干   | pron:base | amha                         | amhākaṃ |",
"| 三性词干 | ti:base   | gacchanta mahallaka          |",
"| 形词干   | adj:base  | mahallaka 传统分类归属三性词 |",
"| 名词干   | n:base    | gāma                         |",
"| 数词干   | num:base  | ti                           |",
"| 前缀     | prefix    | na-, vi-, saṃ-               |",
"| 词根     | root      | gamu                         |",
"| 后缀     | suffix    | (-ika, -ana, -tā)            |",
"| 语尾     | case end  | vibhatti (-ena, -ehi)        |",
"| 动原型   | v:base    | karo(ti) gaccha(ti)          |",
"| 原版注释 | note      | sī sya                       |",
}},
  {"grammar_loc",  new string[]{
"# locative case",
"pāḷi：bhummavacana",
"```",
"Bhummavacanaṃ nāma tappatiṭṭhāparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"grammar_f",  new string[]{
"# feminine gender",
"pāḷi：itthī",
}},
  {"term_pedia_sys",  new string[]{
"## 术语百科系统",
"术语+注释书名词解释=巴利百科词条",
"### 视频演示",
"",
"",
"### 具体操作",
"* 首先创建术语",
"* 然后复制句子编号",
"* 将句子编号黏贴到下面的输入框中",
"* 系统会自动根据句子编号，返回巴利原文、译文以及引用路径",
}},
  {"grammar_inst",  new string[]{
"# instrumental case",
"pāḷi：karaṇavacanaṃ",
"```",
"Karaṇavacanaṃ nāma tajjāpakatanibbattakaparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"comp_split",  new string[]{
"## Turbo Split for Samāsa",
"",
"long spelling pāḷi samāsa(compound word) can be easily splited by clicking this botton.",
"",
"1. basing on AI tech, we calculate the **possibility** and show the highest one.",
"2. The **number** followed the factors can be clicked to show the possible list.",
"3. User can click **each factor** to look up the dictionary. ",
}},
  {"studio_break_down",  new string[]{
"## Split method",
"Pali language segmentation is an important means of semantic analysis starting from etymology.",
"",
"Users can decide to dismantle the words to what extent they wish.",
"",
"If the plus sign \"+\" to separate each component, the machine will automatically identify and find the respective components.",
"",
"If the word is tonal (sandhi) it can be further disassembled and analyzed separately.",
"",
"If you are not sure how to split, there are several channels to choose from:",
"- Word query by clicking",
"  - Click on a word, Opening the <svg id=\"icon_dict\" viewBox=\"0 0 32 32\" style='fill:#6baaff;height: 10px; width: 15px;'><g transform=\"translate(-4 -4)\"><path class=\"a\" d=\"M24.4,2,17.9,7.85v14.3l6.5-5.85V2M8.15,5.9A12.09,12.09,0,0,0,1,7.85V26.908a.7.7,0,0,0,.65.65c.13,0,.195-.091.325-.091A15.85,15.85,0,0,1,8.15,26.05,12.09,12.09,0,0,1,15.3,28a15.659,15.659,0,0,1,7.15-1.95,13.241,13.241,0,0,1,6.175,1.378.565.565,0,0,0,.325.039.7.7,0,0,0,.65-.65V7.85A8.867,8.867,0,0,0,27,6.55V24.1a15.106,15.106,0,0,0-4.55-.65A15.659,15.659,0,0,0,15.3,25.4V7.85A12.09,12.09,0,0,0,8.15,5.9Z\" transform=\"translate(5 4)\"></path></g></svg> in the upper right corner will display dictionary lookup results.",
"  - Many long words can be found in the Pali-Myanmarese dictionary (three in total).",
"- **Turbo Split** function",
"- Ask the teacher",
}},
  {"studio",  new string[]{
}},
  {"library",  new string[]{
}},
  {"studio_general_meaning",  new string[]{
"## Overall meaning and function word formula",
"The meaning entered here will be automatically applied by the system according to the **grammatical information** **function word formula**;",
"### Word query",
"- Click on a word",
"- Open<svg id=\"icon_dict\" viewBox=\"0 0 32 32\" style='fill:#6baaff;height: 10px; width: 15px;'><g transform=\"translate(-4 -4)\"><path class=\"a\" d=\"M24.4,2,17.9,7.85v14.3l6.5-5.85V2M8.15,5.9A12.09,12.09,0,0,0,1,7.85V26.908a.7.7,0,0,0,.65.65c.13,0,.195-.091.325-.091A15.85,15.85,0,0,1,8.15,26.05,12.09,12.09,0,0,1,15.3,28a15.659,15.659,0,0,1,7.15-1.95,13.241,13.241,0,0,1,6.175,1.378.565.565,0,0,0,.325.039.7.7,0,0,0,.65-.65V7.85A8.867,8.867,0,0,0,27,6.55V24.1a15.106,15.106,0,0,0-4.55-.65A15.659,15.659,0,0,0,15.3,25.4V7.85A12.09,12.09,0,0,0,8.15,5.9Z\" transform=\"translate(5 4)\"></path></g></svg>on the upper right corner",
"- Dictionary query results will be displayed on the right sidebar",
"",
"Mouse over <svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg> at the end of the line, the meaning list of system matching can be showed which can realize the quick input by clicking.",
"",
"Tips：",
"- translator's dictum of fidelity, clarity and elegance",
"- The design here is aimed at **clarity** in the three translator's dictum which contains **fidelity**, **clarity** and **elegance**, which is to give priority to the pursuit of clarity of meaning.",
"- Alexander Fraser Tytler",
"- 此处的设计是针对**信达雅**三大翻译指标中的**达**，即优先追求含义表达的明确性",
"- 对于词源学我们设计了**拆分方式**与**拆分含义**",
"- 文学优美性我们提供了**整体译文**",
"- **虚词公式**可能会有遗漏，如有补充，欢迎通过此[链接](https://github.com/iapt-platform/mint/issues/20)给我们留言。",
}},
  {"grammar_voc",  new string[]{
"# 呼格",
"pāḷi：āmantanavacana",
"```",
"Āmantanavacanaṃ nāma tadāmantanaparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"grammar_dat",  new string[]{
"# dative case",
"pāḷi：sampadānavacana",
"```",
"Sampadānavacanaṃ nāma tappadānaparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"grammar_gen",  new string[]{
"# genitive case",
"pāḷi：sāmivacana",
"```",
"Sāmivacanaṃ nāma tadissaraparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"grammar_abl",  new string[]{
"# ablative case",
"pāḷi：nissakkavacana，",
"```",
"Nissakkavacanaṃ nāma tannissaṭatadapagamaparidīpanattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"dict_search_input",  new string[]{
"## Smart Dictionary",
"",
"You can type the plus **（+）** in the input-box between parts in the compone word, and than click one part (under the search input) lookup dictionary.",
"",
"- Example：citta+kamma",
"",
"Each factor will be show under the input-box, **each factor** can be clicked to be looked up in the dictionary.",
"",
"The list on the left will list the **name of dictionary**, which can be clicked and jump.",
"",
"The **word list** below the dictionary list contains all the existed exhaustive declension of this word and their frequencies in the whole Pāli Literature.",
}},
  {"channel_guide",  new string[]{
"## What is channel?",
"",
"While we learning or translating some certain part of pāḷi text, we need to write down something, EX: translation, class note, commentaries, etc.",
"we need to mark two properties of these appended text - **language** & **type**",
"this we call **channel**.",
"",
"By the channel function, we can realize the **multi-language** and **multi-type**, EX: ",
"- grammatical translation",
"- commentaries",
"- speech text",
"- 巴利直译",
"",
"These **channels** will be display in such way:",
">name-language@nickname",
"",
">grammatical translation-en@Bhikkhu Kosalla",
"",
"There must be some other usage to be developed by the smart users like you.",
}},
  {"SUMMARY",  new string[]{
}},
  {"markdown_guide",  new string[]{
"# Translation Guide for **Typing**",
"[Syntax in detail](https://www.markdownguide.org/basic-syntax/)",
"## Font Style",
"",
"|typing in|display|",
"|-|-|",
"|`[[pāḷi]]`|[term<sub>1</sub>]()(pāḷi, term<sub>2</sub>)|",
"|`**bold**`|**bold**|",
"|`*italic*`|*italic*|",
"|`***bold Italic***`|***bold Italic***|",
"|`~~strikethrough~~`|~~strikethrough~~|",
"|`[link to wikipali](www.wikipali.org \"commentary&#10;note\")`|[link to wikipali](www.wikipali.org \"commentary&#10;note\")|",
"---",
"## paragraph style",
"",
"<div style=\"display:flex;\">",
"",
"<div style=\"flex:1;margin-right:1em;\">",
"",
"### **typing**",
"```",
"single enter no wrap",
"double enter ",
"",
"wrap",
"",
"---",
"before Horizontal Rules--- need empty line",
"```",
"</div>",
"<div style=\"flex:1;\">",
"",
"### **display**",
"",
"single enter no wrap",
"double enter ",
"",
"wrap",
"",
"---",
"before Horizontal Rules--- need empty line",
"</div></div>",
}},
  {"title_search_index",  new string[]{
"# Pali Canon Title Searching",
}},
  {"studio_parent",  new string[]{
"## 词典原型",
"此处为该处词语在查词时应该查询的拼写，通常是：",
"- 动词去掉变位后，加上ti",
"  - 如：karoma的原型写为karo(ti)",
"- 名词、三性词去掉变格",
"  - cittena的原型为citta",
"",
"正确输入词典原型，会在个人单词本中加入原型数据，利用该原型数据可以对其他变化词给出相对准确的含义。",
"- 例如：cittena的**词典原型**中输入了citta，当以后遇到cittehi，cittāni会优先给出个人单词本中citta的数据。",
"",
"但如果是复合词拆分之后的组件，可以写衍生词的原型",
"- karonta的原型为karo(ti)",
"",
"",
"註：",
"- 针对多层级变化衍生的关系，比如从词根到词干，动词到分词，分词到变格；我们不建议在此处进行多层级拆解",
"- 我们设计了另一个强大的工具来实现**词源学探索的终极解决方案**——wordmap",
"- 该wordmap工具在离线版的试验中可用，线上版有待恢复和重新设计",
}},
  {"sent_trans",  new string[]{
"## 译文输入",
"此处的设计是针对**信达雅**三大翻译指标中的**雅**，即文学性。在词源拆分上满足了**信**，在单词含义上满足了**达**，我们便可以更加自由地追求**雅**。",
"### 操作方法",
"- 点击输入框，输入框会自动展开；",
"- 在其中键入文字，输入框上方将自动显示预览；",
"- 当鼠标点击其他地方时（输入框失去焦点），输入框里的内容将自动保存。",
"## 术语大兼容系统",
"在佛教翻译中，术语使用在历史沿革中一直存在大量争论，这是在纸媒体的时代永远无法解决的。",
"",
"然而在电子阅读时代，这个问题是可以通过兼容的方式，同时照顾**译者**和**读者**两大群体的感受。",
"### 操作方法",
"- [视频链接]",
"- 点击逐词解析中的术语",
"- 检查**词典原型**是否为空，如果为空请填入去掉变化之后的能够在词典中查询到的**原型**",
"- 点击页面右上角的<svg id=\"icon_term\" viewBox=\"0 0 24 24\" style='fill:#6baaff;height: 15px; width: 15px;'><path d=\"M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z\"></path></svg>调出侧边栏",
"- 点击**新建**按钮，在其中键入**首选术语**(必填)，其他为选填",
"- 之后，在键入译文的时候，如下：",
"```",
"[[isipatana]] [[migadāya]]：由仙人们起飞和降落而得名。由于给予[[miga]]安全感，而划定为[[migadāya]]的区域。",
"```",
"<b>[[pāḷi]]</b>会被自动替换，最终显示为：",
"```",
"落仙坪(isipatana 仙人降落处,仙人堕处,仙人落处 ) 野生保护(区)(migadāya 鹿野苑 )：由仙人们起飞和降落而得名。由于给予野兽(miga 鹿,野生动物 )安全感，而划定为野生保护(区)的区域。",
"```",
"注：该替换优先依照读者的个性化术语系统",
}},
  {"grammar_sg",  new string[]{
"# singular",
"pāḷi：ekavacana",
"```",
"ekassatthassa vacanaṃ ekavacanaṃ.——“Saddanītippakaraṇaṃ”",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"grammar_pl",  new string[]{
"# plural",
"pāḷi：bahuvacana",
"```",
"Bahūnamatthānaṃ vacanaṃ bahuvacanaṃ.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"studio_term",  new string[]{
"## 术语大兼容系统",
"在佛教翻译中，术语使用在历史沿革中一直存在大量争论，这是在纸媒体的时代永远无法解决的。",
"",
"然而在电子阅读时代，这个问题是可以通过兼容的方式，同时照顾**译者**和**读者**两大群体的感受。",
"",
"### 视频演示",
"- [YouTube](https://youtu.be/NdXgxo5YAIo \"按住Ctrl键点开\")",
"- 优酷",
"### 操作方法",
"- 点击逐词解析中的术语",
"- 检查**词典原型**是否为空，如果为空请填入去掉变化之后的能够在词典中查询到的**原型**",
"- 点击页面右上角的<svg id=\"icon_term\" viewBox=\"0 0 24 24\" style='fill:#6baaff;height: 15px; width: 15px;'><path d=\"M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z\"></path></svg>调出侧边栏",
"- 点击**新建**按钮，在其中键入**首选术语**(必填)，其他为选填",
"- 之后，在键入译文的时候，如下：",
"```",
"[[isipatana]] [[migadāya]]：由仙人们起飞和降落而得名。由于给予[[miga]]安全感，而划定为[[migadāya]]的区域。",
"```",
"<b>[[pāḷi]]</b>会被自动替换，最终显示为：",
"```",
"落仙坪(isipatana 仙人降落处,仙人堕处,仙人落处 ) 野生保护(区)(migadāya 鹿野苑 )：由仙人们起飞和降落而得名。由于给予野兽(miga 鹿,野生动物 )安全感，而划定为野生保护(区)的区域。",
"```",
"注：该替换优先依照读者的个性化术语系统",
}},
  {"studio_case_fomular",  new string[]{
"### 虚词公式",
"- 我们在本行的",
"<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>",
"    中列举了与该**语法信息**相应的虚词公式",
"- 如果对自动套用的虚词公式不满意，可用从<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>中选择。",
"- 自动给出的公式显示为<span style='color:#BD8B18;'>金黄色</span>，且该公式不会进入[个人单词本](./setting.php?item=userdict)",
"- 手动选择的公式显示为<span style='color:#f9468f;'>粉红色</span>，且该公式会进入[个人单词本](./setting.php?item=userdict)",
"- 通过**虚词公式**可以加深我们对语法概念的理解",
"- 初学者也可以透过调整**语法信息**和**虚词公式**来实现**格位**、**变位**的抉择",
}},
  {"grammar_nom",  new string[]{
"# nominative case",
"pāḷi：paccattavacana",
"```",
"Tatra paccattavacanaṃ nāma tividhaliṅgavavatthānagatānaṃ itthipumanapuṃsakānaṃ paccattasabhāvaniddesattho.",
"```",
"——<u>*Saddanītippakaraṇaṃ*</u>",
}},
  {"studio_message",  new string[]{
"## 消息功能",
"通过消息功能，实现翻译的网络协作。",
"",
"只有具备**共享属性**的文档，才可以发消息。",
"",
"逐词译、译文的每次修改，都会发消息给协作者",
"",
"数据合并逻辑：",
"- 用户数据大体包括四种状态",
"  - 用户**手动**修改",
"  - 他人**消息**推动",
"  - 机器**自动**匹配",
"  - 新经文中的**未填充**部分",
"- 覆盖逻辑",
"  - 手动>消息>自动>未填充",
"-  未能覆盖则在改数据位置上显示<span style=\"color:#f9468f\">消息数量</span>提示",
}},
  {"power_set",  new string[]{
"# Private & Power",
"|Power Level|Private|Public|Towards to|",
"|-|-|-|-|",
"|none|invisible|read<br>suggest|guests<br>open distributors|",
"|Read Only|read<br>suggest|read<br>suggest|students<br>test-reader|",
"|Read & Write|read<br>write|read<br>write|proof reader<br>reviser<br>collaborator<br>polisher|",
"|Owner|read<br>write<br>power set|read<br>write<br>power set|——|",
}},
  {"readme",  new string[]{
}},
  {"grammar_m",  new string[]{
"# masculine gender",
"pāḷi：puma",
}},
  {"academy",  new string[]{
}},
  {"studio_parent2",  new string[]{
"## 衍生原型",
"范例：",
"- 拼写：karontassa",
"- 词典原型：karonta（现代分词）",
"- 此处：karo(ti)",
"- 下拉菜单选择：prp（现代分词）",
}},
};
    public static Dictionary<string, string[]> grammar_tw = new Dictionary<string, string[]>(){
  {"grammar_ind",  new string[]{
"# 不变词",
}},
  {"power_set",  new string[]{
"# 隱私與許可權",
"",
"|許可權級別|私享|公開|應用範例|",
"|-|-|-|-|",
"|無|不可見|檢視<br>提建議|陌生讀者<br>開源協作|",
"|只讀|檢視<br>提建議|檢視<br>提建議|上課學員<br>嚐鮮試讀|",
"|修改|檢視<br>修改|檢視<br>修改|審稿人<br>校對者<br>協作者<br>潤色者|",
"|擁有者|檢視<br>修改<br>設許可權|檢視<br>修改<br>設許可權|——|",
}},
  {"studio_message",  new string[]{
"## 訊息功能",
"通過訊息功能，實現翻譯的網路協作。",
"",
"只有具備**共享屬性**的文件，才可以發訊息。",
"",
"逐詞譯、譯文的每次修改，都會發訊息給協作者",
"",
"資料合併邏輯：",
"- 使用者資料大體包括四種狀態",
"  - 使用者**手動**修改",
"  - 他人**訊息**推動",
"  - 機器**自動**匹配",
"  - 新經文中的**未填充**部分",
"- 覆蓋邏輯",
"  - 手動>訊息>自動>未填充",
"-  未能覆蓋則在改資料位置上顯示<span style=\"color:#f9468f\">訊息數量</span>提示",
}},
  {"sent_trans",  new string[]{
"## 譯文輸入",
"此處的設計是針對**信達雅**三大翻譯指標中的**雅**，即文學性。在詞源拆分上滿足了**信**，在單詞含義上滿足了**達**，我們便可以更加自由地追求**雅**。",
"### 操作方法",
"- 點選輸入框，輸入框會自動展開；",
"- 在其中鍵入文字，輸入框上方將自動顯示預覽；",
"- 當滑鼠點選其他地方時（輸入框失去焦點），輸入框裡的內容將自動儲存。",
"## 術語大相容系統",
"在佛教翻譯中，術語使用在歷史沿革中一直存在大量爭論，這是在紙媒體的時代永遠無法解決的。",
"",
"然而在電子閱讀時代，這個問題是可以通過相容的方式，同時照顧**譯者**和**讀者**兩大群體的感受。",
"### 操作方法",
"- [視訊連結]",
"- 點選逐詞解析中的術語",
"- 檢查**詞典原型**是否為空，如果為空請填入去掉變化之後的能夠在詞典中查詢到的**原型**",
"- 點選頁面右上角的<svg id=\"icon_term\" viewBox=\"0 0 24 24\" style='fill:#6baaff;height: 15px; width: 15px;'><path d=\"M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z\"></path></svg>調出側邊欄",
"- 點選**新建**按鈕，在其中鍵入**首選術語**(必填)，其他為選填",
"- 之後，在鍵入譯文的時候，如下：",
"```",
"[[isipatana]] [[migadāya]]：由仙人們起飛和降落而得名。由於給予[[miga]]安全感，而劃定為[[migadāya]]的區域。",
"```",
"<b>[[pāḷi]]</b>會被自動替換，最終顯示為：",
"```",
"落仙坪(isipatana 仙人降落處,仙人墮處,仙人落處 ) 野生保護(區)(migadāya 鹿野苑 )：由仙人們起飛和降落而得名。由於給予野獸(miga 鹿,野生動物 )安全感，而劃定為野生保護(區)的區域。",
"```",
"注：該替換優先依照讀者的個性化術語系統",
}},
  {"grammar_pl",  new string[]{
"# 複數",
"pāḷi：bahuvacana",
"```",
"Bahūnamatthānaṃ vacanaṃ bahuvacanaṃ.",
"表達“有多個”含義的用語，為複數。",
"```",
}},
  {"grammar_sg",  new string[]{
"# 單數",
"pāḷi：ekavacana",
"```",
"ekassatthassa vacanaṃ ekavacanaṃ.——“Saddanītippakaraṇaṃ”",
"表示“一個”含義的用語，為單數。——《論語法》",
"```",
}},
  {"channel_guide",  new string[]{
"## 什麼是版本風格?",
"",
"在我們在學習、翻譯某段巴利文獻時，需要記錄一些東西，例如：母語譯文、非母語譯文、隨堂筆記、註釋等等。",
"在記錄這些內容時，我們需要**標註**這些文字是**什麼內容類型**和**什麼語言**，這就是**版本風格**。",
"",
"可以實現**多語言**和多種**行文風格**，例如：",
"- 巴利直譯",
"- 註釋",
"- 演講稿",
"- 草稿",
"- grammatical translation",
"- commentaries",
"- speech text",
"- draft",
"",
"這些**版本風格**會顯示為：名稱-語言@使用者暱稱，例如：",
"",
"- 巴利直譯-中文@Bhikkhu Kosalla",
"",
"還可以利用此功能實現的其他功能，等待大家的挖掘。",
}},
  {"grammar_verb",  new string[]{
"# 动词",
}},
  {"studio_part_meaning",  new string[]{
"## 拆分含義",
"此處的設計是針對**信達雅**三大翻譯指標中的**信**，即學術嚴謹性，可以通過拆分和拆分含義，實現詞源學的探索。",
"",
"在**拆分方式**中用加號“+”將巴利拼寫分隔之後，系統會根據每個組分的拼寫進行自動查詢",
"",
"查詢結果的第一個會顯示，其他結果在下拉選單中",
"",
"點選<svg viewBox=\"0 0 24 24\" id=\"ic_vertical_align_top\" style='fill:#6baaff;height: 12px; width: 20px;'><path d=\"M8 11h3v10h2V11h3l-4-4-4 4zM4 3v2h16V3H4z\"></path></svg>按鈕可以將未 **[括起來]** 的部分覆蓋到 **整體含義** 來實現快捷輸入",
"",
"如果對譯文不滿意，可以點選<svg viewBox=\"0 0 24 24\" id=\"ic_mode_edit\" style='fill:#6baaff;height: 12px; width: 20px;'><path d=\"M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04a.996.996 0 0 0 0-1.41l-2.34-2.34a.996.996 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z\"></path></svg>按鈕來手動修改譯文",
"- 注意保證**拆分含義**的“+”和**拆分方式**中的“+”數量保持一致",
"- 如果**拆分含義**的“+”數量小於**拆分方式**中的“+”，那麼系統將自動填充 “↓↓” 來提示使用者檢視此處的下拉選單",
"- 如果**拆分含義**的“+”數量大於**拆分方式**中的“+”，那麼系統將自動把最後兩個組分含義合併",
"  ",
"## 個人單詞本",
"拆分方式和拆分含義在進入[單詞本](./setting.php?item=userdict)的時候，會在基礎單詞資料塊的基礎上，增加和拆分數目相同的單詞資料塊",
"",
"- 內容會被簡化為拼寫+含義，語法類型程式碼為**待定組分**",
"- 比如：attha+saṃhita 義+已攜帶，會增加2條單詞資料到[單詞本](./setting.php?item=userdict)",
"",
"| 拼寫    | 含義   | 類型     |",
"| ------- | ------ | -------- |",
"| attha   | 義     | 待定組分 |",
"| saṃhita | 已攜帶 | 待定組分 |",
}},
  {"grammar_loc",  new string[]{
"# 處格",
"pāḷi：bhummavacana",
"別名：位置格，依格",
"```",
"Bhummavacanaṃ nāma tappatiṭṭhāparidīpanattho.",
"```",
"例句：2000多年前的**一個月圓夜**，王子為了解脫煩惱，從祖國出發，策馬前往荒野。",
}},
  {"grammar_voc",  new string[]{
"# 呼格",
"pāḷi：āmantanavacana",
"```",
"Āmantanavacanaṃ nāma tadāmantanaparidīpanattho.",
"```",
}},
  {"grammar_m",  new string[]{
"# 陽性",
"pāḷi：puma",
"本意：雄性、男性；",
"除了表示人等有性別的生物之外，在其他事物的詞彙上並沒有一定之規。",
}},
  {"grammar_abl",  new string[]{
"# 來源格",
"pāḷi：nissakkavacana，",
"",
"別名：離格，奪格，從格",
"```",
"Nissakkavacanaṃ nāma tannissaṭatadapagamaparidīpanattho.",
"```",
"例句：2000多年前的一個月圓夜，王子為了解脫煩惱，**從祖國**出發，策馬前往荒野。",
}},
  {"studio_general_meaning",  new string[]{
"## 整體意思與虛詞公式",
"在這裡輸入的含義，會被系統自動根據**語法資訊**來套用**虛詞公式**；",
"### 點詞查詢",
"- 點選某個單詞",
"- 點開右上角的<svg id=\"icon_dict\" viewBox=\"0 0 32 32\" style='fill:#6baaff;height: 10px; width: 15px;'><g transform=\"translate(-4 -4)\"><path class=\"a\" d=\"M24.4,2,17.9,7.85v14.3l6.5-5.85V2M8.15,5.9A12.09,12.09,0,0,0,1,7.85V26.908a.7.7,0,0,0,.65.65c.13,0,.195-.091.325-.091A15.85,15.85,0,0,1,8.15,26.05,12.09,12.09,0,0,1,15.3,28a15.659,15.659,0,0,1,7.15-1.95,13.241,13.241,0,0,1,6.175,1.378.565.565,0,0,0,.325.039.7.7,0,0,0,.65-.65V7.85A8.867,8.867,0,0,0,27,6.55V24.1a15.106,15.106,0,0,0-4.55-.65A15.659,15.659,0,0,0,15.3,25.4V7.85A12.09,12.09,0,0,0,8.15,5.9Z\" transform=\"translate(5 4)\"></path></g></svg>中",
"- 右側邊欄會顯示詞典查詢結果",
"",
"在本行末端的<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>可以顯示系統匹配的含義列表，通過點選實現快捷輸入",
"",
"",
"註：",
"- 此處的設計是針對**信達雅**三大翻譯指標中的**達**，即優先追求含義表達的明確性",
"- 對於詞源學我們設計了**拆分方式**與**拆分含義**",
"- 文學優美性我們提供了**整體譯文**",
"- **虛詞公式**可能會有遺漏，如有補充，歡迎通過此[連結](https://github.com/iapt-platform/mint/issues/20)給我們留言。",
}},
  {"grammar_nt",  new string[]{
"# 中性",
"pāḷi：napuṃsaka",
"本意：非雄，不是男的",
}},
  {"studio_break_down",  new string[]{
"## 拆分資訊",
"巴利語拆分是從詞源入手進行語義解析的重要手段。",
"",
"使用者可以根據自己的意願決定把單詞拆到什麼程度。",
"",
"如果用加號“+”分隔每個組分，機器會自動識別並查詢相應的組分。",
"",
"如果是連讀詞（sandhi）是可以進行進一步拆解和分別分析的。",
"",
"如果不清楚如何拆分，有幾種渠道可供選擇：",
"- 點詞查詢",
"  - 點選某個單詞，點開右上角的<svg id=\"icon_dict\" viewBox=\"0 0 32 32\" style='fill:#6baaff;height: 10px; width: 15px;'><g transform=\"translate(-4 -4)\"><path class=\"a\" d=\"M24.4,2,17.9,7.85v14.3l6.5-5.85V2M8.15,5.9A12.09,12.09,0,0,0,1,7.85V26.908a.7.7,0,0,0,.65.65c.13,0,.195-.091.325-.091A15.85,15.85,0,0,1,8.15,26.05,12.09,12.09,0,0,1,15.3,28a15.659,15.659,0,0,1,7.15-1.95,13.241,13.241,0,0,1,6.175,1.378.565.565,0,0,0,.325.039.7.7,0,0,0,.65-.65V7.85A8.867,8.867,0,0,0,27,6.55V24.1a15.106,15.106,0,0,0-4.55-.65A15.659,15.659,0,0,0,15.3,25.4V7.85A12.09,12.09,0,0,0,8.15,5.9Z\" transform=\"translate(5 4)\"></path></g></svg>中會顯示詞典查詢結果。",
"  - 很多長詞在巴緬詞典（共三本）中能找到拆分結果",
"- **強力拆分**功能",
"- 詢問老師",
}},
  {"dict_search_input",  new string[]{
"## 智慧詞典",
"",
"輸入框中支援用**加號**分隔單詞中各個組成部分。",
"- 如：輸入citta+kamma",
"",
"其組分將在輸入框下方顯示，點選搜尋框下方的**組分**查詢每個組分的意思。",
"",
"點選左側的詞典列表中的**詞典名稱**，可以進行詞條跳轉。",
"",
"詞典列表下方的**拼寫列表**中，窮舉了一切存在的**變化形式**以及在語料庫中的出現頻率。",
}},
  {"grammar_gen",  new string[]{
"# 屬格",
"pāḷi：sāmivacana",
"別名：所有格",
"```",
"Sāmivacanaṃ nāma tadissaraparidīpanattho.",
"```",
"例句：**2000多年前的**一個月圓夜，王子為了解脫煩惱，從祖國出發，策馬前往**其他國家的**荒野。",
}},
  {"library",  new string[]{
}},
  {"markdown_guide",  new string[]{
"# 譯文輸入範例指南",
"## 文字樣式",
"|輸入|顯示|",
"|-|-|",
"|`[[pāḷi]]`|[術語<sub>1</sub>]()(pāḷi, 術語<sub>2</sub>)|",
"|`**粗體**`|**粗體**|",
"|`*斜體*`|*斜體*|",
"|`***粗斜體***`|***粗斜體***|",
"|`~~校對刪除~~`|~~校對刪除~~|",
"|`[連結標題](www.wikipali.org \"註&#10;釋\")`|[連結標題](www.wikipali.org \"註&#10;釋\")|",
"|\\`内容`||",
"",
"## 段落樣式",
"",
"",
"<div style=\"display:flex;\">",
"",
"<div style=\"flex:1;margin-right:1em;\">",
"",
"### **輸入**",
"```",
"單回車不折行",
"雙回車",
"",
"真換行",
"",
"---",
"分割線---前需要雙回車",
"```",
"</div>",
"<div style=\"flex:1;\">",
"",
"### **顯示**",
"",
"單回車不折行",
"雙回車",
"",
"真換行",
"",
"---",
"分割線---前需要雙回車",
"</div></div>",
}},
  {"grammar_acc",  new string[]{
"# 賓格",
"pāḷi：upayogavacana",
"",
"別名：業格，受格、對格",
"```",
"Upayogavacanaṃ nāma yo yaṃ karoti, tena tadupayuttaparidīpanattho.",
"```",
"例句：2000多年前的一個月圓夜，王子為了解脫煩惱，從祖國出發，策馬前往**荒野**。",
}},
  {"sent_func",  new string[]{
"## 句子編號功能",
"### 在逐詞解析中新增巴利原文註釋",
"(文字暫無)",
"- [YouTube](https://youtu.be/phRFoQbAh8s)",
"- [百度網盤](https://pan.baidu.com/s/1Vs0evu9q6np1l8GRU9auug) 提取碼：pali",
}},
  {"SUMMARY",  new string[]{
}},
  {"comp_split",  new string[]{
"## 複合詞強力拆分",
"",
"點選此按鈕可以拆分長複合詞",
"1. 基於AI演算法，我們給出**可能性**最高的拆分結果。",
"2. 點選拆分結果後面的**數字**可以顯示可能的拆分列表。",
"3. 使用者可以通過點選**每個組分**來進行字典查詢。",
}},
  {"grammar_abs",  new string[]{
"# 连续体",
"",
"|语种|缩写|全称|",
"|-|-|-|",
"|巴利|——||",
"|汉|**连续**|连续体<br>独立体<br>绝对体|",
"|英|**ger.**<br>abs.|gerund|",
}},
  {"academy",  new string[]{
}},
  {"grammar_dat",  new string[]{
"# 目的格",
"pāḷi：sampadānavacana",
"別名：與格，為格",
"```",
"Sampadānavacanaṃ nāma tappadānaparidīpanattho.",
"```",
"例句：2000多年前的一個月圓夜，王子**為了解脫煩惱**，從祖國出發，策馬前往荒野。",
}},
  {"studio_parent",  new string[]{
"## 詞典原型",
"此處為該處詞語在查詞時應該查詢的拼寫，通常是：",
"- 動詞去掉變位後，加上ti",
"  - 如：karoma的原型寫為karo(ti)",
"- 名詞、三性詞去掉變格",
"  - cittena的原型為citta",
"",
"正確輸入詞典原型，會在個人單詞本中加入原型資料，利用該原型資料可以對其他變化詞給出相對準確的含義。",
"- 例如：cittena的**詞典原型**中輸入了citta，當以後遇到cittehi，cittāni會優先給出個人單詞本中citta的資料。",
"",
"但如果是複合詞拆分之後的元件，可以寫衍生詞的原型",
"- karonta的原型為karo(ti)",
"",
"",
"註：",
"- 針對多層級變化衍生的關係，比如從詞根到詞幹，動詞到分詞，分詞到變格；我們不建議在此處進行多層級拆解",
"- 我們設計了另一個強大的工具來實現**詞源學探索的終極解決方案**——wordmap",
"- 該wordmap工具在離線版的試驗中可用，線上版有待恢復和重新設計",
}},
  {"studio_case_fomular",  new string[]{
"### 虛詞公式",
"- 我們在本行的",
"<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>",
"    中列舉了與該**語法資訊**相應的虛詞公式",
"- 如果對自動套用的虛詞公式不滿意，可用從<span><svg viewBox='0 0 24 24' id='ic_more' style='fill:#6baaff;height: 10px; width: 15px;'><path d='M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.97.89 1.66.89H22c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm5 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z'></path></svg></span>中選擇。",
"- 自動給出的公式顯示為<span style='color:#BD8B18;'>金黃色</span>，且該公式不會進入[個人單詞本](./setting.php?item=userdict)",
"- 手動選擇的公式顯示為<span style='color:#f9468f;'>粉紅色</span>，且該公式會進入[個人單詞本](./setting.php?item=userdict)",
"- 通過**虛詞公式**可以加深我們對語法概念的理解",
"- 初學者也可以透過調整**語法資訊**和**虛詞公式**來實現**格位**、**變位**的抉擇",
}},
  {"studio",  new string[]{
}},
  {"grammar_f",  new string[]{
"# 陰性",
"pāḷi：itthī",
"本意：女性、雌性",
"除了表示人等有性別的生物之外，在其他事物的詞彙上並沒有一定之規。",
}},
  {"readme",  new string[]{
}},
  {"term_pedia_sys",  new string[]{
"## 术语百科系统",
"术语+注释书名词解释=巴利百科词条",
"### 视频演示",
"",
"",
"### 具体操作",
"* 首先创建术语",
"* 然后复制句子编号",
"* 将句子编号黏贴到下面的输入框中",
"* 系统会自动根据句子编号，返回巴利原文、译文以及引用路径",
}},
  {"grammar_nom",  new string[]{
"# 主格",
"pāḷi：paccattavacana",
"原意：獨自的用語",
"別名：體格",
"```",
"Tatra paccattavacanaṃ nāma tividhaliṅgavavatthānagatānaṃ itthipumanapuṃsakānaṃ paccattasabhāvaniddesattho.",
"——《論語法》",
"```",
"名詞的變化形式之一，大部分情況在句子中扮演動作的發出者，如下文黑體字。",
"例句：2000多年前的一個月圓夜，**王子**為了解脫煩惱，從祖國出發，策馬前往荒野。",
}},
  {"grammar_abbr",  new string[]{
"## 基本操作",
"- 通過下拉選單選擇填入語法資訊",
"- 首先選定類型——帶外框的，比如：動詞",
"- 然後選擇後續的內容，比如：三 單 現",
"- 以上涉及的**語法縮略語**可以參照下面的表格",
"- 調整**語法資訊**和**虛詞公式**，列舉這個詞可能的含義",
"",
"## 連讀詞拆分",
"連讀詞拆分使用教程 （暫缺）",
"",
"## 複合詞拆分",
"複合詞拆分使用教程（文字暫缺）",
"- [YouTube](https://youtu.be/iN1t0Rq9aKk \"按住Ctrl鍵點開\")",
"- [優酷](https://v.youku.com/v_show/id_XNDgwOTg4NDQ4MA==.html \"按住Ctrl鍵點開\")",
"- [百度網盤](https://pan.baidu.com/s/1nXZG2GQkkkfblNnshDuS_w \"按住Ctrl鍵點開\")  提取碼：pali ",
"",
"## 語法縮略語表",
"| 縮略語   | 英文縮寫  | 備註                         |",
"| :------- | :-------- | :--------------------------- |",
"| 名       | n.        | noun                         |",
"| 動       | v.        | verb                         |",
"| 三性     | n.a.      | three genders.               |",
"| 形       | adj.      | 形容詞                       |",
"| 不變     | ind.      | indeclinable (nipāta)        |",
"| 代       | pron.     | pronoun                      |",
"| 動不變   | v. ind.   | indeclinable (-tvā, sighaṃ)  |",
"| 數       | num.      | numerals                     |",
"| 黏音     | slur.     | sandhi                       |",
"| 複合     | comp.     | compound(samāsa)             |",
"| 代詞幹   | pron:base | amha                         | amhākaṃ |",
"| 三性詞幹 | ti:base   | gacchanta mahallaka          |",
"| 形詞幹   | adj:base  | mahallaka 傳統分類歸屬三性詞 |",
"| 名詞幹   | n:base    | gāma                         |",
"| 數詞幹   | num:base  | ti                           |",
"| 字首     | prefix    | na-, vi-, saṃ-               |",
"| 詞根     | root      | gamu                         |",
"| 字尾     | suffix    | (-ika, -ana, -tā)            |",
"| 語尾     | case end  | vibhatti (-ena, -ehi)        |",
"| 動原型   | v:base    | karo(ti) gaccha(ti)          |",
"| 原版註釋 | note      | sī sya                       |",
}},
  {"studio_term",  new string[]{
"## 术语大兼容系统",
"在佛教翻译中，术语使用在历史沿革中一直存在大量争论，这是在纸媒体的时代永远无法解决的。",
"",
"然而在电子阅读时代，这个问题是可以通过兼容的方式，同时照顾**译者**和**读者**两大群体的感受。",
"",
"### 视频演示",
"- [YouTube](https://youtu.be/NdXgxo5YAIo \"按住Ctrl键点开\")",
"- 优酷",
"### 操作方法",
"- 点击逐词解析中的术语",
"- 检查**词典原型**是否为空，如果为空请填入去掉变化之后的能够在词典中查询到的**原型**",
"- 点击页面右上角的<svg id=\"icon_term\" viewBox=\"0 0 24 24\" style='fill:#6baaff;height: 15px; width: 15px;'><path d=\"M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z\"></path></svg>调出侧边栏",
"- 点击**新建**按钮，在其中键入**首选术语**(必填)，其他为选填",
"- 之后，在键入译文的时候，如下：",
"```",
"[[isipatana]] [[migadāya]]：由仙人们起飞和降落而得名。由于给予[[miga]]安全感，而划定为[[migadāya]]的区域。",
"```",
"<b>[[pāḷi]]</b>会被自动替换，最终显示为：",
"```",
"落仙坪(isipatana 仙人降落处,仙人堕处,仙人落处 ) 野生保护(区)(migadāya 鹿野苑 )：由仙人们起飞和降落而得名。由于给予野兽(miga 鹿,野生动物 )安全感，而划定为野生保护(区)的区域。",
"```",
"注：该替换优先依照读者的个性化术语系统",
}},
  {"studio_parent2",  new string[]{
"## 衍生原型",
"範例：",
"- 拼寫：karontassa",
"- 詞典原型：karonta（現代分詞）",
"- 此處：karo(ti)",
"- 下拉選單選擇：prp（現代分詞）",
}},
  {"grammar_inst",  new string[]{
"# 工具格",
"pāḷi：karaṇavacanaṃ",
"別名：具格，具做格",
"```",
"Karaṇavacanaṃ nāma tajjāpakatanibbattakaparidīpanattho.",
"```",
"例句：2000多年前的一個月圓夜，王子為了解脫煩惱，從祖國出發，**策馬**前往荒野。",
}},
  {"grammar_consonant",  new string[]{
"# 輔音",
"又名子音",
}},
};


    public static Dictionary<string, string> grm_abbr = new Dictionary<string, string>(){
{"語基","base"},
{"语基","base"},
{"indecl．","ind"},
{"[adj．]","adj"},
{"[adj.]","adj"},
{"[adv．]","adv"},
{"[adv.]","adv"},
{"[ind．]","ind"},
{"[ind.]","ind"},
{"denom.","denom"},
{"denom．","denom"},
{"imper.","imp"},
{"imper．","imp"},
{"instr．","inst"},
{"instr.","inst"},
{"Instr.","inst"},
{"Instr．","inst"},
{"ppr-a.","prp"},
{"ppr-p.","prp"},
{"（bya）","ind"},
{"（kri）","verb"},
{"（thī）","f"},
{"（thī，","f"},
{"，thī）","f"},
{"caus．","caus"},
{"caus.","caus"},
{"Caus．","caus"},
{"cond.","cond"},
{"fp-a.","prp"},
{"ind．","ind"},
{"inst．","inst"},
{"inst.","inst"},
{"Inst．","inst"},
{"pr.p.","prp"},
{"pref．","pref"},
{"pres.","pres"},
{"pron．","pron"},
{"pron.","pron"},
{"Vism．","vism"},
{"（m．）","m"},
{"（m．)","m"},
{"（na）","nt"},
{"（na，","nt"},
{"（pa）","m"},
{"（pu）","m"},
{"（pu，","m"},
{"（ti）","ti"},
{"，na）","nt"},
{"[a．]","adj"},
{"[a.]","adj"},
{"[f．]","f"},
{"[f.]","f"},
{"[m．]","m"},
{"[m.]","m"},
{"[n．]","nt"},
{"[n.]","nt"},
{"【过分】","pp"},
{"【现分】","prp"},
{"【字首】","pref"},
{"abl．","abl"},
{"abl.","abl"},
{"Abl.","abl"},
{"Abl．","abl"},
{"acc．","acc"},
{"acc.","acc"},
{"Acc.","acc"},
{"Acc．","acc"},
{"adj．","adj"},
{"adv．","adv"},
{"adv.","adv"},
{"aor．","aor"},
{"aor.","aor"},
{"BSk．","bsk"},
{"Bsk．","bsk"},
{"dat．","dat"},
{"dat.","dat"},
{"Dat.","dat"},
{"Dat．","dat"},
{"fpp.","fpp"},
{"fpp．","fpp"},
{"fut.","fut"},
{"fut．","fut"},
{"Fut．","fut"},
{"gen．","gen"},
{"gen.","gen"},
{"Gen.","gen"},
{"Gen．","gen"},
{"ger．","abs"},
{"ger.","abs"},
{"Ger.","abs"},
{"Ger．","abs"},
{"grd．","fpp"},
{"grd.","fpp"},
{"imp.","imp"},
{"imp．","imp"},
{"loc．","loc"},
{"loc.","loc"},
{"Loc.","loc"},
{"Loc．","loc"},
{"nom．","nom"},
{"nom.","nom"},
{"Nom.","nom"},
{"Nom．","nom"},
{"num．","num"},
{"num.","num"},
{"opt．","opt"},
{"opt.","opt"},
{"ppr．","prp"},
{"ppr.","prp"},
{"prp.","prp"},
{"prp．","prp"},
{"Vin．","vinaya"},
{"voc．","voc"},
{"voc.","voc"},
{"Voc.","voc"},
{"Voc．","voc"},
{"（i）","f"},
{"：a．","adj"},
{"【不】","ind"},
{"【独】","abs"},
{"【副】","adv"},
{"【过】","aor"},
{"【 过】","aor"},
{"【合】","incomp"},
{"【祈】","opt"},
{"【潜】","opt"},
{"【三】","ti"},
{"【无】","ind"},
{"【形】","adj"},
{"【阳】","m"},
{"【阴】","f"},
{"【中】","nt"},
{"1p.","1p"},
{"1p．","1p"},
{"2p.","2p"},
{"2p．","2p"},
{"3p.","3p"},
{"3p．","3p"},
{"cf．","cf"},
{"cf.","cf"},
{"nt．","nt"},
{"nt.","nt"},
{"pl．","pl"},
{"pl.","pl"},
{"pp.","pp"},
{"pp．","pp"},
{"pr.","pr"},
{"pr．","pr"},
{"sg．","sg"},
{"sg.","sg"},
{"Sk．","sk"},
{"（梵","bsk"},
{"f．","f"},
{"f.","f"},
{"m．","m"},
{"m.","m"},
{"n．","nt"},
{"n.","nt"},
{"子音","consonant"},
};

    //public static Dictionary<string, string> myEnding = new Dictionary<string, string>()
    //{
    //    {"သည်","my_nom1" },//'主语',
    //    {"ကား","my_nom2" },//主格/主语
    //    {"က","my_nom3" },//主格/主语
    //    {"ကို","my_acc1" },//宾格/宾语
    //    {"သို့","my_acc2" },//宾格/趋向
    //    {"ဖြင့်","my_inst1" },//具格/用

    //    {"နှင့်","my_inst2" },//具格/与

    //    {"ကြောင့်","my_inst3" },//具格/凭借;从格/原因
    //    {"ကြောင်း","my_inst3" },//具格/凭借;从格/原因
    //    {"အား","my_dat1" },//目的格/对象(间接宾语)，对……来说
    //    {"ငှာ","my_dat2" },//目的格/表示目的，为了……
    //    {"အတွက်","my_dat2" }, //目的格/表示目的，为了……
    //    {"မှ","my_abl1" }, //从格/表示来源，从……
    //    {"အောက်","my_abl2" }, //从格/表达比较，比……多
    //    {"ထက်","my_abl3" }, //从格/表达比较，比……少
    //    {"၏","my_gen1" }, //属格/的
    //    {"တွင်","my_gen2" }, //属格/表达范围，……中的
    //    {"၌","my_loc1" }, //处格/处(范围
    //    {"ကြောင့်","my_loc2" }, //处格/表达动机，因……，旨在……

    //    {"၍","my_abs" }, //连续体

    //    {"တို့","my_pl" }, //复数
    //    {"များ","my_pl" }, //复数
    //    {"ကုန်","my_pl" }, //复数
    //    {"ကြ","my_pl" }, //复数
    //    {"ပတ်လုံး","my_time" }, //时间的整数
    //    {"လုံလုံး","my_time" }, //时间的整数
    //    {"တိုင်တိုင်","my_length" }, //距离,长度的整数
    //    {"တိုင်အောင်","my_length" }, //距离,长度的整数
    //    {"နေစဉ်","my_def" }, //同时发生的时间状语(当……的时候)
    //    {"လျက်","my_def" }, //同时发生的时间状语(当……的时候)
    //};
    //let myEnding =[
    //    {
    //        id: "my_nom1",
    //     name: "သည်",
    //     tooltip: '主语',
    //    },
    //    {
    //        id:"my_nom2",
    //        name:"ကား",
    //        tooltip:'主格/主语',
    //    },        
    //    {
    //        id:"my_nom3",
    //        name:"က",
    //        tooltip:'主格/主语',
    //    },        
    //    {
    //        id:"my_acc1",
    //        name:"ကို",
    //        tooltip:'宾格/宾语',
    //    },
    //    {
    //        id:"my_acc2",
    //        name:"သို့",
    //        tooltip:'宾格/趋向',
    //    },
    //    {
    //        id:"my_inst1",
    //        name:"ဖြင့်",
    //        tooltip:'具格/用',
    //    },
    //    {
    //        id:"my_inst2",
    //        name:"နှင့်",
    //        tooltip:'具格/与',
    //    },
    //    {
    //        id:"my_inst2",
    //        name:"နှင့်",
    //        tooltip:'具格/与',
    //    },
    //    {
    //        id:"my_inst3",
    //        name:"ကြောင့်",
    //        tooltip:'具格/凭借;从格/原因',
    //    },
    //    {
    //        id:"my_inst3",
    //        name:"ကြောင်း",
    //        tooltip:'具格/凭借;从格/原因',
    //    },
    //    {
    //        id:"my_dat1",
    //        name:"အား",
    //        tooltip:'目的格/对象(间接宾语)，对……来说',
    //    },
    //    {
    //        id:"my_dat2",
    //        name:"ငှာ",
    //        tooltip:'目的格/表示目的，为了……',
    //    },
    //    {
    //        id:"my_dat2",
    //        name:"အတွက်",
    //        tooltip:'目的格/表示目的，为了……',
    //    },
    //    {
    //        id:"my_abl1",
    //        name:"မှ",
    //        tooltip:'从格/表示来源，从……',
    //    },
    //    {
    //        id:"my_abl2",
    //        name:"အောက်",
    //        tooltip:'从格/表达比较，比……多',
    //    },
    //    {
    //        id:"my_abl3",
    //        name:"ထက်",
    //        tooltip:'从格/表达比较，比……少',
    //    },
    //    {
    //        id:"my_gen1",
    //        name:"၏",
    //        tooltip:'属格/的',
    //    },
    //    {
    //        id:"my_gen2",
    //        name:"တွင်",
    //        tooltip:'属格/表达范围，……中的',
    //    },
    //    {
    //        id:"my_loc1",
    //        name:"၌",
    //        tooltip:'处格/处(范围)',
    //    },
    //    {
    //        id:"my_loc2",
    //        name:"ကြောင့်",
    //        tooltip:'处格/表达动机，因……，旨在……',
    //    },
    //    {
    //        id:"my_abs",
    //        name:"၍",
    //        tooltip:'连续体',
    //    },
    //    {
    //        id:"my_pl",
    //        name:"တို့",
    //        tooltip:'复数',
    //    },
    //    {
    //        id:"my_pl",
    //        name:"များ",
    //        tooltip:'复数',
    //    },
    //    {
    //        id:"my_pl",
    //        name:"ကုန်",
    //        tooltip:'复数',
    //    },
    //    {
    //        id:"my_pl",
    //        name:"ကြ",
    //        tooltip:'复数',
    //    },
    //    {
    //        id:"my_time",
    //        name:"ပတ်လုံး",
    //        tooltip:'时间的整数',
    //    },
    //    {
    //        id:"my_time",
    //        name:"လုံလုံး",
    //        tooltip:'时间的整数',
    //    },
    //    {
    //        id:"my_length",
    //        name:"တိုင်တိုင်",
    //        tooltip:'距离,长度的整数',
    //    },
    //    {
    //        id:"my_length",
    //        name:"တိုင်အောင်",
    //        tooltip:'距离,长度的整数',
    //    },
    //    {
    //        id:"my_def",
    //        name:"နေစဉ်",
    //        tooltip:'同时发生的时间状语(当……的时候)',
    //    },
    //    {
    //        id:"my_def",
    //        name:"လျက်",
    //        tooltip:'同时发生的时间状语(当……的时候)',
    //    },
    //];


}